#import "../../main-defs.typ": source
#import "defs.typ": *

=== Semifields of order 32 and Knuth–Rúa’s counter-example
<sec:l2017-quasifields-order32>

The Knuth–Rúa semifield $KRu$ of order 32 with the identity $x^("(" 22) = x$ is
commutative and presents the first counter-example to Wene’s hypotheses of
primitivity for finite semifields. We describe its automorphisms.

#theorem[
  The automorphism group $Aut KRu$ of Knuth–Rúa semifield $KRu$ is a cyclic
  group of order 5 and the set $KRu without {0,e}$ is an union of six disjoint
  orbits under $Aut KRu$.
] <th:l2017-quasifields-knuth-rua-automorphisms>

The problems (A)–(C) for semifield $KRu$ are solved in
([@bib:l2017-quasifields-Shtukkert2014, @bib:l2017-quasifields-Levchuk2015]).

#theorem[
  The loop $KRu^*$ of Knuth–Rúa semifield $KRu$ of order 32 is generated by any
  non-identity element. Its spectrum is ${1,5,6,7,8,10}$ and right and, also,
  left spectra are ${1,21}$.
] <th:l2017-quasifields-knuth-rua-spectra>

Up to isomorphism, there are 2501 proper semifields of order 32; they form 6
isotopic classes corresponding to six pairwise nonisomorphic planes $pi(i)$
($0 <= i <= 5$). The following Table~@tab:l2017-quasifields-order32
[@bib:l2017-quasifields-Rua2004] reflects other information.

Let’s consider as [@bib:l2017-quasifields-Shtukkert2014] the spread sets of
non-isomorphic semifield planes from [@bib:l2017-quasifields-DempwolffNoDate].
The correspondent coordinatizing semifields $P_j$ ($1 <= j <= 5$), up to
isotopisms, exhauste all proper semifields of order 32. Their structure is
determined by following theorems which are proved in
[@bib:l2017-quasifields-Shtukkert2014].

#theorem[
  For any semifields $P_i$, $1 <= i <= 4$, the subfield of order 2 is a maximal
  subfield. The loop $P_i^*$ is generated by any non-identity element, and the
  spectrum of loop is ${1,4,5,6,7,8}$ for $i = 3$, or ${1,5,6,7,8,9}$ for
  $i = 4$ or ${1,4,5,6,7}$ for $i = 1,2$.
] <th:l2017-quasifields-p1-p4-spectra>

#source(7, printed: 694)

#figure(
  table(
    columns: 7,
    table.header(
      [Plane], [$pi(0)$], [$pi(1)$], [$pi(2)$], [$pi(3)$], [$pi(4)$], [$pi(5)$]
    ),
    [Left and right primitive], [1], [961], [961], [180], [186], [186],
    [Only left primitive], [0], [0], [0], [6], [0], [7],
    [Only right primitive], [0], [0], [0], [6], [7], [0],
    [Neither L. nor R. prim.], [0], [0], [0], [1], [0], [0],
  ),
  kind: table,
  caption: [Isomorphic classes of semifields of order 32],
) <tab:l2017-quasifields-order32>

According to [@bib:l2017-quasifields-Rua2004] there exists a semifield of order
32 with a subfield of order 4. By Theorem
@th:l2017-quasifields-knuth-rua-spectra, the prime subfield of Knuth–Rúa
semifield is unique its subfield. Evidently that order of any finite semifield
equals to some powers of right and left nuclei orders. So the nuclei of
semifield of order 32 are necessary prime subfield. Nevertheless such semifields
can contain a subfield of order 4.

#theorem[
  The semifield $P_5$ contains the subfield $H$ of order 4, that is unique
  maximal subfield. Each element from $P_5 without H$ is of order $> 3$ and
  generates the loop $P_5^*$, the spectrum of the loop is ${1,3,4,5,6,7,8}$.
] <th:l2017-quasifields-p5-subfield>
