#import "../../main-defs.typ": source
#import "defs.typ": *

#source(9, printed: 696)

=== Quasifields of orders 16, 32 and 81 <sec:l2017-quasifields-orders>

According to Dempwolff and Reifart (1983,
[@bib:l2017-quasifields-Dempwolff1983]), the number of all non-desarguesian
translation planes of order 16 equals to 7. Its spread sets allow to construct
the representatives of quasifields isotopic classes.

For correspondent representatives $Q_j$, $1 <= j <= 5$, of isotopic classes
without semifields the next theorem is proved
[@bib:l2017-quasifields-Shtukkert2014].

#theorem[
  Any quasifield $Q_j$, $j = 1,2,3$, is a set-theoretic union of 7 maximal
  subfields of order 4 and all its spectra coincide with ${1,3}$.
] <th:l2017-quasifields-q1-q3-subfields>

#theorem[
  For the quasifield $Q_4$ the kernel is unique maximal subfield of order 4. The
  quasifield $Q_5$ contains 3 maximal subfields of order 4 and its kernel is of
  order 2. The loop $Q_j^*$, $j = 4,5$, is generated by any element which is not
  from maximal subfields, and all its spectra are ${1,3,5}$.
] <th:l2017-quasifields-q4-q5-subfields>

Knuth was constructed (see [@bib:l2017-quasifields-Knuth1965]) the projective
planes $pi(i)$ ($1 <= i <= 5$) of order 32 and was proved that these planes
exhauste, up to isomorphisms, all non-desarguesian semifield planes of order 32.

So the proper semifields of order 32 are determined, up to isotopisms, as
corresponding coordinatizing sets $P_j$ ($1 <= j <= 5$) (the semifields of order
32 are classified also by Walker (1962, [@bib:l2017-quasifields-Walker1962])).
The structure of these semifields are determined by next two theorems
[@bib:l2017-quasifields-Shtukkert2014].

#theorem[
  The semifield $P_5$ contains the subfield $H$ of order 4, that is a unique
  maximal subfield. Any element from $P_5 without H$ generates the loop $P_5^*$,
  the element order is more than 3, the loop spectrum is ${1,3,4,5,6,7,8}$.
] <th:l2017-quasifields-p5-repeated>

#theorem[
  Any semifield $P_i$, $1 <= i <= 4$, contains only minimal subfield. The loop
  $P_i^*$ is generated by any non-identity element, the loop spectrum is
  ${1,4,5,6,7,8}$ for $i = 3$, ${1,5,6,7,8,9}$ for $i = 4$ and ${1,4,5,6,7}$ for
  $i = 1,2$.
] <th:l2017-quasifields-p1-p4-repeated>

The classification of translation planes of order 32 has been completed by
Dempwolff and Rockenfeller in 2011 (see [@bib:l2017-quasifields-DempwolffNoDate,
@bib:l2017-quasifields-Rockenfeller2011]).

Up to isomorphisms, except 6 semifield planes (with Desarguesian plane) there
exist exactly 3 translation non-semifield planes of order 32. Using their spread
sets from [@bib:l2017-quasifields-DempwolffNoDate], we can construct the
coordinatizing quasifields $Q_i$, $i = 1,2,3$. Their structure is described in
[@bib:l2017-quasifields-Levchuk2015].

#theorem[
  For quasifields $Q_i$ ($i = 1,2,3$) the prime subfield is maximal, the loop
  $Q_i^*$ is right-primitive, its spectrum is ${1,4,5,6,7}$.
] <th:l2017-quasifields-order32-quasifields>

Further we consider the semifields that coordinatize the semifield planes of
order 81 admitting a Baer involution.

#definition[
  The collineation of finite projective plane $pi$ is said to be _Baer
  collineation_ if it fixes pointwise the subplane $pi_0$ of order
  $|pi_0| = sqrt(|pi|)$.
] <def:l2017-quasifields-baer-collineation>

Let $pi$ be a semifield plane of order 81 that admit a Baer involution. Then,
using [@bib:l2017-quasifields-Kravtsova2016], we can consider coordinatizing
semifield $W$ as a 4-dimensional vector space over $ZZ_3$ and spread set in
$GL_4 lr((3)) union {0}$:

$ R = {mat(m(U), f(V); V, U) | U,V in K}. $

Here $K$ is the field of order 9 in $GL_2 lr((3)) union {0}$,

$ K = {U = u_1 mat(1, 1; 1, 0) + u_2 mat(1, 0; 0, 1) | u_1,u_2 in ZZ_3}, $

$m,f$ are injective maps from $K$ to $GL_2 lr((3)) union {0}$, $m(E) = E$,
$f(E) != E$.

Computer calculations lead to construction of 106 semifield planes of order 81
with Baer involution. Next considerations of isomorphisms give the result:

#theorem[
  There exist exactly 8, up to isomorphisms, non-desarguesian semifield planes
  of order 81, which admit a Baer involution in translation complement.
] <th:l2017-quasifields-order81-planes>

#source(10, printed: 697)

#figure(
  table(
    columns: 4,
    table.header([Semifield $W$], [$|N_l|$], [Spectrum], [Left spectrum]),
    [$W_1$], [3], [${1,2,4,5,6,7,8}$], [${1,2,4,8,16,40,80}$],
    [$W_2$], [3], [${1,2,4,5,6,7,8}$], [${1,2,4,5,8,10,16,20,40,80}$],
    [$W_3$], [3], [${1,2,4,6,7,8}$], [${1,2,4,8,16,40,80}$],
    [$W_4$], [3], [${1,2,4,5,6,7,8,9,10}$], [${1,2,4,8,16,80}$],
    [$W_5$], [9], [${1,2,4,5,6,7,8}$], [${1,2,4,8,16,40,80}$],
    [$W_6$], [9], [${1,2,4,6,7,8}$], [${1,2,4,8,16,80}$],
    [$W_7$], [9], [${1,2,4,6,8,9,13}$], [${1,2,4,8,16,40,80}$],
    [$W_8$], [9], [${1,2,4,6,7,8}$], [${1,2,4,8,16,40,80}$],
  ),
  kind: table,
  caption: [The structure of non-isotopic semifields of order 81, that admit
    automorphism of order 2],
) <tab:l2017-quasifields-order81>

The structure of correspondent coordinatizing semifields $W_i$, $i = 1,dots,8$,
is determined. The results are summarized by
Table~@tab:l2017-quasifields-order81.

#lemma[
  Any semifield $W_i$ admits an automorphism of order 2 and contains 1 or 3
  maximal subfields of order 9. The loop $W_i^*$ is left- and right-primitive,
  it contains a subloop of order 16 and 1 or 3 subgroup of order 4.
] <lem:l2017-quasifields-order81-subfields>

#lemma[
  The semifields $W_3$ and $W_8$ contains exactly three subfields of order 9,
  another semifields contain unique subfield of order 9. The order of
  automorphism group $Aut W$ equals to 8 for $W_8$, 2 for $W_1$ and $W_3$ and 4
  for other semifields.
] <lem:l2017-quasifields-order81-automorphisms>

#heading(level: 3, numbering: none)[Acknowledgments]

This work was funded by the subsidy Russian Foundation for Basic Research,
project 16-01-00707.
