#import "../../main-defs.typ": *
#import "../../collection.typ": paper-abstract, paper-keywords
#import "defs.typ": *
#source(1, printed: 225)
#paper-abstract[
  Automorphisms, isomorphisms and structural descriptions of finitary
  unitriangular groups over a ring and of Sylow subgroups of Chevalley groups
  are studied. Also, the theorem on pair unipotent intersections of Chevalley
  groups has been proved; it is connected with the known question on pair Sylow
  intersections of finite groups. These investigations use close connections and
  structural descriptions of considered groups and associated rings, which have
  been found recently in the case of a commutative ring of coefficients with a
  strongly maximal ideal. We consider some properties and examples of such
  ideals.
]
#paper-keywords[
  Chevalley group, unipotent subgroup, weakly finitary group, associated Lie
  ring, strongly maximal ideal, isomorphism.
]

#heading(level: 3)[
  The Finitary Rings, their Adjoint Groups and Generalizations
] <sec:l2005-sylow-finitary>

Structural descriptions of finitary unitriangular groups over rings and also of
Sylow subgroups and of the unipotent subgroups of the Chevalley group have close
connections with the description of ideals of the associated rings. Such
descriptions are essentially used in investigations of automorphisms and
isomorphisms and of the known question on pair Sylow intersections of finite
groups (see Theorem @th:l2005-sylow-finite-intersections on pair unipotent
intersections), etc.

Let us distinguish a subalgebra $N Phi(K)$ with the basis
$lr({e_r | r in Phi^+})$ in Lie $K$-algebra with the Chevalley basis
$lr({e_r | r in Phi, dots})$ [@bib:l2005-sylow-Carter1972, Sect. 4.4]. The
unipotent subgroup $U Phi(K)$ of the Chevalley group $Phi(K)$ is isomorphic to
the “adjoint” group of $N Phi(K)$ with respect to a certain operation $compose$,
by [@bib:l2005-sylow-Levchuk1990]. It turns to be that the ideals of Lie ring
$N Phi(K)$ and only they are normal subgroups of the group $(N Phi(K), compose)$
for a field $K = 2K$ with $K = 3K$ at $Phi = G_2$; all ideals are also described
in [@bib:l2005-sylow-Levchuk1992]. Similarly, the normal structure of unipotent
subgroups $U G(K)$ of the twisted group of any Lie type $G$ (see Section
@sec:l2005-sylow-intersections) are described in [@bib:l2005-sylow-Levchuk1999,
@bib:l2005-sylow-Suleimanova2000] and
[@bib:l2005-sylow-Levchuk2002Hypercentral]. Note that if $K = Z_(p^m)$ and $J$
is a maximal ideal of $K$, then the product of $U Phi(K)$ and of the congruence
subgroup by $J$-level is a Sylow $p$-subgroup of the Chevalley group $Phi(K)$.
#source(2, printed: 226)
The question concerning a description of its automorphisms
[@bib:l2005-sylow-Kourovka1992, Question 12.42] is still open.

We now consider a generalization of the principal case of Lie type $A_n$. Let
$Gamma$ be a chain by the order relation $<=$. $Gamma$-matrices
$lr(‖a_(i j)‖)_(i,j in Gamma)$ over $K$ having a finite number of nonzero
elements in each row and column are called _weakly finitary_. Weakly finitary
$Gamma$-matrices over an associative ring $K$ (with the identity $1_K$) form a
ring (resp. with the identity) with respect to the usual matrix addition and
multiplication. Now there is little information about this ring in general
cases. Note that if $Gamma$ is an infinite chain and $1_K in K$, then every
countable group can be represented in the multiplicative group of invertible
monomial matrices of this ring.

The subring of all finitary $Gamma$-matrices with $a_(i j) in J$ $(i <= j)$ for
an ideal $J$ of $K$ is denoted by $R_Gamma lr((K,J))$ and by $R_n lr((K,J))$ for
$|Gamma| = n < infinity$. It is clear, that the ring $R_Gamma lr((K,J))$ is
generated by usual elementary $Gamma$-matrices $x e_(i j)$
$(x in K, i,j in Gamma)$, where $x in J$ for $i <= j$.

#example[
  Set $NT_Gamma lr((K)) = R_Gamma lr((K,0))$ and $R = NT_Gamma lr((K))$. If
  $1_K in K$ or even more generally $K^2 = K$, then $R^2 = R$ for every dense
  chain $Gamma$. On the other hand, if $K$ is a ring with the identity of a
  prime characteristic, then the identical $Gamma$-matrix and $R$ generate a
  ring in which $R$ is a maximal ideal. The ring $R$ is always locally nilpotent
  and hence radical. See also [@bib:l2005-sylow-Merzlyakov1995].
] <exm:l2005-sylow-dense-chain>

Recall that the adjoint multiplication $compose$ and the associated Lie
multiplication $*$ of an arbitrary associative ring are defined by
$alpha compose beta = alpha + beta + alpha beta$ and
$alpha * beta = alpha beta - beta alpha$, respectively.

#lemma[
  Let $R = NT_Gamma lr((K))$ and $K = K^2$. A subset of $R$ is a normal subgroup
  of the adjoint group $G(R) = (R, compose)$ if and only if it is an ideal of
  the associated Lie ring $Lambda(R)$.
] <lem:l2005-sylow-normal-lie>

See [@bib:l2005-sylow-Levchuk1987] and also [@bib:l2005-sylow-Kourovka1992,
Question 10.19].

Let $R = NT_Gamma lr((K))$ with $1_K in K$. Similarly choose a ring
$R' = NT(Omega, S)$. If either $K$ is a ring with no zero-divisors or $Gamma$ is
a finite chain of order $!= 3$ or $K$ is a commutative ring and $|Gamma| = 3$,
then the automorphism groups $Aut R$, $Aut Lambda(R)$ and $Aut G(R)$ have been
described in [@bib:l2005-sylow-Levchuk1987], by using close structural
connections. We also study isomorphisms between rings $R$ and $R'$, their
adjoint groups and also associated Lie rings.

Rings $K$ and $S$ are called _idempotent isomorphic_, if there exists an
isomorphism $theta$ of the additive group $K^+$ of $K$ onto $S^+$ with
$theta(1_K) = 1_S$ inducing an isomorphism of the ideal $f K$ and an
anti-isomorphism of the ideal $(1_K-f)K$ for an idempotent $f$ in the center of
$K$. In this case for any anti-isometry $prime: Gamma arrow.r Gamma$
isomorphisms of the adjoint group $G(R)$ and of the associated Lie ring
$Lambda(R)$ are determined (both extensions coincide if and only if $f = 1_K$)
by
$
  x e_(i j) arrow.r.bar theta(x f)e_(i j) - theta(x-x f)e_(j' i')
  quad (x in K, i,j in Gamma, i>j).
$ <pass:l2005-sylow-idempotent-map>

#source(3, printed: 227)
#theorem[
  Let $K$ and $S$ be associative rings with identities, $Gamma$ and $Omega$ be
  chains, $|Gamma|>2$, $R=NT(Gamma, K)$ and $R'=NT(Omega, S)$. Then the
  following holds:

  #enum(
    numbering: "(i)",
    [if $R tilde.eq R'$ and either $|Gamma|<infinity$ or $K$ is a ring with no
      zero-divisors, then the rings $K$ and $S$ are isomorphic and chains
      $Gamma$ and $Omega$ are isometric;

    ],
    [for a ring $K$ with no zero-divisors and $|Gamma|>4$ the adjoint groups
      $G(R)$ and $G(R')$ or associated Lie rings $Lambda(R)$ and $Lambda(R')$
      are isomorphic if and only if either $Gamma tilde.eq Omega, K tilde.eq S$
      or $Gamma tilde.eq Omega^upright("op"), K tilde.eq S^upright("op")$;

    ],
    [for $4<|Gamma|<infinity$ the adjoint groups $G(R)$ and $G(R')$ or
      associated Lie rings $Lambda(R)$ and $Lambda(R')$ are isomorphic if and
      only if rings $K$ and $S$ are idempotent isomorphic and
      $|Gamma|=|Omega|$.],
  )
] <th:l2005-sylow-isomorphisms>

This theorem is proved by F. Kuzucuoglu and the author. Also, under the
conditions of Theorem @th:l2005-sylow-isomorphisms all isomorphisms are
described. Note that by [@bib:l2005-sylow-Levchuk1983], there exist nonstandard
automorphisms of $G(R)$ and of $Lambda(R)$ in exceptional cases $|Gamma|<=4$.

If a ring $K$ or $S$ is commutative and they are idempotent isomorphic, then
they are also isomorphic. An arbitrary isomorphism between the adjoint groups
$G(R)$ and $G(R')$ (resp. associated Lie rings $Lambda(R)$ and $Lambda(R')$) for
a commutative ring $K$ and $2<|Gamma|<infinity$ is described as follows. It
equals to a product of an automorphism of $G(R)$ (resp. $Lambda(R)$) and an
isomorphism of the ring $R$ onto $R'$ which is induced by an isometry
$Gamma arrow.r.bar Omega$ and by a ring isomorphism $K arrow.r.bar S$. Thus, all
isomorphisms are described in the conditions of Theorem
@th:l2005-sylow-isomorphisms and for the case of a commutative ring $K$.
