#import "../../main-defs.typ": *
#import "defs.typ": *

#heading(level: 3)[
  Pair Unipotent Intersections of Chevalley Groups
] <sec:l2005-sylow-intersections>

Sylow $p$-subgroups of a group are called _independent_ if the intersection of
any pair of Sylow $p$-subgroups is trivial. The intersection of any pair of
Sylow $p$-subgroups
#source(6, printed: 230)
is called a pair $p$-Sylow intersection of a group. In this section we set and
consider the following tasks (A) and (B):

(A) To describe for any prime $p$ finite groups in which the index of the
normalizer of every pair $p$-Sylow intersection is reciprocal to $p$.
<pass:l2005-sylow-task-a>

(B) To describe for any prime $p$ finite groups in which the intersection
$P inter Q$ of every pair of Sylow $p$-subgroups $P$ and $Q$ is normal in some
Sylow $p$-subgroup of $gp⟨P,Q⟩$.
<pass:l2005-sylow-task-b>

Tasks (A) and (B) at $p=2$ have been under active investigation since 1960s.
Suzuki [@bib:l2005-sylow-Suzuki1964] proved that a finite (non-Abelian) simple
group with independent Sylow 2-subgroups is a Chevalley group of Lie rank 1 over
a field of characteristic 2. By the middle of 1970s there had been completed a
classification of finite simple groups in which the intersection of every pair
of Sylow 2-subgroups $P$ and $Q$ is normal either in $P$ or in $Q$. Sylow
2-subgroups of such a group are either independent or Abelian, by
[@bib:l2005-sylow-Kabanov1976]. Also, Kabanov, Makhnev and Starostin raised
Question 5.14 in the Kourovka Notebook [@bib:l2005-sylow-Kourovka1992];
Questions 5.14, (c) and (d) coincide, respectively, with (A) and (B) at $p=2$
and are still open. Studying intersections of nilpotent subgroups of a finite
group [@bib:l2005-sylow-Zenkov1993], V. I. Zenkov advanced the following
hypothesis in 1990s: _all Lie type groups satisfying 5.14(c) (or (A) at $p=2$)
are of the Lie rank $<=2$._

In contrast to (B) the restriction on a group in (A) means that every pair
$p$-Sylow intersection is normal in some Sylow $p$-subgroup of the group. The
example of nonsolvable group $G$ with $O_p lr((G)) != 1$ in
[@bib:l2005-sylow-Kabanov1979, p. 108] shows that the tasks (A) and (B) do not
coincide.

Let $Phi(K)$ be a Chevalley group over a field $K$ associated with an
indecomposable root system $Phi$, and let $twisted(m, Phi)(K)$ $(m=2$ or $3)$ be
a Chevalley group over $K$ of the twisted type $twisted(m, Phi)$. T. Voitenko
and the author proved the following theorem in
[@bib:l2005-sylow-Levchuk2002Hypercentral, @bib:l2005-sylow-Voitenko2002] and
[@bib:l2005-sylow-Voitenko2001] which solves tasks (A) and (B) for Chevalley
groups at $p=char K$.

#theorem[
  Let $G(K)$ be a Chevalley group of a Lie type $G=Phi$ or $twisted(m, Phi)$
  over a finite field $K$. For $p=char K$ the index of the normalizer of every
  pair $p$-Sylow intersection of $G(K)$ is reciprocal to $p$ if and only if
  either $G=A_2$ or $p=2$ and $G=B_2$ or $p=3$ and $G=G_2$ or the Lie rank of
  $G(K)$ equals 1. The tasks (A) and (B) for $G(K)$ at $p=char K$ coincide.
] <th:l2005-sylow-finite-intersections>

Let $U G(K)$ be the unipotent subgroup of $G(K)$ which is generated by root
subgroups $X_r$ $(r in G^+)$ [@bib:l2005-sylow-Carter1972], and $U=U G(K)$.
Since $U$ is a Sylow $p$-subgroup of $G(K)$ at $p=char K>0$, so the first
statement of Theorem @th:l2005-sylow-finite-intersections is the corollary of
the following theorem.

#theorem[
  Let $G(K)$ be a Chevalley group of a Lie type $G=Phi$ or $twisted(m, Phi)$
  over a field $K$. Every pair unipotent intersection $U inter U^g$
  $(g in G(K))$ is conjugated in $G(K)$ to a normal subgroup of $U$ if and only
  if either $G=A_2$ or $char K=2$ and $G=B_2$ or $char K=3$ and $G=G_2$ or the
  Lie rank of $G(K)$ equals 1.
] <th:l2005-sylow-unipotent-intersections>

#source(7, printed: 231)
#sketch[
  The normalizer $B$ of the subgroup $U$ (a Borel subgroup) in $G(K)$ and the
  monomial subgroup $N$ form a $(B,N)$-pair of $G(K)$. In particular, we have
  the Bruhat decomposition $G(K)=B N B$. If $G(K)$ is a Chevalley group of Lie
  rank 1, then $U inter U^g=1$ for each $g in G(K) without B$.

  Set $p(Phi)=max lr({lr((s,s))/lr((r,r)) | r,s in Phi})$. If either $G=Phi$,
  $p(Phi)>1$ and $p(Phi)!=p$ or $G(K)$ is a twisted group of Lie rank $>1$, then
  there exists a root subgroup $X_q$ of $G(K)$ which isn’t conjugated to a
  normal subgroup of $U$. On the other hand, for every $q in G^+$ there is an
  element $n in N$ such that the intersection $U inter U^n$ is conjugated to the
  root subgroup $X_q$, [@bib:l2005-sylow-Levchuk2002Hypercentral].

  The description of intersections $U inter U^g$ and unions $U union U^g$ of
  $Phi(K)$ are received in [@bib:l2005-sylow-Voitenko2002]. Let
  $pi: N arrow.r.bar W$ be the natural homomorphism of the monomial subgroup $N$
  onto the Weyl group $W$ of the root system $Phi$. Recall that the Weyl group
  $W$ is generated by the reflections $omega_r$ for all $r in Phi$. Choose an
  element $n_r in N$ such that $pi(n_r)=omega_r$, as in
  [@bib:l2005-sylow-Carter1972]. Denoting by $Psi_omega^+$ (resp. $Psi_omega^-$)
  for $omega in W$, the set of all roots $r in Phi^+$ with $omega(r) in Phi^+$
  (resp. $omega(r) in Phi^-$) we suppose
  $
    U_omega^+ = gp(X_r | r in Psi_omega^+), quad
    U_omega^- = gp(X_r | r in Psi_omega^-).
  $
  <pass:l2005-sylow-weyl-subgroups>

  #lemma[
    Let $G(K)=Phi(K)$, $n in N$ and $pi(n)=omega$. Let $g in B n B$. Then
    $ gp(U, U^g)=gp(U, n_s lr((s in omega(Psi_omega^-)))) $
    <pass:l2005-sylow-generated-pair>
    and the intersection $U inter U^g$ is conjugated to $U_omega^+$. If the
    subgroup $U_omega^+$ is conjugated to a normal subgroup of $U$, then it is
    conjugated by an element $n' v$ such that
    $
      n' in N, quad v in (U_(omega')^-)^(n'), quad
      omega'=pi(n'), quad Psi_(omega')^- subset.eq Psi_omega^-.
    $
    <pass:l2005-sylow-normal-conjugator>
  ] <lem:l2005-sylow-bruhat-intersection>

  Now, if $Phi(K)$ is a Chevalley group of Lie rank $>2$, then we can choose a
  Coxeter element $omega$ such that the subgroup $U_omega^+$ isn’t conjugated in
  $Phi(K)$ to a normal subgroup of $U$, see
  [@bib:l2005-sylow-Levchuk2002Hypercentral] and
  [@bib:l2005-sylow-Voitenko2001]. By using Lemma
  @lem:l2005-sylow-bruhat-intersection we complete the proof of Theorems
  @th:l2005-sylow-unipotent-intersections and
  @th:l2005-sylow-finite-intersections for Chevalley groups of Lie rank $<=2$.
]
