import Mathlib.Algebra.Group.Basic

namespace LevchukPapers.L2017Quasifields

/- Lemma 8, algebraic step: an associative multiplicative loop generated by
one element is commutative. Here a monoid with every element a nonnegative
power is sufficient. For a finite cyclic group these hypotheses hold.
No assertion about nonassociative one-generated loops is made. -/
theorem cyclic_commutative {M : Type*} [Monoid M] (g : M)
    (generated : ∀ x : M, ∃ n : ℕ, x = g ^ n) (x y : M) :
    x * y = y * x := by
  obtain ⟨m, rfl⟩ := generated x
  obtain ⟨n, rfl⟩ := generated y
  rw [← pow_add, ← pow_add, Nat.add_comm]

/- The remaining distributive step in Lemma 8: right distributivity and
commutative multiplication imply left distributivity. The hypotheses are
the nearfield's existing right distributivity and the preceding conclusion,
extended to zero by its absorbing laws. -/
theorem left_distributivity {Q : Type*} [Add Q] [Mul Q]
    (commutative : ∀ x y : Q, x * y = y * x)
    (right_distributive : ∀ x y z : Q, (x + y) * z = x * z + y * z)
    (x y z : Q) : x * (y + z) = x * y + x * z := by
  rw [commutative x (y + z), right_distributive y z x,
    commutative y x, commutative z x]

end LevchukPapers.L2017Quasifields

#print axioms LevchukPapers.L2017Quasifields.cyclic_commutative
#print axioms LevchukPapers.L2017Quasifields.left_distributivity
