#import "../../main-defs.typ": *
#import "defs.typ": *
#import "diagrams/f4-roots.typ": f4-roots

=== The groups $U$ of types $F_4$, $twisted(2, F_4)$ and $twisted(2, E_6)$
<sec:l2012-extremal-en-f4-e6>

For the root system $Phi$ of type $F_4$, we need notation from
[@bib:l2012-extremal-en-Levchuk1990].

By [@bib:l2012-extremal-en-Bourbaki1968, Tables I–IV] and
[@bib:l2012-extremal-en-Levchuk1990], the positive roots of systems of types
$A_(n-1)$, $B_n$, $C_n$, $B C_n$, and $D_n$ may be written as

$ epsilon_i-m epsilon_j = p_(i,m j), quad 1 <= j <= i <= n, m = 0,1,-1. $

Set $T_(i v) = T(p_(i v))$ for exception the case
$T_(i 1) = T(p_(i,-1)) T(p_(i 1))$ for type $D_n$. If $U G(K)$ is a group of
classical type distinct from $A_n$ then, by [@bib:l2012-extremal-en-Levchuk1990,
Lemma @lem:l1990-chevalley-classical-root-centralizers (II)], the centralizer
$C(T_(i v))$ in $U G(K)$ coincides with $T_(1,-v-1)$, when either $i < n$ or
$G = twisted(2, A_m)$ or $2K = K$, $G = C_n$; in the remaining cases, we have
$C(T_(n v)) = T_(1,-v-1) T_(n,n-1)$.

Let $C_n^+ = {p_(i v) | 0 < |v| <= i <= n, v != i}$, as above. For type $B_n$,
we set $epsilon_i-m epsilon_j = q_(i,m j)$. By analogy with
[@bib:l2012-extremal-en-Levchuk1990], we represent the positive system $F_4^+$
as the union $C_4^+ union B_4^+$ with the given intersection

$
  B_4^+ inter C_4^+ = {q_(i 0),p_(i,-i) (1 <= i <= 4)}, quad
  B_4^+ = {q_(i j) | 0 <= |j| < i <= 4}.
$

Also, we use the following diagram from [@bib:l2012-extremal-en-Levchuk1990;
@pass:l1990-small-f4-root-representation[root diagram]]. (The roots are
accompanied by the notation $(a b c d)$ from
[@bib:l2012-extremal-en-Bourbaki1968, Table VIII].) The substitution
$overline(" "): Phi arrow.r Phi$ is defined by the simple rule:
$overline(p_(i j)) = q_(i j)$, $overline(q_(i j)) = p_(i j)$
($1 <= |j| < i <= 4$).

#figure(
  f4-roots(),
  caption: figure.caption(position: top)[#source(13, printed: 110)
    _The positive roots of the system $F_4$_],
  numbering: none,
  supplement: none,
)

Consider the “root elements” of $U twisted(2, F_4)(K)$, cf. Section
@sec:l2012-extremal-en-preliminaries. Let $r = q_(i j)$. Put
$R_(i j)(t) = x_r lr((t)) x_(overline(r)) lr((overline(t)))$ if either
$(i,j) = (2,-1)$, $(3,2)$, $(3,-2)$ or $i = 4$, $j in {-3,-2,-1,1,2}$. When
$(i,j) = (2,1)$, $(3,1)$, $(3,-1)$ or $(4,3)$, according to
[@bib:l2012-extremal-en-Carter1972],
${r,overline(r),r+overline(r),r+2overline(r)}$ is a class of type $B_2$ and we
set

$
  R_(i j)(t) = x_(overline(r)) lr((overline(t))) x_r lr((t))
  x_(r+overline(r)) lr((t overline(t))) quad (t in K).
$

By [@bib:l2012-extremal-en-Levchuk1990, § @sec:l1990-small-twisted-f4 (I);
@pass:l1990-small-twisted-f4-series[central series table]], $U_k$ in
$U twisted(2, F_4)(K)$ is generated by the elements $R_(i j)(t)$ corresponding
to the columns with number $>= k$ in the following table:

#source(14, printed: 111)
#table(
  columns: 8,
  align: center,
  [$R_21$], [$R_(2,-1)$], [$R_(3,-1)$], [$R_(3,-2)$], [], [], [], [],
  [$R_32$],
  [$R_31$],
  [$R_43$],
  [$R_42$],
  [$R_41$],
  [$R_(4,-1)$],
  [$R_(4,-2)$],
  [$R_(4,-3)$],
)

Recall that the system $twisted(2, Phi)$ of type $twisted(2, E_6)$ is associated
with a root system of type $F_4$. Choose the following subgroups in
$U F_4 lr((K))$ and $U twisted(2, E_6)(K)$ with $F = K$ and $F = K_sigma$,
respectively:

$
  T(q_43) U_6, quad T(p_(4,-1)) T(q_(3,-2)), quad
  T(p_(4,-1)) {x_(q_(3,-2)) lr((t)) x_(q_42) lr((t)) | t in F};
$ <eq:l2012-extremal-en-f4-e6-first-families>

$
  T(p_42) X_(q_43), quad T(p_42) X_(p_43), quad T(p_(3,-2)), quad
  T(p_(3,-2))^tau, quad T(q_(3,-2)) X_(p_41) X_(p_(3,-2));
$ <eq:l2012-extremal-en-f4-second-families>

$
  {x_(p_(3,-2)) lr((t)) x_(p_42) lr((t)) | t in K} S, quad
  S = T(q_43) T(p_41) "or" T(q_(3,-2)) X_(p_41);
$ <eq:l2012-extremal-en-f4-first-linked>

$
  {x_(q_(3,-2)) lr((t)) x_(q_42) lr((t)) | t in K} T(p_(4,-1)) X_(p_41) S,
  quad S = X_(p_43) X_(p_42) "or" X_(p_(3,-2));
$ <eq:l2012-extremal-en-f4-second-linked>

$ 〈 x_(p_43) lr((1)) x_(q_43) lr((d)) 〉 T(p_42) quad (d in K^*); $
<eq:l2012-extremal-en-f4-binary-pair>

$
  [〈 x_(p_(3,-2)) lr((t)) x_(p_42) lr((t)) | t in K 〉 times
    〈 x_(q_(3,-2)) lr((t)) x_(q_42) lr((d t)) | t in K 〉]
  T(p_(4,-1)) X_(p_41).
$ <eq:l2012-extremal-en-f4-linked-product>

The main theorem of this section is the following one.

#theorem[Up to conjugation by a diagonal automorphism, the maximal abelian
  normal subgroups in $U F_4 lr((K))$ and $U twisted(2, E_6)(K)$ are exhausted
  by the subgroups @eq:l2012-extremal-en-f4-e6-first-families for $2K = K$; when
  $2K = 0$, they are exhausted by the subgroups
  @eq:l2012-extremal-en-f4-second-families–@eq:l2012-extremal-en-f4-linked-product
  and, respectively, by @eq:l2012-extremal-en-f4-e6-first-families,
  $(T(p_(3,-2)) inter E_6 lr((K_sigma))) U_7$, and

  $
    {x_(p_41) lr((t)) x_(p_(4,-1)) lr((f t)) | t in F}
    x_(p_(4,-1)) lr((K_sigma)) T(q_43) U_7 quad (f in K without K_sigma).
  $ <eq:l2012-extremal-en-twisted-e6-nonstandard>

  In $U twisted(2, F_4)(K)$, they are exhausted by the subgroups

  $
    〈 R_43 lr((1)) 〉 R_42 lr((K)) U_5, quad
    {R_(3,-2)(t) R_42 lr((c t)) | t in K} U_5 quad (c in K).
  $ <eq:l2012-extremal-en-ree-maximal-abelian>
] <th:l2012-extremal-en-f4-e6-maximal>

#proof(qed: true)[Note that if the roots $r,s$, and $r+s$ from $F_4^+$ do not
  lie simultaneously in one of the subsystems $B_4^+$ or $C_4^+$ then they lie
  in one of the following subsystems of type $B_2^+$:

  $
    {p_(3,-v),q_(3,2v),p_(4,2v),q_(4v)}, quad
    {p_(3,2v),q_(3,-v),p_(4v),q_(4,2v)},
  $
  $
    {p_(3v),q_(3v),p_(4,2v),q_(4,2v)}, quad
    {p_(3,2v),q_(3,-2v),p_(4,-v),q_(4v)}, quad |v| = 1.
  $

  Also we have $U twisted(2, E_6)(K) = 〈 x_(p_(i v)) lr((K)),
  x_(q_(i v)) lr((K_sigma)) (1 <= |v| < i <= 4) 〉$.

  Consider an arbitrary maximal abelian normal subgroup $M$ in $U$ of type $F_4$
  and $twisted(2, E_6)$. When $p_41$-projection of $M$ is zero, we get

  $
    T(q_(3,-2)) T(q_43) supset M = C(M)
    supset C(T(q_(3,-2)) T(q_43)) supset.eq T(p_(4,-1)).
  $

  Let $F = K$ or $F = K_sigma$ as in the theorem. Since
  $X_(q_42) X_(q_(3,-2)) X_(q_(4,-3)) tilde.eq UT(3, K)$ by Lemma
  @lem:l2012-extremal-en-an-maximal-abelian, we obtain the subgroups
  @eq:l2012-extremal-en-f4-e6-first-families.

  Further, we may assume that the $p_41$-projection in $M$ is non-zero. Then the
  $p_41$-projection $P$ of the intersection $M inter U_5$ is also non-zero
  because of $M lt.closed.eq U$. Up to conjugation of $M$ by a diagonal
  automorphism, we have $1 in P$. Commuting $M inter U_5$ firstly with
  $T(p_(1,-1))$ and then with $U$, we find the subgroup
  $x_(p_(4,-1)) lr((F P)) T(p_(4,-2))$ in $M$ (see the diagram). Since the
  centralizer of this subgroup coincides with $T(p_(2,-1))$, we obtain
  $M subset.eq T(p_(2,-1))$ and $2K = 0$, because of the equality
  $[x_(p_(4,-1)) lr((F P)),M inter U_5] = 1$. Thus, if $2K = K$ then $M$ is one
  of the subgroups @eq:l2012-extremal-en-f4-e6-first-families.

  Note that
  $U twisted(2, E_6)(K) inter E_6 lr((K_sigma)) tilde.eq U F_4 lr((K_sigma))$.
  For type $twisted(2, E_6)$ we also infer that the $K_sigma$-module $F P$ is
  one-dimensional, and $1 in P subset.eq K_sigma$. The $p_(4,-1)$-projection of
  the subgroup $M inter (T(p_(4,-1)) T(q_43))$ is #source(15, printed: 112)
  contained in $K_sigma$, since $M$ is an abelian subgroup. Taking into account
  the normality of $M$, we obtain

  $
    T(p_(3,-2)) supset.eq M supset.eq C(T(p_(3,-2))), quad
    M inter T(p_41) = alpha(P) x_(p_(4,-1)) lr((K_sigma)) T(q_42) U_7
  $

  where $alpha(t) = x_(p_41) lr((t)) x_(p_(4,-1)) lr((tilde(t)))$ for a suitable
  mapping $tilde(" "): P arrow.r K$. Set $f = tilde(1)$ and
  $t_0 = tilde(t)+f t$. Using $[alpha(t),alpha(1)] = 1$ we find

  $
    tilde(t)+overline(tilde(t))+f overline(t)+overline(f)t = 0, quad
    t_0 = overline(t_0), quad tilde(t) = t_0+f t in f t+K_sigma quad (t in P).
  $

  Clearly, $(T(p_(3,-2)) inter E_6 lr((K_sigma))) U_7$ is an abelian normal
  subgroup. Consequently, if the $p_(3,-2)$-projection in $M$ is zero then we
  have $f in K without K_sigma$. Therefore, $P = K_sigma$, and $M$ is the second
  subgroup in @eq:l2012-extremal-en-twisted-e6-nonstandard. Similarly

  $
    M = beta(P) x_(p_41) lr((K_sigma)) x_(p_(4,-1)) lr((K_sigma)) T(q_42) U_7,
    quad beta(t) = x_(p_(3,-2)) lr((t)) x_(p_(4,-1)) lr((f t))
  $

  in the case when $M$ has the corner $p_(3,-2)$. But in the latter case the
  condition $[beta(t),beta(1)] = 1$ gives $f overline(t)+overline(f)t = 0$
  ($t in P$). Therefore, $f in K_sigma$, and $M$ coincides with the subgroup
  $(T(p_(3,-2)) inter E_6 lr((K_sigma))) U_7$.

  In $U F_4 lr((K))$, the subgroup $X_(p_41) T(p_(4,-1))$ centralizes $U_5$.
  Using the normality of $M$, we also find the corner $p_41$ of the intersection
  $M inter T(p_41)$ for the case $M subset.not U_5$. Therefore, the
  $p_(2,-1)$-projection and $p_(3,-1)$-projection in $M$ are zero, i.e.,
  $M subset.eq T(p_43) T(q_(2,-1))$. If either the $q_(2,-1)$-projection or the
  $q_(3,-1)$-projection in $M$ is non-zero then $M inter T(q_41)$ has the corner
  $q_41$, and $M inter T(q_41)$ does not centralize $M$, a contradiction. It
  follows that

  $
    T(p_(4,-1)) X_(p_41) subset.eq M subset.eq
    X_(p_43) T(p_42) T(p_(3,-2)) T(q_(3,-2)).
  $

  Since $1 = [[M,T(q_32)],M]$, the $q_(3,-2)$-projection should be zero if the
  $q_43$-projection in $M$ is non-zero. Similarly, the $p_(3,-2)$-projection in
  $M$ is zero if the $p_43$-projection is non-zero. For the center $Z$ of $U$,
  the subgroup $B = X_(p_43) X_(q_43) Z$ has a direct complement $D$ in
  $X_(p_43) X_(q_43) T(p_42)$, and

  $
    Z times D = T(p_42) subset.eq M subset.eq B times D, quad
    M = (M inter B) times D, quad B tilde.eq U B_2 lr((K)).
  $

  If $p_43$ and $q_43$ are corners in $M$ then they are connected. By
  [@bib:l2012-extremal-en-Levchuk2008, Theorem
  @th:l2008-normal-classical-maximal], the projections on these corners have
  order 2. Thus, $M inter B$ is a maximal abelian normal subgroup in $B$, and
  $M$ is the subgroup @eq:l2012-extremal-en-f4-binary-pair.

  The other cases for the non-zero $p_43$-projection or $q_43$-projection give
  one of the subgroups $T(p_(3,-2))$, $T(q_(3,-2)) X_(p_43) X_(p_42) X_(p_41)$
  (i.e., $T(p_(3,-2))^tau$, when $K$ is perfect and hence there exists a graph
  automorphism), $T(p_42) X_(q_43)$, $T(p_42) X_(p_43)$ and the first of
  subgroups in @eq:l2012-extremal-en-f4-first-linked and
  @eq:l2012-extremal-en-f4-second-linked. If $M subset.eq T(p_42) T(p_(3,-2))$
  then $M$ coincides with one of $T(p_(3,-2))$, $T(p_42) T(q_43)$ or
  @eq:l2012-extremal-en-f4-first-linked.

  Considering the subgroups $M$ with the corners $p_(3,-2)$ and $q_(3,-2)$ we
  get the subgroups $T(q_(3,-2)) X_(p_41) X_(p_(3,-2))$,
  @eq:l2012-extremal-en-f4-linked-product and the remaining subgroups in
  @eq:l2012-extremal-en-f4-first-linked and
  @eq:l2012-extremal-en-f4-second-linked.

  By Lemma @lem:l2012-extremal-en-hypercenters-incident every normal subgroup in
  $U twisted(2, F_4)(K)$ is incident with the abelian normal subgroup
  $Z_4 = U_5$. Therefore,

  $ Z_4 = U_5 subset.eq M subset.eq C(Z_4) = R_43 lr((K)) Z_5. $

  The defining relations for the twisted group $U twisted(2, F_4)(K)$ in terms
  of generators $R_(i v)(t)$ ($t in K$) were described in
  [@bib:l2012-extremal-en-Levchuk1990, Lemma
  @lem:l1990-small-twisted-f4-relations]. In particular,

  $
    [R_43 lr((a)),R_(3v)(b)] = R_(4v)(a b) quad (|v| <= 2), quad
    [R_(4v)(a),R_(3,-v)(b)] = R_(4,-3)(a b) quad (v = plus.minus 2).
  $

  #source(16, printed: 113) Also, we obtain the isomorphic embeddings
  $t arrow.r R_(i v)(t)$ of the additive group $K^+$ into $R_(i v)(K)$ for all
  $(i,v)$ such that $(i,v) in.not {(2,1),(4,3),(3,1),(3,-1)}$. For the remaining
  cases, using the representation @eq:l2012-extremal-en-suzuki-multiplication,
  we get the following isomorphic embeddings of the group $U twisted(2, B_2)(K)$
  into $U twisted(2, F_4)(K)$:

  $
    (t,u) arrow.r R_(i v)(t) R_(i,-v)(u) quad ((i,v) = (2,1),(4,3)),
    quad (t,u) arrow.r R_(3v)(t) R_(4,2v)(u) quad (|v| = 1).
  $

  The subgroup $T(R_42)$ centralizes $R_43 lr((K)) T(R_42)$. For
  $M subset.eq Z_5$, the isomorphism

  $ R_42 lr((K)) R_(3,-2)(K) R_(4,-3)(K) tilde.eq UT(3, K) $

  and Lemma @lem:l2012-extremal-en-an-maximal-abelian give the equality
  $M = {R_(3,-2)(t) R_42 lr((t d)) | t in K} Z_4$ for a fixed $d in K$. Let
  $M_(i v)$ be an $R_(i v)$-projection of $M$. Since

  $
    1 = [M,[M,R_32 lr((1))]] = [M,R_42 lr((M_43))]
    = R_(4,-3)(M_(3,-2) M_43),
  $

  we get $M_(3,-2) M_43 = 0$. If $M_(3,-2) = 0$ and hence $M subset.eq T(R_43)$
  then the description of the abelian normal subgroups in $U twisted(2, B_2)(K)$
  implies $M = T(R_42) 〈 alpha 〉$ for an arbitrary
  $alpha in T(R_43) without T(R_42)$. Thus, Theorem
  @th:l2012-extremal-en-f4-e6-maximal is proved.
]

=== Some large $cal(P)$-subgroups <sec:l2012-extremal-en-large-subgroups>

In this section, we consider some application to the problem (1.6) from
[@bib:l2012-extremal-en-Kondratyev1986] of description of the large abelian and
normal large abelian subgroups in a finite group $U$ of exceptional Lie type.
Under notation of Theorems @th:l2012-extremal-en-rank-two-maximal,
@th:l2012-extremal-en-abelian-normal and @th:l2012-extremal-en-f4-e6-maximal, as
a consequence, we obtain

#theorem[Let $U = U G(K)$ for a finite field $K$. Then the large normal abelian
  subgroups in $U$ are the following:

  #enum(
    numbering: "(a)",
    [$T(alpha_1+2alpha_2+2alpha_3+3alpha_4+2alpha_5+alpha_6)$ in
      $U E_8 lr((K))$, $T(alpha_1)$ and $T(alpha_6)$ in $U E_6 lr((K))$,
      $T(alpha_7)$ in $U E_7 lr((K))$;],
    [$〈 gamma 〉 U_2$ ($gamma in U without U_2$) for $G = twisted(2, B_2)$,
      $〈 R_43 lr((c)) 〉 R_42 lr((K)) U_5$ ($c != 0$) for
      $G = twisted(2, F_4)$;],
    [$T(q_43) U_6$ for $2K = K$, $G = F_4$ or $twisted(2, E_6)$;],
    [$U_3$ in $U G_2 lr((K))$ for $6K = K$ and in $U twisted(3, D_4)(K)$ for
      $2K = K$;],
    [$U_2$ for $3K = 0$, $G = G_2$ or $twisted(2, G_2)$,
      $〈 alpha 〉 times 〈 beta_1 lr((1)) 〉$ in $U G_2 lr((2))$, and $U_3$ and
      $beta_c lr((K)) U_4$ ($c in K$) in $U G_2 lr((K))$ for $2K = 0$,
      $|K| > 2$;],
    [when $2K = 0$, up to conjugation by a diagonal automorphism,

      $
        (T(p_(3,-2)) inter E_6 lr((K_sigma))) U_7
        quad "in" U twisted(2, E_6)(K),
      $
      <eq:l2012-extremal-en-twisted-e6-large>

      $beta_c lr((K_sigma)) x_(2a+b) lr((K^(1+sigma))) dot U_4$ ($c in K$) and
      $U_3$ in $U twisted(3, D_4)(K)$ for $|K_sigma| > 2$,

      $
        〈 alpha 〉 times 〈 beta_1 lr((1)) 〉 times x_(2a+b) lr((K^(1+sigma)))
        quad "in" U twisted(3, D_4)(8),
      $
      <eq:l2012-extremal-en-triality-binary-large>

      $
        T(p_(3,-2))^tau, quad X_(p_43) T(p_42), quad
        X_(p_43) X_(p_42) X_(p_41)
        {x_(q_(3,-2)) lr((t)) x_(q_42) lr((t)) | t in K} T(p_(4,-1)),
      $
      $
        T(p_(3,-2)), quad X_(q_43) T(p_42), quad
        {x_(p_(3,-2)) lr((t)) x_(p_42) lr((t)) | t in K} X_(q_43) T(p_41)
      $

      and, in addition, $〈 x_(p_43) lr((1)) x_(q_43) lr((1)) 〉 T(p_42)$ for
      $|K| = 2$ in $U F_4 lr((K))$.
    ],
  )] <th:l2012-extremal-en-large-normal-abelian>

Now we show that the large normal abelian subgroups in $U$ are large abelian
subgroups.

In general, a large normal $cal(P)$-subgroup of a finite group is not a normal
large $cal(P)$-subgroup. In fact, the center of $SL(3, GF(2))$ is a large normal
cyclic subgroup but this group has no a normal large cyclic subgroup.

We have to prove the inequality $a(U) <= b(U)$, where $a(U)$ (and $b(U)$) is the
largest order of all (respectively, normal) abelian subgroups in $U$. This fact
is well known for the groups of Lie type of #source(17, printed: 114) rank 1 or
of classical type, [@bib:l2012-extremal-en-Kondratyev1986] and
[@bib:l2012-extremal-en-Levchuk2009]. Theorem
@th:l2012-extremal-en-large-normal-abelian explicitly gives the number $b(U)$
for every $U$ of exceptional Lie type.

Further, we use the notion of a _regular ordering_ of roots, which agrees with
the height function on roots [@bib:l2012-extremal-en-Carter1972, Lemma 5.3.1].
Taking into account the representation $zeta$ in Section
@sec:l2012-extremal-en-preliminaries we may use similar ordering for the twisted
system.

Now, in the canonical decomposition of every $alpha in U = U G(K)$, the first
non-unit cofactor corresponds to the _first corner_ in $alpha$. Evidently, if
$M subset.eq U$ then for every corner $r$ in $M$ the _r-projection_
$cal(F)_M lr((r))$ of $M$ does not depend on the choice of ordering in $G$. The
following lemma is immediate.

#lemma[Let $M$ be a subgroup in $U G(K)$, and let $cal(L)_1 lr((M))$ be the set
  of first corners of all elements in $M$. Then
  $|M| <= product_(r in cal(L)_1 lr((M))) |cal(F)_M lr((r))|$.#ed-note[
    For the full projections defined above, the printed equality must be
    replaced by an inequality: in $UT(3, GF(4))$, the cyclic subgroup generated
    by $mat(1, 1, a; 0, 1, 1; 0, 0, 1)$, with $a in.not GF(2)$, has order $4$,
    whereas the product of its first-corner projection sizes is $8$. The
    inequality follows from injectivity of the restricted coordinate map: the
    first coordinate where two elements differ is the first corner of their
    quotient, since earlier coordinates cancel in the regular ordering of
    [@bib:l2012-extremal-en-Carter1972, Lemma 5.3.1 and Theorem 5.3.3].]]
<lem:l2012-extremal-en-first-corner-order>

By Lemma @lem:l2012-extremal-en-root-commutator, a subgroup $X_Psi$ in
$U Phi(K)$ (with $p(Phi)! K = K$) is abelian if and only if $Psi$ is an abelian
subset in $Phi^+$, and hence ${e_r | r in Psi}$ is a basis for an abelian
subalgebra in $N Phi(K)$. According to E. P. Vdovin
[@bib:l2012-extremal-en-Vdovin2001], a subset $Psi$ of $Phi^+$ is said to be
_p-abelian_ if in the algebra $N Phi(K)$ over a field $K$ of characteristic $p$
we have $e_r ast e_s = 0$ for all $r,s in Psi$. For $p(Phi)! K = K$, this gives
$r+s in.not Phi$, i.e., $Psi$ is an abelian subset. Clearly, every abelian
subset in $Phi^+$ is always p-abelian for every prime $p$. The largest order of
abelian and p-abelian subsets in $Phi^+$ is denoted by $a(Phi)$ and $a(Phi,p)$,
respectively.

An application of the first corner of the elements in $U$ and Lemma
@lem:l2012-extremal-en-first-corner-order give a simplified proof of the
following statement (see [@bib:l2012-extremal-en-Vdovin2001, § 2]).

#lemma[Let $A$ be an abelian subgroup in $U Phi(K)$. Then $cal(L)_1 lr((A))$ is
  a p-abelian subset in $Phi^+$, and $|A| <= |K|^(a(Phi,p))$.]
<lem:l2012-extremal-en-first-corner-p-abelian>

A. I. Mal’tsev [@bib:l2012-extremal-en-Malcev1945] described the abelian subsets
of largest order in $Phi^+$. His description shows that there exists a normal
abelian subset $Psi$ of order $a(Phi)$. For $U Phi(K)$ with $p(Phi)! K = K$,
$X_Psi$ is a normal large abelian subgroup of order $|K|^(a(Phi))$, and hence
$a(U) = b(U) = |K|^(a(Phi))$.

Analogously, if $p(Phi) = char K = p >= 2$ then there exists a normal p-abelian
subset $Psi$ in $Phi^+$ of order $a(Phi,p)$ and $a(U) = b(U) = |K|^(a(Phi,p))$.
For type $C_n$, this result follows from the description in
[@bib:l2012-extremal-en-Barry1982]. By E. P. Vdovin
[@bib:l2012-extremal-en-Vdovin2001], for types $G_2$ and $F_4$ we get,
respectively,

$
  X_Psi = U_2, quad a(Phi,3) = 4, quad "and" quad
  X_Psi = T(p_(3,-2)), quad a(Phi,2) = 11.
$

Also, if $Phi$ is of type $G_2$ then ${a,a+b,3a+b,3a+2b}$ is a unique 2-abelian
subset in $Phi^+$ of order $> 3$ and $a(Phi,2) = 4$. Every abelian subgroup $A$
in $U G_2 lr((K))$ ($2K = 0$) either is of order $|A| <= |U_3| = |K|^3$ or

$
  A = 〈 x_a lr((t)) x_(2a+b) lr((s t)),
  x_(a+b) lr((s)) x_(2a+b) lr((s t)) 〉 U_4
  quad (s,t in K^*), quad |A| = 4 dot |K|^2.
$ <eq:l2012-extremal-en-g2-binary-large>

The subgroup @eq:l2012-extremal-en-g2-binary-large is of order $>= |K|^3$ if and
only if $|K| = 2$ or 4. If this inequality is strict then $|K| = 2$ and
@eq:l2012-extremal-en-g2-binary-large is a normal subgroup. Therefore,
$a(U) = b(U)$ holds for all $U Phi(K)$.

The same holds for the groups $U$ of type $twisted(2, F_4)$, $twisted(2, B_2)$,
and $twisted(2, G_2)$, since a corner projection of every their root set $X_r$
coincides with $K$.

For the remaining groups $U twisted(m, Phi)(K)$ of type $twisted(3, D_4)$ and
$twisted(2, E_6)$, E. P. Vdovin [@bib:l2012-extremal-en-Vdovin2001] suggested to
use the description from [@bib:l2012-extremal-en-Malcev1945] of abelian subsets
in $Phi$ of type $D_4$ and $E_6$. Simplifying this approach, we use a
description of p-abelian subsets of the associated root systems $zeta(Phi)$.

Consider $U$ of type $twisted(2, E_6)$ in detail. Then $zeta(Phi)$ is of type
$F_4$, and $U inter U E_6 lr((K_sigma)) tilde.eq U F_4 lr((K_sigma))$. Let $A$
be an arbitrary large abelian subgroup in $U$. By Lemma
@lem:l2012-extremal-en-twisted-projections, if $|cal(F)_A lr((r))| > |K_sigma|$
for some root $r in cal(L)_1 lr((A))$ then $r+s in.not cal(L)_1 lr((A))$ for all
$s in cal(L)_1 lr((A))$. For $2K = K$, according to Lemma
@lem:l2012-extremal-en-first-corner-p-abelian, $cal(L)_1 lr((A))$ is an abelian
subset in $zeta(Phi)^+$ of order $<= a(zeta(Phi)) = 9$. By
[@bib:l2012-extremal-en-Malcev1945], $cal(L)_1 lr((A))$ doesn’t contain more
than six classes of every fixed type, and also it doesn’t contain more than
three classes of type $A_1 times A_1$, i.e., $cal(L)_1 lr((A))$ possesses no the
roots $p_(i v)$ with $1 <= |v| < i$ in the diagram of Section
@sec:l2012-extremal-en-f4-e6. By Lemma
@lem:l2012-extremal-en-first-corner-order, we obtain

$ a(U) = |A| <= |K_sigma|^6 dot |K|^3 = |K_sigma|^12 = b(U). $

#source(18, printed: 115) If $2K = 0$ then $cal(L)_1 lr((A))$ is a 2-abelian
subset, and $|cal(L)_1 lr((A))| <= a(zeta(Phi),2) = 11$. Also, the description
from [@bib:l2012-extremal-en-Vdovin2001] and Lemma
@lem:l2012-extremal-en-twisted-projections show that the number of all
$r in cal(L)_1 lr((A))$ with $|cal(F)_A lr((r))| > |K_sigma|$ is less than 3.
Since the number $b(U)$ coincides with the order $|K_sigma|^13$ of the abelian
normal subgroup @eq:l2012-extremal-en-twisted-e6-large, we get

$ a(U) = |A| <= |K|^2 dot |K_sigma|^9 = |K_sigma|^13 = b(U). $

Thus, $a(U) = b(U)$ holds for all $U$. We arrived at the following

#theorem[Let $U = U G(K)$ for a finite field $K$. Then a subgroup in $U$ is a
  large normal abelian subgroup if and only if it is a normal large abelian
  subgroup.] <th:l2012-extremal-en-normal-large-order>

#remark(numbered: false)[For the groups $U G_2 lr((2))$, $U twisted(3, D_4)(8)$,
  and $U twisted(2, E_6)(K)$ with $2K = 0$, Theorem
  @th:l2012-extremal-en-normal-large-order allows us to refine the values
  $a(U)$, which by [@bib:l2012-extremal-en-Vdovin2001] might be $2^3$, $2^5$ or
  $|K_sigma|^12$, respectively. The subgroups
  @eq:l2012-extremal-en-g2-binary-large,
  @eq:l2012-extremal-en-triality-binary-large and
  @eq:l2012-extremal-en-twisted-e6-large of orders $2^4$, $2^6$ and
  $|K_sigma|^13$, respectively, were omitted in
  [@bib:l2012-extremal-en-Vdovin2001].] <rem:l2012-extremal-en-orders>

Now it is easy to show that if all normal large abelian subgroups in a finite
group $U$ are extremal then all large abelian subgroups in $U$ are normal. We
note that for every finite group $G$ of Lie type the authors have the proof of
the following theorem. (See also [@bib:l2012-extremal-en-Levchuk2009,
Theorem~@th:l2009-finitary-large-abelian-conjugacy] for the classical types
[@bib:l2012-extremal-en-Suleimanova2010], and the question in
[@bib:l2012-extremal-en-Gupta2008, § 1].)

#theorem[In every finite group $U$, either each large abelian subgroup is
  $G$-conjugate to a normal subgroup in $U$ or $G$ is of type $G_2$,
  $twisted(3, D_4)$, $F_4$ or $twisted(2, E_6)$.]
<th:l2012-extremal-en-classical-conjugacy>
