#import "../../collection.typ": paper-abstract, paper-keywords
#import "../../main-defs.typ": *
#import "../../statements.typ": *
#import "defs.typ": *
#import "diagrams/roots.typ": bc-one

=== Preliminary notes <sec:l2022-graph-preliminary>

The semisimple complex Lie algebras are classified in Cartan–Killing theory
parallel with the root systems of a Euclidean space $V$.

For any indecomposable root system $Phi$ in $V$ and for any field $K$ we have
the corresponding Chevalley algebra $L_Phi lr((K))$. The elements $e_r$
($r in Phi$) and the basis of the suitable Cartan subalgebra $H$ with the
condition $H e_r subset.eq K e_r$ [@bib:l2022-graph-Carter1972, Sec. 4.2] form a
basis of $L_Phi lr((K))$. The elements $e_r$ ($r in Phi^+$) for the positive
root system $Phi^+$ in $Phi$ form a basis of the niltriangular subalgebra
$N Phi(K)$.

The system of fundamental roots $Pi$, which is a basis in $Phi^+$, is unique.
The Cartan numbers $A_(r s) = frac(2 lr((r,s)), lr((r,r)))$ ($r,s in Pi$) are
integers; they form the Cartan matrix. We call a graph with nodes, one
associated with each fundamental root, such that the $i$th node is joined to the
$j$th node by a bond of strength $A_(r s) A_(s r)$, a Coxeter graph of the root
system $Phi$, by the terminology of J.-P. Serre [@bib:l2022-graph-Serre1966]
(see also the remark in [@bib:l2022-graph-Levchuk2012, Sec. 1]). If we mark each
node by a number $(r,r)$ we obtain the Dynkin diagram.

The classification of simple complex Lie algebras, to within isomorphism, is
connected with the classification of indecomposable root systems, to within
equivalence. There exist 9 series of reduced root systems
[@bib:l2022-graph-Bourbaki1968, Tables I–IX] — the classical types $A_n$, $B_n$,
$C_n$, $D_n$, and the exceptional types $G_2$, $F_4$, $E_6$, $E_7$ and $E_8$.

_Co-roots_ $h_r = frac(2r, lr((r,r)))$ ($r in Phi$) give also a
_dual root system_
$Phi^*$ with base $Pi^*$ and, also, the systems $Phi$, $(Phi^*)^*$ are
equivalent. Note that the systems of type $B_n$, $C_n$ are dual.

On the other hand, all indecomposable unreduced root systems, to within
equivalence, are exhausted by the systems of type $B C_n$. For $n = 1$ we have

#source(3, printed: 680)
#align(center, bc-one())

#align(center)[Type $B C_1$.]

In 1982 in [@bib:l2022-graph-Levchuk1982] homomorphisms of root systems were
introduced. Denote by $L_0 lr((Phi))$ the additive subgroup in $V$ generated by
the roots of $Phi$ (the lattice of roots).

#definition[We call a surjective mapping $Phi -> Phi'$ a homomorphism of $Phi$
  onto $Phi'$ if this mapping may be extended to a homomorphism of the group
  $L_0 lr((Phi))$ onto the group $L_0 lr((Phi'))$.
] <def:l2022-graph-root-homomorphism>

We consider homomorphisms of the root system $Phi$, which are not isomorphisms.
Such homomorphisms exist only if the Coxeter graph of the system $Phi$ has a
non-trivial symmetry and all roots in $Phi$ have an equal length
[@bib:l2022-graph-Levchuk1982].

The symmetry may be linearly extended to a permutation $overline(" ")$ on the
root system $Phi$. Under the same restrictions on $Phi$ the Chevalley algebra
$L_Phi lr((K))$ has a graph automorphism

$ theta: e_r -> e_(overline(r)) quad (r in Pi), $

according to the proof of Proposition 12.2.3 in [@bib:l2022-graph-Carter1972].
By [@bib:l2022-graph-Levchuk1990], the same conclusion is true for the induced
automorphism of subalgebra $N Phi(K)$.

By [@bib:l2022-graph-Levchuk2018] and [@bib:l2022-graph-Levchuk2020;
@def:l2020-nonassoc-exact-envelope[definition]], an arbitrary (not necessarily
associative) algebra $A$ is said to be an exact enveloping algebra for a Lie
algebra $L$ if $L$ is isomorphic to the associated algebra $A^((-))$. Both
algebras $L$ and $A$ may be defined by structure constants in the same basis, in
contrast to the universal associative enveloping algebra.

The existence and the structure of exact enveloping algebras for the Lie
algebras $N Phi(K)$ were considered in [@bib:l2022-graph-Levchuk2018].
Centralizers of graph automorphisms of Lie algebras $N Phi(K)$ play an important
role in the investigation of uniqueness (problem of I. P. Shestakov, 2017).

For the classical types on this way special exact enveloping algebras

$
  R A_(n-1) lr((K)) = NT(n, K), quad R B_n lr((K)), quad R C_n lr((K)), quad
  R D_n lr((K))
$

were discovered (the associative algebra $NT(n, K)$ of all (lower) niltriangular
matrices of degree $n$ over $K$ exists only for the type $A_(n-1)$).

The problem on non-trivial homomorphisms of root systems and embeddings of the
centralizers is studied for $Phi$ of type $D_n$ and $theta^2 = 1$
[@bib:l2022-graph-Egorychev2023]. This problem was represented at the student
conference in SFU (2022) by students of IMFI (M. V. Dektyarev, D. R.
Khismatulin, A. D. Pakhomova and I. V. Salmina).
