#import "../../main-defs.typ": *
#import "defs.typ": *



#import "../../collection.typ": paper-abstract, paper-keywords

#heading(
  level: 3,
  numbering: none,
)[Introduction] <sec:l2013-thompson-introduction>

It is well-known that similarly to A. I. Mal’cev’s schema from
[@bib:l2013-thompson-Malcev1945] the problem of enumeration of the large abelian
subgroups of a Lie-type group $G$ over a finite field is reduced to the same
problem for the unipotent radical $U$ of the Borel subgroup of $G$. The problem
has been under active investigation since 1970’s. For classical types the sets
$Ac(U)$ of large abelian subgroups of $U$ were found by the middle 1980’s, as
well as the subsets $Ac_N lr((U))$ of normal subgroups and $Ac_e lr((U))$ of
elementary abelian subgroups and, also, the Thompson subgroups
$ J(U) = ⟨ A | A in Ac(U) ⟩, quad J_e lr((U)) = ⟨ A | A in Ac_e lr((U)) ⟩. $

In 1986 A. S. Kondratiev singled out in his survey
[@bib:l2013-thompson-Kondratyev1986, (1.6)] the following problem:

*Problem (A):* _Describe the sets $Ac(U)$, $Ac_N lr((U))$, $Ac_e lr((U))$ and
the Thompson subgroups $J(U)$ and $J_e lr((U))$ for the remaining cases of
$G$._ <pass:l2013-thompson-problem-a>

The present paper summarizes the investigations of this problem, carried out by
E. P. Vdovin [@bib:l2013-thompson-Vdovin2001Maximal,
@bib:l2013-thompson-Vdovin2001], the authors
[@bib:l2013-thompson-Levchuk2008–@bib:l2013-thompson-Levchuk2012Extremal] and G.
S. Suleimanova
[@bib:l2013-thompson-Suleimanova2010–@bib:l2013-thompson-Suleimanova2012].
=== Preliminaries <sec:l2013-thompson-preliminaries>

A Chevalley group $Phi(K)$ over a field $K$, associated with a root system
$Phi$, is generated by the root subgroups $X_r = x_r lr((K))$, $r in Phi$; the
root subgroups taken for the positive roots $r in Phi^+$ generate the unipotent
subgroup $U = U Phi(K)$. A twisted group $twisted(m, Phi)(K)$ is defined as the
centralizer in $Phi(K)$ of a twisting automorphism $theta$ of order $m = 2$ or
$3$. For a twisted group we #source(2, printed: 64) have
$U = U twisted(m, Phi)(K) := twisted(m, Phi)(K) inter U Phi(K)$. Besides,
$theta$ is a superposition of a graph automorphism $tau in Aut Phi(K)$ and a
field automorphism $sigma: t arrow.r overline(t)$ ($t in K$), and for the only
continuation $overline(std.hide(r))$ on $Phi$ of a symmetry of a Coxeter graph
of order $m$ we have $theta(X_r) = tau(X_r) = X_(overline(r))$ ($r in Phi$)
[@bib:l2013-thompson-Carter1972, @bib:l2013-thompson-Steinberg1967].

Given a group-theoretic property $P$, every $P$-subgroup of the highest order is
called a _large $P$-subgroup_. Developing A. I. Mal’tsev’s approach
[@bib:l2013-thompson-Malcev1945], E. P. Vdovin has mainly calculated
[@bib:l2013-thompson-Vdovin2001, Concluding table] the orders $a(U)$ of large
abelian subgroups of finite groups $U = U G(K)$ ($G = Phi$ or
$G = twisted(m, Phi)$) and those of Thompson subgroups.

Having described the maximal normal abelian subgroups of $U$, the authors
([@bib:l2013-thompson-Levchuk2008, @bib:l2013-thompson-Levchuk2009,
@bib:l2013-thompson-Levchuk2012Extremal]) also described the large normal
abelian subgroups of finite groups $U$ by showing that they form the set
$Ac_N lr((U))$. (In general, a large normal $P$-subgroup of a finite group is
not a large $P$-subgroup.) It allows us
[@bib:l2013-thompson-Levchuk2012Extremal] to complete (for types $G_2$,
$twisted(3, D_4)$ and $twisted(2, E_6)$) the calculation of the orders $a(U)$.
In [@bib:l2013-thompson-Levchuk2009] the problem (A) is reduced to the question:

_Describe the groups $U$, in which every large abelian subgroup is
$G(K)$-conjugate to a normal subgroup of $U$ and enumerate all the exceptional
large abelian subgroups of the remaining groups $U$
([@bib:l2013-thompson-Levchuk2007, @bib:l2013-thompson-Gupta2008])._

See the exceptions in [@bib:l2013-thompson-Levchuk2009,
@bib:l2013-thompson-Suleimanova2010] and [@bib:l2013-thompson-Suleimanova2012].
In [@bib:l2013-thompson-Levchuk2012Extremal] the authors proved

#theorem[Either every large abelian subgroup of $U$ is $G(K)$-conjugate to a
  normal subgroup of $U$ or $G(K)$ is of type $G_2$, $twisted(3, D_4)$, $F_4$ or
  $twisted(2, E_6)$.] <th:l2013-thompson-exceptions>

G. S. Suleimanova described the exceptional large abelian subgroups for the type
$F_4$ in [@bib:l2013-thompson-Suleimanova2010,
@bib:l2013-thompson-Suleimanova2011F4] and those for the type $twisted(2, E_6)$
in Section @sec:l2013-thompson-e6 and [@bib:l2013-thompson-Suleimanova2012]. In
Section @sec:l2013-thompson-rank-two we complete this description for the types
$G_2$ and $twisted(3, D_4)$.

Twisted groups $twisted(m, Phi)(K)$ required further development of the methods
[@bib:l2013-thompson-Malcev1945]. For the types $twisted(3, D_4)$ and
$twisted(2, E_6)$ there exists a homomorphism $zeta$ from the lattice of the
root system $Phi$ to the lattices of the systems of types $G_2$ and $F_4$
respectively; the preimages of the elements of $zeta(Phi)$ being the
$overline(std.hide(r))$-orbits in $Phi$.

Let $twisted(m, Phi) = zeta(Phi)$. For any $a in zeta(Phi)$ is defined the root
subgroup $X_a$ of $twisted(m, Phi)(K)$. Similarly to
[@bib:l2013-thompson-Levchuk1990] and [@bib:l2013-thompson-Levchuk2012Extremal],
we have $X_a = x_a lr((K_sigma))$, $K_sigma := Ker(1 - sigma)$ when
$zeta^(-1) lr((a))$ is a $overline(std.hide(r))$-orbit of length $1$; in the
remaining cases $X_a = x_a lr((K))$. Then $U = U G(K) = ⟨ X_r | r in G^+ ⟩$,
where $G = Phi$ or $twisted(m, Phi)$. The standard central series is
$U = U_1 supset.eq U_2 supset.eq dots$ [@bib:l2013-thompson-Carter1972]. Let
$lr({r})^+$ be the set of all $s in G^+$ for which the coefficients in the
decomposition of $s - r$ in $Pi(G)$ are all nonnegative. Set
$
  T(r) := ⟨ X_s | s in lr({r})^+ ⟩, quad Q(r) := ⟨ X_s | s in lr({r})^+, s != r
  ⟩ quad (r in G).
$

If $H subset.eq T(r_1) T(r_2) dots T(r_m)$ and the inclusion fails under every
substitution of $T(r_i)$ by $Q(r_i)$ then $Lc(H) = lr({r_1, r_2, dots, r_m})$ is
said to be the _set of corners_ of $H$. Also, $Lc_1 lr((H))$ denotes the set of
first corners for all elements of $H$.

We fix a regular order of the roots, compatible with the root height function
[@bib:l2013-thompson-Carter1972, Lemma 5.3.1]. Each element $gamma$ of $U$
permits a unique compatible (canonical) decomposition into a product of root
elements $x_r lr((gamma_r))$ ($r in G^+$), [@bib:l2013-thompson-Steinberg1967,
Lemma 18]. The coefficient $gamma_r$ is called an _$r$-projection_ of the
element $gamma$. Obviously, the first corner of $gamma$ corresponds to the first
multiplier in its canonical decomposition.

We use usual notation from [@bib:l2013-thompson-Carter1972]: $h(chi)$ for
diagonal automorphisms, $n_r$ for monomial elements and the subgroups
$U_r = ⟨ X_s | s in G^+ without lr({r}) ⟩$, $r in Pi(G)$. For the root systems
of types $E_n$ and $F_4$ simple roots are denoted by $alpha_1, alpha_2, dots$,
similarly to [@bib:l2013-thompson-Bourbaki1968, Tables V–VIII].

Refining [@bib:l2013-thompson-Vdovin2001, Table 4], the following theorem
completes the description of Thompson subgroups.

#theorem[Let $K$ be a finite field and $U = U G(K)$. Then:
  #enum(
    numbering: "a)",
    [$J(U) = J_e lr((U)) = U$ in $U G_2(K)$, $abs(K) > 2$, and in
      $U twisted(3, D_4)(K)$, $abs(K_sigma) > 2$;],
    [$J_e lr((U)) = 1$ and $J(U) = T(a)$ in $U twisted(3, D_4)(8)$;],
    [$J_e lr((U)) = 1$, $J(U) = ⟨ alpha ⟩ times ⟨ alpha^(n_b) ⟩$,
      $alpha = x_a lr((1)) x_(2a+b) lr((1))$ in $U G_2(2)$;],
    [#source(3, printed: 65) $J(U) = J_e lr((U)) = U_(alpha_1)$ in
      $U twisted(2, E_6)(K)$;],
    [$J(U) = J_e lr((U)) = U_(alpha_7) inter U_(alpha_8)$ in $U E_8(K)$.],
  )
] <th:l2013-thompson-thompson>
