#import "../../main-defs.typ": *
#import "defs.typ": *

=== Large Abelian Subgroups of Groups $U$ of Type $twisted(2, E_6)$
<sec:l2013-thompson-e6>

In this section we suppose $U = U twisted(2, E_6)(K)$. For the root system $Phi$
of type $E_6$ the corresponding system $twisted(m, Phi) = zeta(Phi) = G$ is of
type $F_4$. According to Section @sec:l2013-thompson-preliminaries, the group
$U$ is generated by the root subgroups $X_a = x_a lr((K_sigma))$ for all long
roots $a in G^+$ (the first type) and $X_a = x_a lr((K))$ for all short roots
$a in G^+$. For the system of type $F_4$ see also the diagram of the positive
roots from [@bib:l2013-thompson-Levchuk1990] or
[@bib:l2013-thompson-Levchuk2012Extremal]. Use the notation $a b c d$ for the
root $a alpha_1 + b alpha_2 + c alpha_3 + d alpha_4$ of the system of type $F_4$
($alpha_1, alpha_2, alpha_3, alpha_4$ are simple roots) similarly to
[@bib:l2013-thompson-Bourbaki1968, Table VIII]. For certain maps
$tilde(std.hide(t)): K arrow.r K$ and $hat(std.hide(t)): K arrow.r K$ we choose
the following subgroups in the group $U$:
$
  lr({x_1111 lr((t)) x_1231 lr((tilde(t))) | t in K}) lr(
    {x_1121 lr((u)) x_1221
      lr((hat(u))) | u in K}
  ) dot T(0122),
$ <eq:l2013-thompson-e6-1>
$
  X_1111 lr((K_sigma)) lr({x_1121 lr((t)) x_1221 lr((tilde(t))) | t in K})
  X_1231 lr((K^(1-sigma))) T(0122),
$ <eq:l2013-thompson-e6-2>
$
  X_1111 lr((K_sigma)) X_1121 lr((K_sigma)) X_1221 lr((K^(1-sigma))) X_1231
  lr((K^(1-sigma))) T(0122),
$ <eq:l2013-thompson-e6-3>
$
  lr({x_1121 lr((t)) x_1221 lr((tilde(t))) | t in K}) X_1231 T(0122),
$ <eq:l2013-thompson-e6-4>
$
  lr({x_1121 lr((t)) x_1221 lr((c t)) | t in K_sigma}) X_1221 lr((K^(1-sigma)))
  X_1231 T(0122), quad c in.not K_sigma,
$ <eq:l2013-thompson-e6-5>
$ T(0122) U_6, $ <eq:l2013-thompson-e6-6>
$ (T(0121) inter E_6(K_sigma)) U_7. $ <eq:l2013-thompson-e6-7>

Let $G(K) = twisted(2, E_6)(K)$. The aim of this section is to prove that, up to
$G(K)$-conjugacy, the subgroups @eq:l2013-thompson-e6-1–@eq:l2013-thompson-e6-6
for $2K = K$ and the subgroup @eq:l2013-thompson-e6-7 for $2K = 0$ are all large
abelian subgroups of $U$.

We need the following lemma [@bib:l2013-thompson-Levchuk2012Extremal, Lemma
4.4].

#lemma[If $[x_r lr((F)), x_s lr((V))] subset.eq Q(r+s)$ in the group $U$ for
  $F, V subset.eq K$, $F V != 0$, then $r+s$ is of the first type, $r$ and $s$
  are not of the first type, and, up to a diagonal automorphism conjugacy,
  $F subset.eq K_sigma$,
  $V subset.eq K^(1-sigma)$.] <lem:l2013-thompson-trace-pair>

According to A. I. Mal’cev [@bib:l2013-thompson-Malcev1945], a subset $Psi$ of
$Phi^+$ is said to be _abelian_ if $r+s in.not Phi$ for all $r,s in Psi$. A
subset $Psi$ of $Phi^+$ is said to be _$p$-abelian_ (E. P. Vdovin
[@bib:l2013-thompson-Vdovin2001]), if for all $r,s in Psi$ either $r+s in Phi$
and the structure constant $C_(11 r s)$ in the Chevalley formula is zero in
characteristic $p$, or $r+s in.not Phi$. The maximal $2$-abelian subsets for
type $F_4$ are listed in [@bib:l2013-thompson-Vdovin2001, Table 3]. The table
contains $7$ rows and $13$ columns, so the subsets are denoted by $Psi_(i,j)$
($i$ is the row number and $j$ is the column number). In particular,
$Psi_(2,12) = lr({0121})^+ := Psi_1$ and also
$Psi_2 = lr({1111})^+ union lr({0122})^+$,
$Psi_3 = lr({0011,0111,1111,1231}) union lr({0122})^+$ are $Psi_(2,13)$,
$Psi_(6,10)$, respectively. Using [@bib:l2013-thompson-Vdovin2001] we easily
obtain the following lemma.

#lemma[Each maximal $2$-abelian subset of the root system of type $F_4$ either
  coincides with one of the sets $Psi_(1,j)$, $Psi_(4,j)$ ($1 <= j <= 13$) of
  order $10$, or is $W$-conjugate to one of the sets $Psi_i$, $overline(Psi)_i$
  of order $11$ for $i = 1$, $2$ or $3$.] <lem:l2013-thompson-f4-maximal>

Let $m(x) := Lc_1 lr((x))$ ($x in U$). The following three lemmas are proved in
[@bib:l2013-thompson-Suleimanova2012].

#lemma[Let $A$ be a large abelian subgroup of $U$ of type $twisted(2, E_6)$.
  Then for all $x,y in A$, $x,y != 1$, the subset $lr({m(x),m(y)})$ of $Phi$ of
  type $F_4$ is $2$-abelian and, if $m(x)+m(y) in Phi$, then the
  $m(x)$-projections of all elements of $A$ with the first corner $m(x)$ are
  contained in a $1$-dimensional
  $K_sigma$-module.] <lem:l2013-thompson-first-corners>

#source(4, printed: 66)

#lemma[Let $A$ be a large abelian subgroup of $U$ of type $twisted(2, E_6)$,
  $Psi$ be a maximal $2$-abelian subset of the root system of type $F_4$ and let
  $Lc_1 lr((A)) subset.eq Psi$. Then:
  #enum(
    numbering: "a)",
    [if $lr({r_1,r_2,r_3}) subset.eq Psi$, $r_i+r_j in Phi$ and
      $C_(11,r_i,r_j) = plus.minus 2$ for all $i != j$ then the subset
      $lr({r_1,r_2,r_3})$ is contained in $Lc_1 lr((A))$,],
    [if $r+s in Phi$ for the roots $r,s in Psi$, $C_(11,r,s) = plus.minus 2$,
      and the pair $r,s$ is not contained in any triple from a), then
      $r in Lc_1 lr((A))$ or $s in Lc_1 lr((A))$;],
    [if $Psi$ contains a root $r$ such that $(r+Psi) inter Phi = emptyset$ then
      $r in Lc_1 lr((A))$.],
  )
] <lem:l2013-thompson-corner-membership>

#lemma[If $Psi$ is a maximal $2$-abelian subset of type $F_4$, for which there
  exists a large abelian subgroup $A$ such that $m(A) subset.eq Psi$, then $Psi$
  is $W$-conjugate to $Psi_1$ when $2K = 0$ or to $Psi_2$ when $2K = K$.
  Furthermore, all such sets $Psi$ are exhausted, respectively, by the sets
  $
    Psi_(2,9), Psi_(2,12), Psi_(3,1), Psi_(3,7), Psi_(3,12), Psi_(5,1),
    Psi_(5,3),
    Psi_(5,6), Psi_(5,8), Psi_(5,9), Psi_(5,13), Psi_(6,4), Psi_(6,11),
    Psi_(7,1);
  $
  $
    Psi_(2,10), Psi_(2,11), Psi_(2,13), Psi_(3,13), Psi_(5,2), Psi_(5,4),
    Psi_(5,5), Psi_(5,7), Psi_(6,7), Psi_(7,2), Psi_(7,3).
  $
] <lem:l2013-thompson-f4-possible>

Now we consider a large abelian subgroup $A$ of $U = U twisted(2, E_6)(K)$.

#lemma[If $A$ has a simple corner $p$ then $A subset.eq T(p)$ and
  $p != alpha_1$.] <lem:l2013-thompson-simple-corner>

#proof[
  In the canonical decomposition of elements of $U$ we use the regular order of
  the system $Phi$, defined by the order $alpha_1 < alpha_2 < alpha_3 < alpha_4$
  of the simple roots. Note that the inverse order is also regular.

  Suppose that $A$ has at least two simple corners $p < q$. None of the sets
  $Psi_(i,j)$ from Lemma @lem:l2013-thompson-f4-possible contains $alpha_1$, so
  we get $p > alpha_1$. Suppose that $q = alpha_4$. If we replace the regular
  order of $Phi$ by the inverse order then $Lc_1 lr((A))$ will contain $alpha_4$
  and, by Lemma @lem:l2013-thompson-f4-possible, $Lc_1 lr((A))$ is contained in
  one of the sets $Psi_(5,4)$, $Psi_(5,5)$, $Psi_(5,6)$ for $2K = K$ or
  $Psi_(5,3)$, $Psi_(5,6)$, $Psi_(5,8)$, $Psi_(5,9)$ for $2K = 0$. Each of these
  sets contains the root $1242$. #ed-note[The source prints $Psi_(5,6)$ in the
    odd-characteristic list here, although Lemma @lem:l2013-thompson-f4-possible
    lists $Psi_(5,7)$ and excludes $Psi_(5,6)$ in that case. The discrepancy
    remains unresolved.] This root is the only root in $Phi^+$ of height $9$. By
  Lemma @lem:l2013-thompson-corner-membership, c), the root $1242$ is contained
  in $Lc_1 lr((A))$. It is clear, that if there exists an element in
  $A inter T(r)$ with the corner $r$, then $r in Lc_1 lr((A))$ for any regular
  order of $Phi$. Therefore, the roots $alpha_2$ and $alpha_4$ can not be
  corners in $A$ simultaneously. If $q = alpha_3$ then similarly
  $1242 in Lc_1 lr((A))$. Therefore, the case $p = alpha_2$, $q = alpha_3$ is
  also impossible.

  In the remaining case $p = alpha_3$, $q = alpha_4$, by Lemmas
  @lem:l2013-thompson-f4-possible, @lem:l2013-thompson-corner-membership and
  [@bib:l2013-thompson-Vdovin2001, Table 3], we get $1122 in Lc_1 lr((A))$ for
  the inverse order of $Phi$. Therefore, for the initial order, the set
  $Lc_1 lr((A))$ contains a root of height $6$. However, this root and the root
  $alpha_3$ can not be contained in $Lc_1 lr((A))$ simultaneously, by Lemma
  @lem:l2013-thompson-f4-possible and [@bib:l2013-thompson-Vdovin2001, Table 3].
  Therefore, in all cases the subgroup $A$ can have only one simple corner.

  Let $A$ have a simple corner $alpha_i$ and $A subset.eq X_(alpha_i) U_2$.
  Suppose that $A subset.eq.not T(alpha_i)$. Then $A$ has the corner $0011$ for
  $i = 2$, so $A^(n_4)$ has the simple corners $alpha_2$ and $alpha_3$. If
  $i = 3$ then $A$ has the corner $1100$, therefore, $A^(n_1)$ has the corners
  $alpha_2$ and $alpha_3$. If $i = 4$ then $A$ has a corner
  $r in lr({1100,0110,1110,0120,1120,1220})$. In the first and second cases
  $A^(n_2)$ has the corner $alpha_1$ or $alpha_3$, respectively, and the corner
  $alpha_4$. The third case is reduced to the second case by $n_1$-conjugacy. In
  the fourth case $A^(n_3)$ has a corner $alpha_2$ and
  $A^(n_3) subset.eq.not T(alpha_2)$; this gives a contradiction with the proved
  above. The fifth case is reduced to the fourth case by an $n_1$-conjugacy. The
  sixth case is reduced to the fifth case by an $n_2$-conjugacy.
]

Similarly we obtain the following two lemmas.

#lemma[If $A$ has a corner $r$ of height $2$, then $A subset.eq T(r)$ and
  $r != 1100$.] <lem:l2013-thompson-height-two>

#lemma[If $A$ has a corner $r$ of height $3$, then:
  #enum(
    numbering: "a)",
    [$A subset.eq T(r)$ for $r = 0111$;],
    [$A subset.eq T(1110) T(0120)$ for $r = 0120$;],
    [$A subset.eq T(1110) T(0122)$ for $r = 1110$ and
      $A subset.eq X_1110 U_4$.],
  )
] <lem:l2013-thompson-height-three>

#lemma[Each large abelian subgroup of $U$ is $G(K)$-conjugate to a subgroup of
  $U_2$.] <lem:l2013-thompson-reduce-u2>

#proof[
  #source(5, printed: 67) Let $A$ be a large abelian subgroup in $U$ and
  $A subset.eq.not U_2$. By Lemma @lem:l2013-thompson-simple-corner, there
  exists a simple corner $p != alpha_1$ in $A$ and $A subset.eq T(p)$. If
  $p = alpha_2$ then $Lc_1 lr((A))$ is contained in one of the sets $Psi_(2,9)$,
  $Psi_(3,1)$ for $2K = 0$ or $Psi_(2,10)$, $Psi_(2,11)$ for $2K = K$, and
  $1100,1222 in Lc_1 lr((A))$, by Lemma @lem:l2013-thompson-f4-possible.
  Therefore for arbitrary non-zero elements $t,u in K_sigma$ and suitable
  $t_i,u_i in K$ there exist elements $x,y in A$ such that
  $
    x = x_1100 lr((t)) x_0110 lr((t_1)) x_1110 lr((t_2)) x_0120 lr((t_3)) x_0111
    lr((t_4)) mod U_4,
    y = x_1222 lr((u)) x_1232 lr((u_1)) x_1242 lr((u_2)) mod U_10.
  $ <eq:l2013-thompson-u2-elements>
  If $t_1 != 0$ for all elements of the form @eq:l2013-thompson-u2-elements then
  in the inverse order we have $0110 in Lc_1 lr((A))$. However, the sets
  $Psi_(2,11)$ and $Psi_(3,1)$ do not contain this root. Since
  $
    [x,y] = x_1342 lr(
      (u t_3 plus.minus (overline(u)_1 t_1 + u_1
          overline(t)_1))
    ) mod U_11,
  $
  we have $t_3 = 0$ for $t_1 = 0$. So, there exists an element $x' in A$ such
  that
  $ x' = x_1100 lr((t)) x_1110 lr((t_2)) x_0111 lr((t_4)) mod U_4 $
  and hence
  $
    x' = x_1100 lr((t)) x_1110 lr((t_2)) x_0111 lr((t_4)) x_1120 lr((t_5))
    x_1111 lr((t_6)) x_0121 lr((t_7)) mod U_5
  $
  for some $t_5,t_6,t_7 in K$. We may cancel $t_2$ by $X_(alpha_3)$-conjugacy.
  Moreover,
  $
    (x')^(x_(alpha_3) lr((y))) = x_1100 lr((t)) x_1110 lr((t_2 + t y)) x_0111
    lr((t_4)) x_1120 lr(
      (t_5 plus.minus t y overline(y) plus.minus (t_2
          overline(y))^(1+sigma))
    )
    x_1111 lr((t_6)) x_0121 lr((t'_7)) =
    = x_1100 lr((t)) x_1110 lr((t y)) x_0111 lr((t_4)) x_1120 lr(
      (t_5 plus.minus
        t y overline(y))
    ) x_1111 lr((t_6)) x_0121 lr((t'_7)) mod U_5 quad (y in K).
  $

  If $y in K$ and $K^sharp = ⟨ y ⟩$ then $K_sigma^sharp = ⟨ y overline(y) ⟩$.
  Therefore we can choose $y$ such that $t y overline(y) = minus.plus t_5$. So,
  we can transform $x'$ by a $U$-conjugacy to the form
  $
    x' = x_1100 lr((t)) x_1110 lr((t y)) x_0111 lr((t_4)) x_1111 lr((t_6))
    x_0121 lr((t'_7)) mod U_5 quad (y in K).
  $
  Then
  $
    (x')^(n_3) = x_1110 lr((t y)) x_0111 lr((t'_7)) x_1120 lr((t)) x_1111
    lr((t'_6)) x_0121 lr((t_4)) mod U_5 quad (y in K).
  $
  Suppose that $t'_7 != 0$. Then in the inverse order we get
  $0111 in Lc_1 lr((A^(n_3)))$ and $Lc_1 lr((A^(n_3))) = Psi_(3,1)$ for $2K = 0$
  or $Lc_1 lr((A^(n_3))) subset.eq Psi_(2,10)$ for $2K = K$. In the first case
  $1111 in Lc_1 lr((A^(n_3)))$. Therefore, in the initial order, the set
  $Lc_1 lr((A^(n_3)))$ ($= Psi_(2,9)$) must contain a root of height $4$; so we
  get a contradiction with [@bib:l2013-thompson-Vdovin2001, Table 3]. In the
  second case, due to inclusion $0111 in Lc_1 lr((A^(n_3)))$ we get that the
  $1231$-projection of the set of all elements $z in A^(n_3)$ with $m(z) = 1231$
  can not coincide with $K$, by Lemma @lem:l2013-thompson-trace-pair. Hence, in
  the initial order, $Lc_1 lr((A^(n_3)))$, which is contained in $Psi_(2,11)$,
  must contain the root $1111$. Since in the inverse order
  $Lc_1 lr((A^(n_3))) subset.eq Psi_(2,10)$ then the set $Psi_(2,10)$ must
  contain a root of height $4$, and we also get a contradiction with
  [@bib:l2013-thompson-Vdovin2001, Table 3]. Consequently,
  $
    (x')^(n_3) = x_1110 lr((t y)) x_1120 lr((t)) x_1111 lr((t'_6)) x_0121
    lr((t_4)) mod U_5 quad (y in K).
  $
  By $U$-conjugacy, we get $t'_6 = 0$ and for some $u_i in K$ we obtain the
  equality
  $
    (x')^(n_3 n_4) = x_0120 lr((u_1)) x_1120 lr((u_2)) x_1111 lr((u_3)) x_0121
    lr((u_4)) mod U_5 quad (u_3 != 0).
  $

  We may assume that $u_1 = 0$ because otherwise $0120 in m(A^(n_3 n_4))$ and
  $alpha_2 in.not Lc_1 lr((A^(n_3 n_4)))$, see [@bib:l2013-thompson-Vdovin2001,
  Table 3]. Moreover, $u_2 = 0$, since otherwise
  $1120 in Lc_1 lr((A^(n_3 n_4)))$ and $alpha_2 in.not Lc_1 lr((A^(n_3 n_4)))$.
  Also, $u_4 = 0$, since otherwise in the inverse order of $G$ we have
  $0121 in Lc_1 lr((A^(n_3 n_4)))$ and $alpha_2 in.not Lc_1 lr((A^(n_3 n_4)))$.
  Note that
  $1220 in Psi_(2,9) inter Psi_(2,10) inter Psi_(2,11) inter Psi_(3,1)$. By
  Lemma @lem:l2013-thompson-corner-membership, $1220 in Lc_1 lr((A^(n_3 n_4)))$
  and the $1220$-projection of the elements $y$ with $m(y) = 1220$ coincides
  with $K_sigma$. Thus, if $A^(n_3 n_4)$ has a corner #source(6, printed: 68)
  $alpha_2$, then we may assume that the $1220$-projection of $(x')^(n_3 n_4)$
  is zero, up to a multiplication by a suitable element $y$. Applying the
  conjugations by $U$ and $n_3$ to $(x')^(n_3 n_4)$, we get an element of the
  form
  $ x_1121 lr((v_1)) x_0122 lr((v_2)) mod U_6 quad (v_1 != 0). $
  Hence $1121 in Lc_1 lr((A^(n_3 n_4 n_3)))$. It follows
  $alpha_2 in.not Lc_1 lr((A^(n_3 n_4 n_3)))$ and
  $A^(n_3 n_4 n_3) subset.eq U_2$.

  If $p = alpha_3$ then we get $1231 in Lc_1 lr((A))$, by Lemma
  @lem:l2013-thompson-f4-possible. The relation
  $ 1 = [A inter U_7,A] = [A inter U_7, X_(alpha_3) inter (A U_2)] mod U_9 $
  shows that $A inter U_7 = A inter T(1231)$. Up to $X_(alpha_4)$-conjugacy,
  $A inter (X_1231 U_9)$ has an element $gamma$ with the corner $1231$. Since
  $1 = [gamma,A] mod U_9$, we have $A subset.eq X_(alpha_3) T(0110)$ and
  $A^(n_4) subset.eq U_2$. Similarly we consider the case $p = alpha_4$.
]

Analogously we proved

#lemma[Any large abelian subgroup of $U$ is $G$-conjugate to a subgroup of $U_3$
  and even to a subgroup of $U_4$.] <lem:l2013-thompson-reduce-u4>

Finally we get that either $2K = K$ and the subgroup $A$ is $G$-conjugate to
ones from @eq:l2013-thompson-e6-1–@eq:l2013-thompson-e6-6 or $2K = 0$ and $A$ is
$G$-conjugate to the normal subgroup @eq:l2013-thompson-e6-7.

#remark[Taking into account that @eq:l2013-thompson-e6-1–@eq:l2013-thompson-e6-7
  are abelian subgroups, we obtain the equalities $Ac(U) = Ac_e lr((U))$ and
  $J(U) = J_e lr((U)) = U_(alpha_1)$ for the group $U = U twisted(2, E_6)(K)$.
  All large abelian subgroups of the group $U F_4(K)$ are described in
  [@bib:l2013-thompson-Suleimanova2010] and
  [@bib:l2013-thompson-Suleimanova2011F4].] <rem:l2013-thompson-e6-thompson>
