#import "defs.typ": *
=== Fundamental automorphisms and powers of $R_n lr((K,J))$
<sec:l2001-automorphisms-fundamental>
Throughout this paper $K,J,$ and $J^+$ denote an associative ring with identity,
an ideal of $K$ and the additive group of $J$, respectively. If
$lr(||a_(u v)||)$ is a matrix, then $a_(i j)$ is called the $(i,j)$-coefficient.
We denote by $e$, the identity matrix, by $e_(i j)$, the matrix unit of
$M_n lr((K))$ in which the $(i,j)$-coefficient is equal to 1 and others are
zero. We use standard terminology, as in
[@bib:l2001-automorphisms-Hungerford1974],
[@bib:l2001-automorphisms-Kargapolov1979]. The following lemma determines
“annihilator” automorphisms of an arbitrary ring $R$. We set
$Ann R=lr({alpha in R | alpha R=R alpha=0})$.

#source(3, printed: 475)
#lemma[
  Let $zeta:R arrow Ann R$ be an additive map. Then

  (a) the map $1+zeta:x arrow x+zeta(x)$ is an endomorphism of the ring $R$ if
  and only if $zeta(R^2)=0$;

  (b) if $zeta(R^2)=0$ and $Ann R subset.eq R^2$, then $1+zeta$ is an
  automorphism of the ring $R$.
] <lem:l2001-automorphisms-annihilator>
#proof[
  (a) It follows from equalities $(x+zeta(x))(y+zeta(y))=x y$ $(x,y in R)$.

  (b) Evidently $Ker(1+zeta) subset.eq zeta(R) subset.eq Ann R$ and if
  $zeta(R^2)=0$, then $1+zeta$ induces the identity map on $R^2$. If also
  $Ann R subset.eq R^2$, then the map $1+zeta$ is an endomorphism of the ring
  $R$ with zero kernel. It remains to note that the inclusions
  $
    R subset.eq zeta(R)+(1+zeta)R subset.eq R^2+(1+zeta)R
    subset.eq (1+zeta)R subset.eq R
  $
  are equalities. The lemma is proved.
]

For an arbitrary associative ring $R$ the adjoint multiplication $compose$ and
the associated Lie multiplication $*$ are defined as
$
  alpha compose beta=alpha+beta+alpha beta, quad
  alpha*beta=alpha beta-beta alpha.
$
An element $alpha in R$ is called quasi-regular if there exists an element
$alpha' in R$ such that $alpha compose alpha'=alpha' compose alpha=0$. For
instance, the quasi-inverse of a nilpotent element $-alpha$ is defined as
$(-alpha)'=alpha+alpha^2+alpha^3+dots$. The adjoint conjugation of $R$ by a
quasi-regular element
$ alpha' compose y compose alpha=y+y*alpha+alpha'(y*alpha), quad y in R, $
<eq:l2001-automorphisms-adjoint-conjugation>
gives an “inner” automorphism of the ring $R$. It coincides with ordinary
conjugation of $R$ by the element $e+alpha$ when the ring $R$ contains identity
$e$. A ring $R$ is called radical if $(R,compose)$ is a group. Each element
$alpha$ of any radical ring $R$ determines an inner automorphism as in
@eq:l2001-automorphisms-adjoint-conjugation.

Let $R$ be the ring $R_n lr((K,J))$. It is a radical ring if and only if $J$ is
a quasi-regular ideal of $K$; i.e., $(J,compose)$ is a group. The conjugation
$delta^(-1)alpha delta$ $(alpha in R)$ by an arbitrary invertible diagonal
$n times n$ matrix $delta$ over $K$ determines an automorphism of $R$ which is
called “diagonal.” An automorphism $theta$ of the ring $K$ determines an
automorphism $lr(||a_(u v)||) arrow lr(||theta(a_(u v))||)$ of the ring $R$ if
and only if the ideal $J$ is $theta$-invariant. Such an automorphism of $R$ is
called a “$K$-ring” or “ring” automorphism as usual. On the other hand, an
automorphism $theta$ of the additive group $K^+$ determines an automorphism of
the ring $R_2 lr((K,J))$ as above if the ideal $J$ is $theta$-invariant and the
relation $(z y)^theta=z^theta y^theta$ is satisfied for $z in K$, $y in J$ and
for $z in J$, $y in K$. This generalization of a $K$-ring automorphism will be
called a $(K^+,J)$-ring automorphism of $R_2 lr((K,J))$ if $1^theta=1$.

Note that the ring $R$ is generated by sets $K e_(i+1,i)$ $(i=1,2,dots,n-1)$ and
$J e_(1 n)$ since $1 in K$. The following lemmas describe powers $R^k$ and their
annihilators in the ring $R$. We put $J^0=K$.

#source(4, printed: 476)
#lemma[
  Let $k$ be a positive integer and $k=s n+t$, $0<=t<n$. Then the ideal $R^k$
  consists of all matrices $lr(||a_(u v)||)$ such that the element $a_(u v)$ is
  placed in the ideal $J^s$, $J^(s+1)$, $J^(s+2)$ respectively to cases
  $t<=u-v$, $t-n<=u-v<t$, $u-v<t-n$.
] <lem:l2001-automorphisms-powers>
#proof[
  It is easy to show by induction on $k$ (see also
  [@bib:l2001-automorphisms-Kargapolov1979, 16.1.2;
  @bib:l2001-automorphisms-Kolesnikov1999, Theorem 3]).
]
An ideal $J$ is called nilpotent of class $m$, if $m$ is the smallest positive
integer such that $J^m=0$. As a corollary of Lemma
@lem:l2001-automorphisms-powers we obtain that if $J$ is a nilpotent ideal of
$K$ of a class $m$, then the ring $R$ is nilpotent of class $m n$.

#lemma[
  The left (resp. right) annihilator of $R^k$ $(k=s n+t,0<=t<n)$ in the ring $R$
  consists of all matrices $alpha in R$ such that all elements of the first $t$
  columns (resp. last $t$ rows) of $alpha$ are in the left (resp. right)
  annihilator of $J^(s+1)$ in $K$ and other elements are placed in the left
  (resp. right) annihilator of $J^s$ in $K$.
] <lem:l2001-automorphisms-power-annihilators>
#proof[
  It is sufficient to note that the elements of the first $t$ rows of matrices
  of $R^k$ are ranged over the ideal $J^(s+1)$. Remaining elements of the first
  column of the matrices are ranged over the ideal $J^s$ by Lemma
  @lem:l2001-automorphisms-powers.
]
Let $Ann_K J=lr({x in K | x J=J x=0})$. Then $Ann R=(Ann_K J)e_(n 1)$ by Lemma
@lem:l2001-automorphisms-power-annihilators. If $n>2$ or $n=2$ but
$Ann_K J subset.eq J$, then $Ann R subset.eq R^2$ by Lemma
@lem:l2001-automorphisms-powers and an arbitrary annihilator automorphism of the
ring $R$ has the form
$
  lr(||a_(u v)||) arrow lr(||a_(u v)||)+
  (lambda_n lr((a_(1 n)))+sum_(i=1)^(n-1) lambda_i lr((a_(i+1,i)))) e_(n 1)
  quad (lr(||a_(u v)||) in R),
$
<eq:l2001-automorphisms-annihilator-map>
where additive maps $lambda_n$ of $J$ and $lambda_1,lambda_2,dots,lambda_(n-1)$
of $K$ into $Ann_K J$ satisfy $lambda_n lr((J^2))=0$, $lambda_i lr((J))=0$,
$1<=i<n$. We denote by $zeta_i lr((lambda))$ $(1<=i<=n)$ an annihilator
automorphism @eq:l2001-automorphisms-annihilator-map of $R$ such that
$lambda_i=lambda$ and $lambda_j$ are zero for all $j!=i$. It is clear that the
annihilator automorphism @eq:l2001-automorphisms-annihilator-map of $R$ is equal
to the product
$zeta_1 lr((lambda_1)) zeta_2 lr((lambda_2)) dots zeta_n lr((lambda_n))$.

Choose an arbitrary homomorphism $sigma:J^+ arrow K^+$ and
$lambda,mu in End(J^+)$. Consider the following map of the set of all elementary
matrices
$
  y e_(1 n) arrow y e_(1 n)+y^lambda e_(11)+y^mu e_(n n)+y^sigma e_(n 1),
  quad y e_(i n) arrow y e_(i n)+y^lambda e_(i 1),
$
$
  y e_(1 j) arrow y e_(1 j)+y^mu e_(n j),
  quad 1<i<=n, quad 1<=j<n, quad y in J.
$
<eq:l2001-automorphisms-almost-annihilator-map>
(We assume that the remaining elementary matrices from $R$ are fixed.) If map
@eq:l2001-automorphisms-almost-annihilator-map determines an automorphism of the
ring $R$, then the invariance under
@eq:l2001-automorphisms-almost-annihilator-map of relations
$x e_(i 1)y e_(1 n)=x y e_(i n)$, $y e_(1 n)x e_(n j)=y x e_(1 j)$ and
$(y e_(1 n))(z e_(1 n))=0$ gives
$
  (x y)^lambda=x y^lambda, quad (y x)^mu=y^mu x,
  quad y z^mu=-y^lambda z, quad (z y)^sigma=z^mu y^lambda,
$
$
  y^mu z^sigma+y^sigma z^lambda=y z^sigma+y^lambda z^lambda
  =y^sigma z+y^mu z^mu=0, quad y,z in J, quad x in K.
$
<eq:l2001-automorphisms-almost-annihilator-conditions>

#source(5, printed: 477)
On the other hand, if $lambda,mu$, and $sigma$ satisfy
@eq:l2001-automorphisms-almost-annihilator-conditions, then map
@eq:l2001-automorphisms-almost-annihilator-map preserves all basic relations
$
  x e_(i j)+y e_(i j)=(x+y)e_(i j), quad
  (x e_(i j))(y e_(j m))=x y e_(i m), quad
  (x e_(i j))(y e_(k m))=0, quad j!=k,
$
in the ring $R$ and hence it determines an automorphism of the ring $R$ which
will be called almost-annihilator. We denote by $zeta^((l)) lr((lambda))$ (resp.
$zeta^((r)) lr((mu))$), an automorphism
@eq:l2001-automorphisms-almost-annihilator-map with zero $mu,sigma$ (resp.
$lambda,sigma$). By Lemma @lem:l2001-automorphisms-power-annihilators,
$zeta^((l)) lr((lambda))$ is the identity map of $R$ modulo the left annihilator
of $R$.
