#import "defs.typ": *
=== The automorphism group
<sec:l2001-automorphisms-group>
We investigate the automorphism group $Aut R_n lr((K,J))$ of a radical ring
$R_n lr((K,J))$. Let $K$ be an associative ring with identity, as above, and let
$K^("#")$ be the multiplicative group of all invertible elements of $K$. Denote
by $B$ (resp. $B'$), the subgroup of $Aut R_n lr((K,J))$ which is generated by
all annihilator and almost-annihilator (resp. almost-annihilator) automorphisms.
Also, we denote by $D,F,A(K,J)$, and $A(K^+,J)$, subgroups which form all
diagonal, inner, $K$-ring, and $(K^+,J)$-ring (for $n=2$) automorphisms,
respectively. The following theorem is the main result of this section.

#theorem[
  Let $J$ be an ideal of $K$ such that a one-sided or two-sided annihilator of
  $J^t$ in $K$ coincides with $J$ for a nonnegative integer $t$. Then
  $Aut R_n lr((K,J))=B F D A(K,J)$ for $n>2$. If inclusion
  $
    lr({c in K | c J=J c=J upright("(mod") J^2 upright(")")}) subset.eq K^("#")
  $
  <eq:l2001-automorphisms-unit-condition>
  is satisfied then $Aut R_2 lr((K,J))=B' F D A(K^+,J)$.
] <th:l2001-automorphisms-main>
Let $R=R_n lr((K,J))$. We require the following lemmas.

#lemma[
  Let $K$ be an associative ring with identity and $n>2$. Then each automorphism
  of the ring $NT_n lr((K))$ is equal to a product of certain diagonal, inner,
  $K$-ring, and annihilator automorphisms of $NT_n lr((K))$.
] <lem:l2001-automorphisms-niltriangular>
#proof[
  See [@bib:l2001-automorphisms-Levchuk1975,
  Theorem~@th:l1975-automorphisms-ring-decomposition;
  @bib:l2001-automorphisms-Levchuk1983, Theorem~@th:l1983-main-automorphisms].
]
#lemma[
  If an ideal $J$ of the ring $K$ coincides with a one-sided or two-sided
  annihilator of $J^t$ in $K$ for a nonnegative integer $t$ and $n>=2$, then the
  ideal $M_n lr((J))$ of the ring $R$ is characteristic.
] <lem:l2001-automorphisms-characteristic-ideal>
#proof[
  If $t=0$, then $J^t=K$ and $J=0$ since $1 in K$. Suppose $t>0$. All powers of
  $R$ and also their one-sided annihilators are characteristic in $R$. The left
  (resp. right) annihilator of $R^(t n)$ in $R$ is equal to the set of all
  matrices of $R$ over the left (resp. right) annihilator of $J^t$ in $K$ by
  Lemma @lem:l2001-automorphisms-power-annihilators. The intersection of
  one-sided annihilators is equal to $M_n lr((Ann_K lr((J^t)))) inter R$. The
  lemma is proved.
]

#source(6, printed: 478)
#lemma[
  Let $J$ be a quasi-regular ideal of $K$, $n>=2$, and let
  @eq:l2001-automorphisms-unit-condition hold for $n=2$. Let $phi$ be an
  automorphism of the ring $R$ and let the ideal $M_n lr((J))$ be
  $phi$-invariant. Then there exists a diagonal automorphism $delta$ of $R$ such
  that the $(i+1,i)$-coefficient of the matrix $e_(i+1,i)^(phi delta)$ is equal
  to 1 for all $i$, $1<=i<n$.
] <lem:l2001-automorphisms-diagonal-normalization>
#proof[
  Denote the $(i+1,i)$-coefficient of the matrix $e_(i+1,i)^phi$ by $c_i$.
  First, we show that $c_i in K^("#")$ for all $i$, $1<=i<n$. If $n=2$, we
  obtain $e_(21)^phi in c_1 e_(21)+M_2 lr((J))$ and
  $
    R^2=(e_(21)+M_2 lr((J)))^phi R=J e_(21)+c_1 J e_(22)+J e_(11)+M_2 lr((J^2))
  $
  since $R^2$ and $M_2 lr((J))$ are $phi$-invariant. It gives $J=c_1 J+J^2$ and
  similarly $J c_1+J^2=J$. Consequently, $c_1 in K^("#")$ by
  @eq:l2001-automorphisms-unit-condition. Suppose $n>2$. The automorphism $phi$
  induces an automorphism of the quotient-ring $frac(R, M_n lr((J)))$ which is
  isomorphic to the ring $NT_n lr((K/J))$ for the associative ring $K/J$ with
  identity. By Lemma @lem:l2001-automorphisms-niltriangular there exist elements
  $f_i in K$ and $u_i in J$ such that $c_i f_i=1+u_i$, $i=1,2,dots,n-1$.
  Therefore all elements $1+u_i$ and $c_i$ are invertible in $K$ since the ideal
  $J$ is quasi-regular.

  Choose now the conjugation $delta$ of $R$ by the diagonal matrix
  $diag(d_1, d_2, dots, d_n)$ where $d_1=1$ and
  $d_(i+1)=c_i c_(i-1) dots c_2 c_1$, $1<=i<n$. Then the $(i+1,i)$-coefficient
  of the matrix $e_(i+1,i)^(phi delta)$ is equal to 1 for all $i$ as required.
]
#lemma[
  Let $n>=2$ and let $phi$ be an automorphism of a ring $R_n lr((K,J))$ such
  that the $(i+1,i)$-coefficient of a matrix $e_(i+1,i)^phi$ is equal to 1 for
  each $i$, $i<n$. Then $phi in B A(K,J)F$ for $n>2$ and $phi in B' A(K^+,J)F$
  for $n=2$.
] <lem:l2001-automorphisms-normalized-generation>
#proof[
  First, we show that there exists an inner automorphism $psi$ such that each
  matrix $e_(i+1,i)^(phi psi)-e_(i+1,i)$ has zero $i$th column. Clearly, for any
  matrix $beta$ the $m$th column of the matrix $beta e_(k m)$ is equal to the
  $k$th column of $beta$ and other columns of $beta e_(k m)$ are zero. Let
  $alpha_t=(e_(t,t-1)^phi-e_(t,t-1))e_(t-1,t)$, $1<t<=n$. The matrix $alpha_t$
  is placed in the left ideal $R e_(t t)$ of the ring $R$ and $alpha_t^2=0$. By
  @eq:l2001-automorphisms-adjoint-conjugation we get
  $
    alpha'_t compose e_(i+1,i)^phi compose alpha_t=
    e_(i+1,i)^phi-alpha_t e_(i+1,i)^phi+
    (e-alpha_t)e_(i+1,i)^phi alpha_t
    in e_(i+1,i)^phi-alpha_t e_(i+1,i)^phi+R e_(t t).
  $
  Denote by $d_j$ the $(2,j)$-coefficient of the matrix $e_(21)^phi$. Since
  $d_1=1$, the matrices $alpha_2$ and $alpha_2 e_(21)^phi$ have zero second rows
  and hence
  $
    alpha_2 e_(21)^phi=(e_(21)^phi-e_(21))e_(12)e_(21)^phi
    =sum_(j=1)^n (e_(21)^phi-e_(21))d_j e_(1 j),
  $
  $
    (alpha'_2 compose e_(21)^phi compose alpha_2)e_(11)=e_(21)^phi e_(11)
    -(e_(21)^phi-e_(21))e_(11)=e_(21).
  $
  Consequently, the first column of the matrix
  $alpha'_2 compose e_(21)^phi compose alpha_2$ is equal to the second column of
  the identity matrix. Suppose that $1<i<n$ and each #source(
    7,
    printed: 479,
  )matrix $e_(t+1,t)^phi-e_(t+1,t)$, $1<=t<i$, has zero $t$th column. The
  adjoint conjugation of the element $alpha_(i+1)$ does not change the $t$th
  column of such a matrix since the $t$th column of $alpha_(i+1)e_(t+1,t)^phi$
  is zero. On the other hand, the $i$th column of the matrix
  $(alpha'_(i+1) compose e_(i+1,i)^phi compose alpha_(i+1))-e_(i+1,i)$
  is also zero. Thus, without loss of generality we may assume that the $i$th
  column of each matrix $e_(i+1,i)^phi-e_(i+1,i)$ $(1<=i<n)$ is zero.

  Consider the product $(x e_(k m))^phi e_(i+1,i)^phi$, $1<=i<n$. Its $i$th
  column is equal to the $(i+1)$st column of the first factor. If $i+1!=m$, this
  product is equal to zero. Therefore, all columns of matrix $(x e_(k m))^phi$
  $(1<=k<=n,1<=m<=n)$ are zeros except the first and $m$th columns. In
  particular, $e_(i+1,i)^phi in e_(i+1,i)+R e_(11)$ for $1<i<n$ and
  $e_(21)^phi=e_(21)$. Consequently, the first row of each matrix
  $(x e_(k m))^phi$ for $k>1$ is zero since $e_(21)^phi(x e_(k m))^phi=0$. For
  $n>2$ we set $alpha_1=-b_3 e_(21)-b_4 e_(31)-dots-b_n e_(n-1,1)$ where
  $b_(i+1)$ is the $(i+1,1)$-coefficient of the matrix $e_(i+1,i)^phi$. By
  @eq:l2001-automorphisms-adjoint-conjugation we obtain
  $
    alpha'_1 compose e_(21) compose alpha_1=e_(21), quad
    alpha'_1 compose e_(i+1,i)^phi compose alpha_1=
    e_(i+1,i)^phi+e_(i+1,i)^phi alpha_1=e_(i+1,i)^phi-b_(i+1)e_(i+1,1)
  $
  for $1<i<n$. Therefore, without loss of generality we may assume that the
  $(i+1)$st row of each matrix $e_(i+1,i)^phi-e_(i+1,i)$ $(1<=i<n)$ is also
  zero. Since $e_(i+1,i)^phi(x e_(k m))^phi=0$ for $i!=k$, $1<=i<n$, we obtain
  that all rows of a matrix $(x e_(k m))^phi$ are zeros except the $k$th and
  $n$th rows. In particular, the restriction of $phi$ on $NT_n lr((K))$ is an
  automorphism of the ring $NT_n lr((K))$.

  Suppose $n>2$. By Lemma @lem:l2001-automorphisms-niltriangular there exist an
  automorphism $theta$ of the ring $K$ and endomorphisms $phi_i$ of the additive
  group $K^+$ such that
  $ (x e_(i+1,i))^phi=x^theta e_(i+1,i)+x^(phi_i)e_(n 1), $
  <eq:l2001-automorphisms-simple-root-images>
  $
    e_(i+1,i)^phi=e_(i+1,i)+a_i e_(n 1), quad a_1=a_(n-1)=0 quad (x in K,1<=i<n)
  $
  <eq:l2001-automorphisms-unit-root-images>
  for $a_i=1^(phi_i)$. Clearly $(x e_(i j))^phi=x^theta e_(i j)$ for $i-j>1$.
  The relations $e_(n,n-1) dots e_(32)(y e_(21))=e_(n 1)(y e_(1 n))e_(n 1)$ are
  $phi$-invariant for all $y in J$. Hence the $(1,n)$-coefficient of a matrix
  $(y e_(1 n))^phi$ is equal to $y^theta$. By using
  @eq:l2001-automorphisms-simple-root-images and
  @eq:l2001-automorphisms-unit-root-images we get
  $
    (y e_(1 n))^phi=y^theta e_(1 n)+y^lambda e_(11)
    +y^mu e_(n n)+y^sigma e_(n 1),
    quad (y e_(i n))^phi=y^theta e_(i n)+y^lambda e_(i 1),
  $
  $
    (y e_(1 j))^phi=y^theta e_(1 j)+y^mu e_(n j),
    quad (y e_(i j))^phi=y^theta e_(i j),
    quad 1<i<n, quad 1<j<n, quad y in J,
  $
  <eq:l2001-automorphisms-ideal-images>
  where $lambda,mu in End(J^+)$ and $sigma$ is a homomorphism of $J^+$ into
  $K^+$. Since the set of all $(1,n)$-coefficients of matrices in $R^phi$
  coincides with $J^theta$ we obtain the equality $J=J^theta$. Therefore,
  $theta$ induces a $K$-ring automorphism of the ring $R$.

  Without loss of generality we may assume that $theta$ is the identity map of
  $K$. The $phi$-invariance of relations
  $(K e_(i+1,i))(J e_(1 n))=0=(J e_(1 n))(K e_(i,i-1))$ gives
  $(K^(phi_i))J=0=J(K^(phi_(i-1)))$ for $1<i<n$. Also
  $
    (x J e_(i+1,i))^phi=(x e_(i+1,i))^phi(J e_(i i))^phi
    =(x e_(i+1,i)+x^(phi_i)e_(n 1))(J e_(i i)), quad 1<=i<n.
  $

  #source(8, printed: 480)
  Consequently, $J^(phi_i)=(K^(phi_i))J=a_i J$ and similarly
  $J^(phi_i)=J(K^(phi_i))=J a_i$. Taking into account
  @eq:l2001-automorphisms-unit-root-images we get that $phi$ is a product of the
  annihilator and almost-annihilator automorphisms as in Section
  @sec:l2001-automorphisms-fundamental.

  Assume $n=2$. Let $x^theta$ be the $(2,1)$-coefficient of a matrix
  $(x e_(21))^phi$ for $x in K$. As above, we get $1^theta=1$ and
  $ (x e_(21))^phi=x^theta e_(21) quad (x in K), $
  $
    e_(21)(y e_(12))^phi e_(21)
    =[e_(21)(y e_(12))e_(21)]^phi=y^theta e_(21), quad y in J.
  $
  Therefore, @eq:l2001-automorphisms-ideal-images is satisfied and $theta$ is an
  automorphism of the additive group $K^+$ such that $J^theta=J$. Finally,
  relations
  $(z y)^theta e_(21)=(z e_(21))^phi(y e_(11))^phi=z^theta y^theta e_(21)$
  show that the relation $(z y)^theta=z^theta y^theta$ is satisfied for
  $z in K,y in J$ and similarly for $z in J,y in K$. Consequently, $phi$ is a
  product of the almost-annihilator and $(K^+,J)$-ring automorphisms of
  $R_2 lr((K,J))$. The lemma is proved.
]

Now Theorem @th:l2001-automorphisms-main follows easily by Lemmas
@lem:l2001-automorphisms-characteristic-ideal–
@lem:l2001-automorphisms-normalized-generation.

We consider some cases when the conditions of Theorem
@th:l2001-automorphisms-main hold.

(A) Let $J$ be a maximal ideal of $K$ which is nilpotent of a class $t+1>1$.
Then $Ann_K lr((J^t))=J$ since $Ann_K lr((J^t))$ is a proper ideal of $K$ which
contains $J$. If $K$ is a local ring, then $K backslash J=K^("#")$ and
@eq:l2001-automorphisms-unit-condition is satisfied.

(B) Let $a$ be an element of a ring $K$ and $a K=K a=Ann_K lr((a^t))$ for
positive integer $t$. Let $J$ be the principal ideal $(a)$. Clearly
$Ann_K lr((J^t))=J$. Suppose $J$ contains one-sided annihilators of $a$. (For
instance, $Ann_K a=Ann_K J subset.eq Ann_K lr((J^t))=J$ if $a$ is in the center
of the ring $K$.) Then @eq:l2001-automorphisms-unit-condition is satisfied. In
fact, if $c in K$ and $c J+J^2=J$ then there exist elements $x,y in K$ such that
$(c x+y a-1)a=0$ and $c x in 1+J subset.eq K^("#")$. Therefore there exists
right (similarly left) inverse of $c$ in $K$.

(C) Let $p$ be a prime and $m$ be a positive integer. Let $K=M_n lr((Z_(p^m)))$
for $n>=1$ or $K$ is a ring of polynomials in commutative or noncommutative
indeterminates (of finite or infinite number) over $Z_(p^m)$. If $d$ is an
arbitrary divisor of $m$, $1<=d<m$, and $J$ is the principal ideal $p^d K$ of
$K$, then the case (B) for $t=(m-d)/d$ holds.

#example[
  Let $K_1$ be an associative ring with identity which has a nilpotent ideal
  $J_1$ of class two. Let $K$ be a direct product $(K_1,K_1)$ of two copies of
  the ring $K_1$ and $J$ be the ideal $(J_1,0)$ of $K$. If
  $lambda:(a,0) arrow (a,a)$ $(a in J_1)$, then $zeta_n lr((lambda))$ is an
  automorphism of the ring $R_n lr((K,J))$ $(n>2)$ by Lemma
  @lem:l2001-automorphisms-annihilator and the ideal $M_n lr((J))$ is not
  $zeta_n lr((lambda))$-invariant.
] <exm:l2001-automorphisms-noncharacteristic-ideal>
#remark[
  Let $J$ be an arbitrary quasi-regular ideal of a ring $K$ and $n>2$. All
  automorphisms of the ring $R_n lr((K,J))$ that leave invariant the ideal
  $M_n lr((J))$ are described by Lemmas
  @lem:l2001-automorphisms-diagonal-normalization and
  @lem:l2001-automorphisms-normalized-generation. In the general case, the
  subgroup of such automorphisms does not coincide with the automorphism group
  of the ring $R_n lr((K,J))$ as the last example shows. However, the #source(
    9,
    printed: 481,
  )authors have no example of a radical ring $R_n lr((K,J))$ such that the
  equality $Aut R_n lr((K,J))=B F D A(K,J)$ does not hold.
] <rem:l2001-automorphisms-general-case>
