#import "../../main-defs.typ": *
#import "../../collection.typ": article-introduction
#import "defs.typ": *
#article-introduction[Introduction] <sec:l1992-chevalley-introduction>
#source(1, printed: 227)
Our purpose is to expound the results for Chevalley groups concerning with
solution of question 6.34 [@bib:l1992-chevalley-Kourovka1980] and of problem 1.5
[@bib:l1992-chevalley-Kondratyev1986] which are formulated in detail below.

=== Congruence subgroups of Chevalley groups of normal type
<sec:l1992-chevalley-normal>
It has been constructed commutator series and lower central ones of different
congruence subgroups of groups $GL_n lr((K))$ in papers by Ph. Hall
[@bib:l1992-chevalley-Hall1964], Yu. I. Merzlyakov
[@bib:l1992-chevalley-Merzlyakov1964], D. A. Suprunenko
[@bib:l1992-chevalley-Suprunenko1965] and other authors. An uniform way of their
construction has been supposed in [@bib:l1992-chevalley-Merzlyakov1964] basing
on usage carpets of ideals (see also [@bib:l1992-chevalley-Kargapolov1982,
16.1.2]). Partially, it allowed to investigate a commutator structure of Sylow
$p$-subgroups of groups $GL_n lr((Z_(p^m)))$.

Let $K$ be a commutative (associative) ring with an unit and let $J$ be
quasiregular ideal. We define the sequence of ideals by recurrent relations:
$J_0 = K$, $J_(n+1) = J_n J$ $(n >= 0)$. Carpets of ideals
$
  lr({J_(f_n lr((i,j,k))) | 1 <= i,j <= n}), quad
  k = k_0, k_0 + 1, k_0 + 2, dots,
$
are distinguished in [@bib:l1992-chevalley-Merzlyakov1964] by means of using a
certain function $f_n$. The main theorem of
[@bib:l1992-chevalley-Merzlyakov1964] shows under quitely general conditions
that in groups $GL_n lr((K))$, $SL_n lr((K))$ a mutual commutant of subgroups
defined by $k$-th and $m$-th carpets is the subgroup defined by $(k+m)$-th
carpet of the same form. Analogic theorem for symplectic groups has been proved
by Yu. V. Sosnovsky [@bib:l1992-chevalley-Sosnovsky1978]; see also
[@bib:l1992-chevalley-Roloff1982]. Yu. I. Merzlyakov raised the question: to
prove the analogic theorem a) for the orthogonal groups, b) for the unitary
groups (see [@bib:l1992-chevalley-Kourovka1980, question 6.34]). Below the
theorem by Yu. I. Merzlyakov is transferred to Chevalley groups and thus to
#source(2, printed: 228)
orthogonal and unitary ones.

Now suppose $Phi$ is an indecomposable root system, $f$ is function defined for
positive integers $k >= k_0$ and $r in Phi union {0}$, taking an integer values
$>= 0$ under the conditions:
$ "F1)" quad f(0,k) > 0; quad "F2)" quad f(r,k) <= f(r,k+1); $
$ "F3)" quad f(q,k+m) <= f(r,k) + f(q-r,m), $
$q,r,q-r in Phi union {0}$, and for any fixed $q,k,m$ one can find $r$ for which
F3) is identity. Let us call a pair $k,m >= k_0$ unpeculiar in relation to $f$,
if the lattice of the dual root system $Phi^* = {h_r | r in Phi}$ is generated
by co-roots $h_r = 2r/(r,r)$ such that F3) is identity for $q = 0$.

Let us call a pair $Phi,K$ unpeculiar, if $p(Phi) ! K = K$ (here and further
$p(Phi) = max lr({(r,r)/(s,s) | r,s in Phi})$) or $Phi = A_1 (= C_1)$, $2K = K$.
(Elementary) Chevalley group $Phi(K)$ of normal type $Phi$ over $K$, as well as
in [@bib:l1992-chevalley-Steinberg1967, § 3], is generated by root elements
$x_r lr((t))$ $(r in Phi, t in K)$. A space of representation of corresponding
Lie algebra is fixed arbitrarily. It permits automorphism $h(chi)$ with
condition $h(chi)^(-1) x_r lr((t)) h(chi) =
x_r lr((chi(r)t))$ for each homomorphism $chi$ of additive group $L_0 lr((Phi))$
generated by all roots into multiplicative group $K^("#")$ of ring $K$. We
denote by $G^((k))$ a group generated by elements
$
  h(chi) quad (chi in Hom(L_0 lr((Phi)), 1 + J_(f(0,k)))), quad
  x_r lr((t)) quad (r in Phi, t in J_(f(r,k))),
$
and by $S^((k))$ its intersection with $Phi(K)$ group.

Analog of Yu. I. Merzlyakov's theorem [@bib:l1992-chevalley-Merzlyakov1964] for
Chevalley groups of normal types is #theorem[
  Let us assume that function $f$, ideals $J$, $J_m$ and groups $G^((k))$,
  $S^((k))$ are chosen as pointed out above. Then:
  #source(3, printed: 229)
  #enum(numbering: "1)", [$[G^((k)),G^((m))] subset S^((k+m))$;], [if $Phi,K$
    and $k,m$ are unpeculiar pairs, then $[S^((k)),S^((m))] = S^((k+m))$.])
] <th:l1992-chevalley-normal-commutators>

As in [@bib:l1992-chevalley-Merzlyakov1964] (case of $Phi = A_n$),
[@bib:l1992-chevalley-Sosnovsky1978] (that of $Phi = C_n$), the applications of
Theorem @th:l1992-chevalley-normal-commutators are considered. For example, if
$Phi,K$ is unpeculiar pair, assuming $f(r,k) = k$ in Theorem
@th:l1992-chevalley-normal-commutators (this function has no peculiar pairs
$k,m >= 1$), thus get commutator and lower central series of congruence subgroup
by $J$-level in Chevalley group $Phi(K)$. Let us consider an other important
case.

#example[
  Let $h$ is a Coxeter number of root system $Phi$, $ht r$ — a height of root
  $r$, $ht 0 = 0$. Function $f(r,k) = -floor((ht r-k)/h)$ ($floor()$ — an
  integer part of quantity) satisfies the conditions F1)–F3). A pair $k,m >= 1$
  is peculiar for it, partially when $h > 2$ and the numbers $k+m$ are divisible
  by $h$; for arbitrary peculiar pair $k,m$ the number $k+m$ is always divisible
  by $h$, while those $k-1$, $m-1$ are not $h$-divisible. Originating from this
  function $f$ and from ideal $J = (p)$ of ring $Z_(p^m)$, let us form subgroups
  $S^((k))$ of group $Phi(Z_(p^m))$. Then $S^((1))$ is the Sylow $p$-subgroup;
  its order, when $Phi(Z_(p^m))$ being an universal Chevalley group, is equal to
  $p^M$, where $M = m(|Phi|+n) - |Phi^+| - n$, $n$ is a rank of $Phi$. If a
  prime $p > p(Phi)$, and at $Phi = A_1$ also $p > 2$, then by Theorem
  @th:l1992-chevalley-normal-commutators
  $S^((1)) supset S^((2)) supset S^((3)) supset dots supset S^((m h)) = 1$
  is a lower central series of $S^((1))$ group. If also $h != 2^t$ $(t > 1)$ or
  $m = 1$, that subgroups $S^((2^i))$, $i = 0,1,2,dots,d$,
  $d = -floor(-log_2 lr((m h)))$, form a commutator series of group $S^((1))$.
] <exm:l1992-chevalley-sylow-series>
