#import "../../main-defs.typ": *
#import "defs.typ": *
=== Twisted Chevalley groups <sec:l1992-chevalley-twisted>
Let us appoint an analog of Yu. I. Merzlyakov's theorem for several twisted
Chevalley groups.

Two-fold symmetry of Coxeter graph for root system $Phi$ of types $E_6$, $D_n$,
$A_(2n-1)$ or $A_(2n)$ gives rise to isometry $r mapsto overline(r)$ of the
#source(4, printed: 230)
main Euclydian space, being $overline(Phi) = Phi$. By
[@bib:l1992-chevalley-Steinberg1967, § 11, Theorem 32 and Remark] define a
homomorphism $zeta$ of system $Phi$ onto the root system of types $F_4$,
$B_(n-1)$, $C_n$ or $BC_n$ respectively, for which
$zeta(r) = zeta(overline(r))$. Let us consider a function $f$ with conditions
F1)–F3), as well as in Sect.~@sec:l1992-chevalley-normal, adding F4)
$f(r,k) = f(overline(r),k)$. Here the unpeculiarity of pair $k,m$ in respect to
$f$ is equivalent to that lattice $L_0 lr((Phi))$ is generated by set
$ Phi(k, m, f) = lr({r in Phi | f(r,k) + f(-r,m) = f(0,k+m)}). $
If, besides that, a lattice of system dual to $zeta(Phi)$ is generated by set
dual to $zeta(Phi(k, m, f))$, that $k,m$ is called as $zeta$-unpeculiar pair.

If $K$ is commutative ring with an unit and an involutive automorphism
$sigma: x mapsto overline(x)$ $(x in K)$, then group $Phi(K)$ permits an
involutive automorphism $T$, for which
$
  (x_r lr((t)))^T = x_(overline(r)) lr((plus.minus overline(t)))
  quad (r in Phi, t in K).
$
Twisted Chevalley group $twisted(2, Phi) lr((K))$ (Steinberg group) is a
centralizator of $T$ in group $Phi(K)$; see also E. Abe
[@bib:l1992-chevalley-Abe1977]. As before, for quasiregular ideal $J$ of ring
$K$ assume $J_(m+1) = J_m J$ $(m >= 0)$ and also
$J_(m,sigma) = J_m inter Ker(1-sigma)$. Denote by $G^((k))$ a group generated by
elements
$
  h(chi) quad (chi in Hom(L_0 lr((Phi)), 1 + J_(f(0,k))),
    chi(overline(a)) = overline(chi(a)), a in Phi),
$
$
  x_r lr((t)) quad (r in Phi, r = overline(r),
    t in J_(f(r,k),sigma)),
$
$
  x_r lr((t)) (x_r lr((t)))^T quad
  (r in Phi, r != overline(r), t in J_(f(r,k))),
$
and by $S^((k))$ — its intersection with group $twisted(2, Phi) lr((K))$.

#source(5, printed: 231)
#theorem[
  Let groups $G^((k))$ and subgroups $S^((k))$ of twisted group
  $twisted(2, Phi) lr((K))$, $Phi = E_6$, $D_n$ $(n >= 4)$ or $A_(2n-1)$
  $(n > 1)$ are formed by means of above-described manner, originated from
  function $f$ with conditions F1)–F4) and from quasiregular ideal $J$ of
  commutative ring $K$, while being $J = overline(J)$ and
  $
    J_k J_(m,sigma) = J_(k+m), quad J_k^(1+sigma) = J_(k,sigma), quad
    J_(k,sigma) J_(m,sigma) = J_(k+m,sigma).
  $
  Then:
  #enum(numbering: "1)", [$[G^((k)),G^((m))] subset S^((k+m))$;], [if $k,m$ is
    $zeta$-unpeculiar pair and $2K = K$, then $[S^((k)),S^((m))] = S^((k+m))$.])
] <th:l1992-chevalley-twisted-commutators>

Obviously, functions $f$ in examples of Sect.~@sec:l1992-chevalley-normal
satisfy the F1)–F4) conditions. If $K$ is a ring of polynomials by alone
variable $x$ over $Z_(p^m)$, $p > 2$, and $sigma: g(x) mapsto g(-x)$
$(g(x) in K)$, that ideals $J_k = p^k K$ satisfy the conditions of Theorem
@th:l1992-chevalley-twisted-commutators. An another example: $K$ is a ring,
$J = 0$. Note also, that transferring the theorem by Yu. I. Merzlyakov to
twisted groups of type $twisted(2, A_(2n))$ (a case of unitary group with odd
dimension) leads to a more bulky theorem.
