#import "../../main-defs.typ": *
#import "defs.typ": *
=== Unipotent subgroups and their automorphisms
<sec:l1992-chevalley-automorphisms>
J. Gibbs [@bib:l1992-chevalley-Gibbs1970] described central series,
characteristic subgroups and automorphisms of unipotent subgroup $UG(K)$ of
Chevalley group of normal or twisted type $G$ ($= Phi$ or $twisted(n, Phi)$)
over a field $K$ of characteristic $p != 2,3$, and for $G = A_n$ at $p != 2$.
(Herein are the references to earlier papers by P. P. Pavlov, A. J. Weir, E.
Spitznagel.) A question of describing the essential cases $p = 2,3$ already for
the finite main field makes up the content of problem 1.5
[@bib:l1992-chevalley-Kondratyev1986].

#source(7, printed: 233)
Upper and lower central series of groups $U Phi(K)$ get success to describe
evidently for arbitrary commutative ring $K$ with unit. At $p(Phi) ! K = K$ they
coincide with standard central series
$U_1 supset U_2 supset dots supset U_h = 1$, where $U_m$ is subgroup generated
by root subgroups $X_r = x_r lr((K))$ $(r in Phi, ht r >= m)$; a condition of
invertibility for element $p(Phi) !$ here is important. A standard central
series of twisted group $U twisted(n, Phi) lr((K))$ is composed of its
intersections with subgroups $U_m$. Here is just

#theorem[
  Upper and lower central series of twisted-type unipotent group over a field
  are always standard.
] <th:l1992-chevalley-twisted-central-series>

In order to describe characteristic subgroups of group $UG(K)$ let us
distinguish a class $Omega$ of all its normal subgroups, which is invariant
under all graph automorphisms (for $G = Phi$) and is generated by root subgroups
$X_a$, $a in G^+$, or (for twisted groups) by their centrals.

#theorem[
  Let $K$ is a perfect field, if $2K = 0$, $G = B_2$, $twisted(2, B_2)$, $F_4$,
  $twisted(2, F_4)$, or $3K = 0$, $G = G_2$, $twisted(2, G_2)$, and is an
  arbitrary one in the rest cases. Then $Omega$ coincides with class of all
  characteristic subgroups of group $UG(K)$, except the following groups:
  $
    U C_n lr((K)) quad (n >= 2, K = 2K = 3K), quad U G_2 lr((4)), quad
    U twisted(2, E_6) lr((4)), quad U twisted(2, D_n) lr((4)) quad (n >= 4),
  $
  $
    U C_n lr((3)) quad (n >= 3), quad U B_3 lr((3)), quad U G_2 lr((3)),
    quad U Phi(2) quad (Phi != A_3,D_4).
  $
] <th:l1992-chevalley-characteristic-subgroups>

In the exceptional cases the characteristic subgroups have been also described
evidently.

As usually, we distinguish the standard automorphisms of group $UG(K)$. They are
products of its inner, ring, diagonal, central (acting trivially by center
modulus), graph and, more generally, idempotent-graph automorphisms;
[@bib:l1992-chevalley-Gibbs1970] and at $G = A_n$
[@bib:l1992-chevalley-Levchuk1975],
[@bib:l1992-chevalley-LevchukConnections1976]. Now automorphism of arbitrary
group (or ring) we
#source(8, printed: 234)
call as hypercentral of height $m >= 0$, if it acts trivially by modulus of
$m$-th hypercenter (see [@bib:l1992-chevalley-Kargapolov1982, 16.1]) and is not
inner by that of $(m-1)$-th one at $m >= 1$.

#theorem[
  Arbitrary automorphism of group $UG(K)$ of Lie rank $> 4$ over a field $K$ is
  product of standard automorphism and (evident) hypercentral one of height $m$,
  being $m <= n-1$ at $G = B_n$ or $C_n$, and $m <= 5$ in the rest cases.
] <th:l1992-chevalley-high-rank-automorphisms>

(Note that in a case $K = 2K = 3K$ studied by Gibbs
[@bib:l1992-chevalley-Gibbs1970] one ought to have $m <= 3$ at $G = C_n$ and
$m <= 2$ in the rest cases.) Automorphisms of unipotent subgroups of Lie rank
$<= 4$ have been described by another way. In particular, for group
$U twisted(2, F_4) lr((K))$ over the perfect field $K$ of characteristic 2 all
automorphisms are standard. Description of automorphisms of groups $U Phi(K)$ of
types $Phi = A_n$ $(n > 1)$, $C_n$ $(n > 2)$, $D_n$ $(n >= 4)$, $E_n$
$(n = 6,7,8)$ has been found for arbitrary commutative ring with unit.

One cannot improve the estimation of quantity $m$ in Theorem
@th:l1992-chevalley-high-rank-automorphisms. In particular, group
$U C_n lr((K))$, $n > 2$, over the perfect ring $K$ of characteristic 2 always
permits the hypercentral automorphism of height $n-1$. If the root system of
type $C_n$ and its base are chosen as in [@bib:l1992-chevalley-Carter1972, p.
47], that such automorphism can be defined on root elements by the rule:
$
  x_(2e_n) lr((t)) mapsto x_(2e_n) lr((t))
  x_(e_1+e_n) lr((c sqrt(t^2-t))),
$
$
  x_(2e_i) lr((t)) mapsto x_(2e_i) lr((t))
  x_(e_1+e_i) lr((c sqrt(t))), quad (t in K, 1 < i < n)
$
$
  x_(e_i+e_n) lr((t)) mapsto x_(e_i+e_n) lr((t))
  x_(e_1+e_i) lr((c t)),
$
where $c$ is an arbitrary element of $K$. (Rest root elements hold their
places.)
