#import "../../main-defs.typ": *
#import "defs.typ": *
=== Unitriangular groups and locally niltriangular rings
<sec:l1992-chevalley-unitriangular>
#source(9, printed: 235)
A basic ground for automorphisms' description is the case $G = A_(n-1)$, i.e.
that of unitriangular group $UT_n lr((K))$ (see denotes in
[@bib:l1992-chevalley-Kargapolov1982]). Orders of automorphisms' groups have
been calculated at $K = GF(q)$. In particular,
$ |Aut UT_n lr((2))| = 2^(n-1) |UT_n lr((2))|, quad n > 4. $
Taking into account enclosing the finite 2-groups into $UT_n lr((2))$ ones, we
obtain

#proposition[
  Each finite 2-group is isomorphically enclosed into a finite 2-group, whose
  group of automorphisms is 2-group too.
] <prop:l1992-chevalley-two-group-embedding>

Analogic result for $p$-groups at $p > 2$ is following from results by M. V.
Khoroshevsky [@bib:l1992-chevalley-Khoroshevsky1971].

We investigate group $UT_n lr((K))$ [@bib:l1992-chevalley-Levchuk1975,
@bib:l1992-chevalley-LevchukConnections1976] as an adjoint group (in respect to
multiplying $a compose b = a+b+a b$) of ring $NT_n lr((K))$ of niltriangular
$n times n$ matrices over $K$ with zeros on and over the main diagonal.
Structural ties of adjoint group and associated Lie ring play an important part.
(See also A. I. Malcev [@bib:l1992-chevalley-Malcev1949]) In
[@bib:l1992-chevalley-Levchuk1987] these ties are considered for a more general
situation.

Namely let $Gamma$ is an arbitrary chain (linearly ordered set). By definition
the ring $NT_Gamma lr((K))$ is generated by elements $x e_(i j)$
$(x in K, i,j in Gamma, i > j)$ submitted to usual rules of additing and
multiplicating elementary matrices. In known sense it is a locally niltriangular
ring.

#theorem[
  Let $K$ is an arbitrary (not obligatorily a commutative) associative ring with
  unit. Then a class of all normal subgroups of adjoint group of ring
  $NT_Gamma lr((K))$ coincides with class of all ideals of associated Lie ring.
] <th:l1992-chevalley-unitriangular-normal-lie>

#source(10, printed: 236)
Note that assumption $1 in K$ in Theorem
@th:l1992-chevalley-unitriangular-normal-lie might be substantiated by a more
weak requirement of generating the ring $K$ by subset ${x y | x,y in K}$; as the
example shows, it is impossible to remove the last demand. See also
[@bib:l1992-chevalley-Kourovka1980, question 6.19 together with comment], and
10.19 one.

I. D. Ado [@bib:l1992-chevalley-Ado1943] pointed out an example of $p$-group
coinciding with the derived group, having used (in another terminology) an
adjoint group of ring $NT_Gamma lr((GF(p)))$, where $Gamma$ is the chain of
rational numbers within segment $[0,1]$. One can obtain analogical examples,
using an everyone dense chain; see also an example of characteristically simple
$p$-group by D. McLain [@bib:l1992-chevalley-McLain1954]. Hence it is also
consequent that usual method to describe action of automorphisms by modulus of
centrals is not applicable here. When $K$ is a ring without divisors of zero, an
evident description of maximal Abelian ideals of Lie ring $NT_Gamma lr((K))$ has
a success [@bib:l1992-chevalley-Levchuk1987]. Also using Theorem
@th:l1992-chevalley-unitriangular-normal-lie, we obtain automorphic images of
maximal Abelian ideals
$angle.l x e_(i j) | x in K, j in S, i in Gamma without S angle.r$ for every
possible segments $S$ of chain $Gamma$. This conforms a basic ground for
description of automorphisms.

Isometries and antiisometries of arbitrary chain $Gamma$ induce automorphisms of
adjoint group of ring $NT_Gamma lr((K))$ (analogically, of associated Lie ring).
The ring, diagonal and locally inner automorphisms are defined naturally. If $K$
is a ring without divisors of zero $(1 in K)$ and $|Gamma| > 4$, that an
arbitrary automorphisms might be expanded into the product of above-listed
automorphisms and an evident hypercentral one of height $<= 3$
[@bib:l1992-chevalley-Levchuk1987].

A case of finite chain $Gamma$ is mostly investigated. Namely in
[@bib:l1992-chevalley-Levchuk1975, @bib:l1992-chevalley-LevchukConnections1976]
automorphisms of ring $NT_n lr((K))$ over an arbitrary
#source(11, printed: 237)
(associative) ring $K$ with unit have been described. Description of
automorphisms of adjoint group and those of associated Lie ring have been also
described at $n > 4$; as before they are a product of standard automorphism and
hypercentral one of height $<= 3$. When $n <= 4$, automorphisms have been
described under the condition of commutativity of ring $K$ and in some another
cases.
