#import "../../main-defs.typ": *
#import "defs.typ": *

=== Automorphisms of the Algebras $A_n$ and $B_n$
<sec:l2008-monic-free-algebras>

We consider a free associative algebra $A_n = F〈x_1,x_2,dots,x_n〉$ over an
arbitrary field $F$ with the free generators $x_1,x_2,dots,x_n$ and a polynomial
algebra $B_n = F[x_1,dots,x_n]$ in $n$ commutative #source(5, printed: 384)
variables. If $phi$ is an endomorphism of such an algebra and $x_i^phi = phi_i$
for all $i$, then we write $phi = (phi_1,phi_2,dots,phi_n)$.

We call an automorphism _elementary_ if it has the form

$ (x_1,dots,x_(k-1),alpha x_k+f,x_(k+1),dots,x_n), $
<eq:l2008-monic-elementary-automorphism>

where $f$ is a polynomial not containing $x_k$ and $alpha in F^times$. An
automorphism is said to be _tame_, if it is a product of some elementary
automorphisms; all other automorphisms are called _wild_. Tame and wild
automorphisms, in particular, the Anick automorphism of $A_n$ and the Nagata
automorphism of $B_n$ were considered in [@bib:l2008-monic-Czerniakiewicz1971],
[@bib:l2008-monic-Nagata1972], [@bib:l2008-monic-Cohn1985], etc. It was recently
proved in characteristic zero that the Nagata automorphism and the Anick
automorphism are wild, [@bib:l2008-monic-Shestakov2003],
[@bib:l2008-monic-Umirbaev2006]. Thus, for $n = 3$ in characteristic zero, the
tame automorphism groups $TAut A_n$ and $TAut B_n$ are proper subgroups of
groups $Aut A_n$ and $Aut B_n$, respectively.

In both algebras we choose the ideal $R$ generated by the elements
$x_1,x_2,dots,x_n$. Obviously, for every automorphism of the ideal $R$ there
exists a unique continuation on the whole algebra.

We now show that the study of the wild automorphisms of the algebras $A_n$ and
$B_n$ comes to the study of wild monic automorphisms of the ideal $R$. We
consider the following automorphisms of the algebras $A_n$ and $B_n$:

$ (x_1+c_1,x_2+c_2,dots,x_n+c_n), quad c_i in F. $
<eq:l2008-monic-translations>

Also for every $alpha in GL_n lr((F))$ we define the automorphism of $R$:

$ tilde(alpha): X arrow.r X alpha, quad X = (x_1,x_2,dots,x_n). $

#proposition[Let $phi$ be an automorphism of the algebra $A_n$ or $B_n$. Then
  $phi$ is a product of the continuation of some monic automorphism of $R$,
  $tilde(alpha)$ for some $alpha in GL_n lr((F))$ and an automorphism
  @eq:l2008-monic-translations.]
<prop:l2008-monic-affine-reduction>

#proof[Since $x_i^phi = c_i$, $1 <= i <= n$, modulo $R$, up to a multiplication
  by an automorphism @eq:l2008-monic-translations we may suppose that $phi$
  preserves $R$. Therefore modulo $R^2$ we have

  $ phi(X) = X alpha, quad phi^(-1)(X) = X beta $

  for some $n times n$ matrices $alpha,beta$ over $F$. It follows that
  $alpha = beta^(-1) in GL_n lr((F))$ and hence $tilde(alpha) in Aut R$. So
  $phi$ is a continuation of an automorphism of $R$ which is a product of
  $tilde(alpha)$ and some monic automorphism of the ideal $R$.]

It is well-known that every invertible matrix over any field is a product of
elementary matrices. Therefore we obtain

#corollary[Up to a multiplication by a tame automorphism any automorphism of the
  algebras $A_n$ and $B_n$ is the continuation of a monic automorphism of $R$.]
<cor:l2008-monic-reduction-to-monic>

Note that monic endomorphisms of the ideal $R$ and its factors $R/R^k$ are
always monomorphisms. Every n-tuple $(phi_1,dots,phi_n)$ over $R^2$ determines
an endomorphism

$ (x_1+phi_1,dots,x_n+phi_n), quad phi_i in R^2. $
<eq:l2008-monic-monic-endomorphism>

of $R$. This endomorphism is not always an automorphism.

#example[#source(6, printed: 385) We show that a monic endomorphism
  $phi = (x_1+x_1 x_1,x_2,dots,x_n)$ of $R$ is not an automorphism. Suppose it
  is an automorphism. It fixes the ideal generated by $x_2,dots,x_n$, and its
  inverse fixes that ideal as well. On the quotient $F[x_1]$ it would therefore
  induce an automorphism $x_1 arrow.r x_1+x_1^2$. For any nonconstant polynomial
  $g$, however, $deg g(x_1+x_1^2) = 2 deg g$, so $x_1$ is not in the image. This
  gives us a contradiction. Thus $phi$ is not an automorphism. A criterion for
  an endomorphism of the algebra $A_n$ to be an automorphism, based on the
  concept of a Fox derivation [@bib:l2008-monic-Crowell1967], is proved in
  [@bib:l2008-monic-Romankov2004].]
<exm:l2008-monic-nonsurjective-endomorphism>

Let us consider some properties of endomorphisms of the ideal $R$ and a factor
algebra $R/R^k$ for a fixed integer $k > 1$. The following lemma is evident.

#lemma[Any tame automorphism of $R$ induces a tame automorphism of a free
  nilpotent algebra $R/R^k$. Any tame automorphism of $R/R^k$ is induced by a
  tame automorphism of an ideal $R$.]
<lem:l2008-monic-tame-lifting>

Clearly, a monic endomorphism $phi$ of the algebra $R$ or $R/R^k$ is an
automorphism if and only if this algebra is equal to its $phi$-image. By
definition, $phi$ induces the identity automorphisms on the factors
$R^m/R^(m+1)$, $m = k-1,k-2,dots,1$. Consequently, $phi(R/R^k) = R/R^k$. Thus
the following lemma holds.

#lemma[Every monic endomorphism of a free nilpotent algebra is always an
  automorphism.]
<lem:l2008-monic-nilpotent-monic-invertible>

As above, every matrix $alpha in GL_n lr((F))$ defines an automorphism
$tilde(alpha)$ of the ideal $R$. This notation is preserved for the induced
automorphisms of $R/R^k$. The following lemma gives a canonical form of tame
automorphisms.

#lemma[Let $phi$ be a tame monic automorphism of $R$. Then there exist scalar
  multiples of monomials $m_i in R^2$ not containing $x_1$ and
  $tilde(lambda)_i in tilde(GL)_n lr((F))$, $i = 1,2,dots,v$, such that

  $ phi = product_(i=1)^v tilde(lambda)_i^(-1) e_i tilde(lambda)_i, $
  <eq:l2008-monic-tame-normal-form>

  $ e_i = (x_1+m_i,x_2,dots,x_n). $
  <eq:l2008-monic-monomial-shear>
]
<lem:l2008-monic-tame-normal-form>

#proof[By definition any tame automorphism can be written as a product of
  elementary automorphisms. Up to a substitution and a linear automorphism, any
  elementary automorphism may be written as a product of elementary
  automorphisms @eq:l2008-monic-monomial-shear. So we have:

  $
    phi = tilde(mu)_1 e_1 dots tilde(mu)_v e_v tilde(mu)_(v+1)
    = tilde(mu)_1 e_1 tilde(mu)_1^(-1) tilde(mu)_1 tilde(mu)_2 e_2 dots
    tilde(mu)_1 dots tilde(mu)_v e_v tilde(mu)_v^(-1) dots
    tilde(mu)_1^(-1) tilde(mu)_1 dots tilde(mu)_(v+1),
  $

  where $tilde(mu)_i in tilde(GL)_n lr((F))$, $e_i$ is like
  @eq:l2008-monic-monomial-shear for some scalar multiples of monomials $m_i$.
  Let $tilde(lambda)_i = (tilde(mu)_1 dots tilde(mu)_i)^(-1)$. Since $phi$ acts
  identically modulo $R^2$ we have $x_i^phi = x_i mod R^2$. On the other hand
  $x_i^phi = x_i^(tilde(lambda)_(v+1)^(-1)) mod R^2$. Hence
  $tilde(lambda)_(v+1)$ is an identity.]

We should also mention the following corollary of Lemma
@lem:l2008-monic-tame-normal-form.

#lemma[If $phi$ is a tame automorphism of a free nilpotent algebra $R/R^k$ over
  a field $F$ which is a subfield of the field $D$ then its scalar extension is
  a tame automorphism of a free nilpotent algebra over $D$.]
<lem:l2008-monic-tameness-scalar-extension>

Thus, if some automorphism of the algebra $A_n$ over a field $F$ induces a wild
automorphism of a free nilpotent algebra over a field $D$ and $F$ is a subfield
of $D$ then the former automorphism of $A_n$ is wild.
