#import "defs.typ": *
#import "../../collection.typ": paper-abstract, paper-keywords
#source(1, printed: 169)
#paper-abstract[
  For any chain $Gamma$ the ring $NT(Gamma, K)$ of all finitary $Gamma$-matrices
  $lr(‖a_(i j)‖)_(i,j in Gamma)$ over an associative ring $K$ with zeros on and
  above the main diagonal is locally nilpotent and hence radical. If
  $R'=NT(Gamma', K')$, $R=NT(Gamma, K)$ and either $|Gamma|<infinity$ or $K$ is
  a ring with no zero-divisors, then isomorphisms between rings $R$ and $R'$,
  their adjoint groups and associated Lie rings are described.
]
#paper-keywords[
  chain, finitary matrix, radical ring, adjoint group, associated Lie ring,
  isomorphism.
]
#heading(level: 3, numbering: none)[Introduction]
<sec:l2004-finitary-introduction>
Let $K$ be an associative ring with identity and $Gamma$ be a chain (or linearly
ordered set) by the order relation $<=$. The finitary unitriangular group
$UT(Gamma, K)$ is always locally nilpotent, however it coincides with the
commutator subgroup for any dense chain $Gamma$ and also it does not satisfy the
normalizer condition for every infinite chain $Gamma$, see
[@bib:l2004-finitary-Levchuk1987] and [@bib:l2004-finitary-Merzlyakov1995]. The
aim of this paper is to investigate isomorphisms of the groups $UT(Gamma, K)$
and the associated rings.

The ring $NT(Gamma, K)$ is generated by elements $x e_(i j)$
$(x in K,i,j in Gamma,i>j)$ with the usual rules of the addition and
multiplication of elementary matrices. Set $R=NT(Gamma, K)$. In
[@bib:l2004-finitary-Levchuk1976; @bib:l2004-finitary-Levchuk1983;
@bib:l2004-finitary-Levchuk1987] the unitriangular group $UT(Gamma, K)$ is
considered as the adjoint group $G(R)$ of the ring $R$. (The map
$alpha arrow.r e+alpha$ ($alpha in R$) for the identity $Gamma$-matrix $e$ is a
well-known isomorphism between them.) Automorphisms of $G(R)$ and those of the
associated Lie ring $Lambda(R)$ or $R$ are described if either
$|Gamma|<infinity$ or $K$ is arbitrary ring with no zero-divisors, see
[@bib:l2004-finitary-Levchuk1975; @bib:l2004-finitary-Levchuk1983;
@bib:l2004-finitary-Levchuk1987]. In Remark
@rem:l2004-finitary-standard-isomorphism we define a standard isomorphism of
$G(R)$ (similarly, $Lambda(R)$) as a product of some main isomorphisms. Let $f$
be an idempotent in the center of $K$ and $S$ be a ring. Any isomorphism $theta$
of the additive group $K^+$ of $K$ onto $S^+$ with $theta(1_K)=1_S$ inducing an
isomorphism of the ideal $f K$ and an anti-isomorphism of $(1_K-f)K$ will be
#source(2, printed: 170)called an $f$-isomorphism or idempotent isomorphism of
the ring $K$. It determines an ‘idempotent $S$-ring isomorphism’ of $G(R)$
(resp. $Lambda(R)$) by
$
  x e_(i j) arrow.r theta(x f)e_(i j)-theta(x-x f)e_(j' i')
  quad (x in K,i,j in Gamma,i>j)
$ <eq:l2004-finitary-idempotent-isomorphism>
for any anti-automorphism $'$ of the chain $Gamma$, see
[@bib:l2004-finitary-Levchuk1975] and [@bib:l2004-finitary-Levchuk1983]. Rings
$K$ and $S$ are called idempotent isomorphic, if there exists some idempotent
isomorphism between them. Evidently, every ring isomorphism $theta:K arrow.r S$
and chain isomorphism (or isometry) $':Gamma arrow.r Omega$ induce,
respectively, a ‘$S$-ring isomorphism’ $x e_(i j) arrow.r x^theta e_(i j)$ and
‘$Omega$-chain isomorphism’ $x e_(i j) arrow.r x e_(i' j')$
$(x in K,i,j in Gamma,i>j)$ of the ring $R$. Also, the opposite isomorphism, a
central (which acts like the identity, modulo the center), hypercentral of
height $<=3$ and triangular automorphisms of $G(R)$ (resp. $Lambda(R)$) will be
use in the paper. We now formulate the main result.

#common.theorem-like("Main theorem", "th", none, false)[
  Let $K$ and $S$ be associative rings with identities, $Gamma$ and $Omega$ be
  chains, $R=NT(Gamma, K)$, $R_S=NT(Omega, S)$ and $|Gamma|>2$. Then the
  following hold:
  #enum(
    numbering: "(i)",
    [If $R tilde.eq R_S$ and either $|Gamma|<infinity$ or $K$ is a ring with no
      zero-divisors, then $K tilde.eq S$, $Gamma tilde.eq Omega$ and every
      isomorphism of the ring $R$ onto $R_S$ is a product of a triangular and a
      central automorphisms of $R$, an $Omega$-chain and $S$-ring
      isomorphisms.],
    [If $K$ is a ring with no zero-divisors, $|Gamma|>4$ and there exists an
      isomorphism $psi$ of $G(R)$ onto $G(R_S)$ or of $Lambda(R)$ onto
      $Lambda(R_S)$, then $psi$ is a standard isomorphism and either
      $Gamma tilde.eq Omega$, $K tilde.eq S$ or
      $Gamma tilde.eq Omega^((upright("op")))$,
      $K tilde.eq S^((upright("op")))$.],
    [For $4<|Gamma|<infinity$ the adjoint groups $G(R)$ and $G(R_S)$ or
      associated Lie rings $Lambda(R)$ and $Lambda(R_S)$ are isomorphic if and
      only if rings $K$ and $S$ are idempotent isomorphic and $|Omega|=|Gamma|$;
      every isomorphism between them is standard.],
  )
] <th:l2004-finitary-main>

Note that for $Gamma={1,2}$ rings $R$ and $Lambda(R)$ have zero multiplication,
$G(R) tilde.eq R^+ tilde.eq K^+$ and every isomorphism $theta$ of the additive
group $K^+$ determines an isomorphism of the ring $R$ by rule
$x e_(2 1) arrow.r x^theta e_(2 1)$ $(x in K)$. By Remark
@rem:l2004-finitary-small-ranks, for $|Gamma|=3,4$ there exist nonstandard
automorphisms of $G(R)$ and $Lambda(R)$.

In the case $Gamma=Omega$ and $K=S$ main theorem describes $Aut R$, $Aut G(R)$
and $Aut Lambda(R)$. Automorphisms and isomorphisms of classical linear groups
have been under active research for a long time, see surveys
[@bib:l2004-finitary-Merzlyakov1980; @bib:l2004-finitary-Golubchik1983;
@bib:l2004-finitary-Hahn1984; @bib:l2004-finitary-Abe1995;
@bib:l2004-finitary-Li1996]. The unitriangular group $UT(Gamma, K)$ is a
$pi$-group for $"char" K!=0$ and $pi=pi("char" K)$ of any finite degree
$|Gamma|$ or over any finite field is a Sylow subgroup of the general linear
group and its automorphisms were studied in [@bib:l2004-finitary-Pavlov1952;
@bib:l2004-finitary-Weir1955; @bib:l2004-finitary-Levchuk1975;
@bib:l2004-finitary-Levchuk1983; @bib:l2004-finitary-McBride1983;
@bib:l2004-finitary-You1989; @bib:l2004-finitary-Maginnis1993]. Main results of
[@bib:l2004-finitary-Levchuk1983; @bib:l2004-finitary-Levchuk1987] are obtained
by using close structural connections between $G(R)$ and $Lambda(R)$, see also
[@bib:l2004-finitary-Levchuk1976], [@bib:l2004-finitary-Kuzucuoglu2000, §
@sec:l2000-ideals-structural] and [@bib:l2004-finitary-Zelmanov1995]. Methods
and results of [@bib:l2004-finitary-Levchuk1983] were extended to all Chevalley
groups in [@bib:l2004-finitary-Levchuk1990; @bib:l2004-finitary-Levchuk1992] and
to certain radical matrix rings in [@bib:l2004-finitary-Kuzucuoglu2001;
@bib:l2004-finitary-Levchuk2002]. In the present paper this approach is also
used to investigate of isomorphisms of $G(R)$ and $Lambda(R)$ for
$R=NT(Gamma, K)$.
