#import "defs.typ": *
=== Automorphisms and the Central Series
<sec:l2004-finitary-central-series>
#source(3, printed: 171)
In this section we introduce certain automorphisms and terminology. Henceforth,
$K$ denotes an associative ring with identity $1_K$ and $Gamma$ a chain of order
$>2$. Denote by $j^+$, the direct successor of $j$ in $Gamma$, i.e. the first
element of the subset ${y in Gamma | j<y}$; if it does not exist, then we set
$j^+=j$. Similarly, by using the direct predecessor of $j$, the element $j^-$ is
also defined. If $j<i$, then we write $j triangle.l i$ for $i=j^+$ and otherwise
$j lt.double i$. By [@bib:l2004-finitary-Kuratowski1968, p. 209], a proper
subset $X$ of $Gamma$ is said to be an initial segment if for every $x in X$ and
$y in Gamma$ with $y<x$ we have $y in X$. We denote by $[i,j]$, the segment
${k in Gamma | i<=k<=j}$, by $p$ and $q$, the first and the last element of
$Gamma$ (if they exist), respectively. For $Gamma$-matrices $lr(‖a_(i j)‖)$ with
$i,j in Gamma$ we use the standard matrix notation.

Recall that the adjoint multiplication $compose$ and the associated Lie
multiplication $ast$ of an arbitrary associative ring are defined by
$alpha compose beta=alpha+beta+alpha beta$ and
$alpha ast beta=alpha beta-beta alpha$, respectively. Let $R=NT(Gamma, K)$ and
$Lambda(R)$ be the associated Lie ring of $R$. Since the ring $R$ is locally
nilpotent, $(e-beta)^(-1)=e+beta+beta^2+beta^3+dots$ for all $beta in R$. Thus,
$(R,compose)$ is a group (the adjoint group of $R$) which we denote by $G(R)$.
The adjoint conjugation by an element $-beta$ of $R$ coincides with ordinary
conjugation
$
  (e-beta)alpha(e-beta)^(-1)=alpha+(alpha ast beta)(e-beta)^(-1),
  quad alpha in R.
$
This gives an inner automorphism of $R$. We now consider its generalization. It
is easy to see that all triangular $Gamma$-matrices $lr(‖a_(i j)‖)$ (with
$a_(i j)=0$ for $i<j$) over $K$ having a finite number of nonzero elements in
each row and column form a ring with identity with respect to the usual matrix
addition and multiplication. For arbitrary invertible $Gamma$-matrix $gamma$ of
this ring the conjugation $alpha arrow.r gamma alpha gamma^(-1)$ $(alpha in R)$
is a ‘triangular’ automorphism of the ring $R$ or a ‘diagonal’ automorphism, if
$gamma$ is a diagonal $Gamma$-matrix. If $gamma-e$ has zero main diagonal, then
the conjugation by $gamma$ is an automorphism which acts like an inner
automorphism of $R$ on each finite set and, therefore, it is a ‘locally inner’
automorphism of $R$ in according to [@bib:l2004-finitary-Gorchakov1978].

We now describe the central series and the central automorphisms. #lemma[
  The center of the ring $R$ is nonzero if and only if the chain $Gamma$
  contains the first element $p$ and the last element $q$. If $p,q in Gamma$ and
  $m$ is a positive integer, then $m$th hypercenter of $G(R)$ and $Lambda(R)$
  are generated by the sets $K e_(i j)$ $(j<i)$ with $|[p,j]|+|[i,q]|<=m+1$.
] <lem:l2004-finitary-hypercenters>
#proof[
  It is clear for a finite chain $Gamma$. In general case we assume that the
  center of $R$ contains nonzero element $alpha$. Then there exists a finite
  subchain $Gamma_1$ of $Gamma$ satisfying $alpha in NT(Gamma_1, K)$. For every
  such subchain the element $alpha$ is in the center of $NT(Gamma_1, K)$ which
  has form $K e_(i j)$. Evidently, it is possible only if $p,q in Gamma$ and
  equalities $i=q$ and $j=p$ are satisfied. In particular, the center of $R$ is
  zero if and only if the chain $Gamma$ has no first or last element. By
  induction on $m$ we obtain the second statement of the lemma.
]
Let $Gamma_0={j in Gamma | j^+!=j}$. Clearly, $Gamma_0=emptyset$ if and only if
the chain $Gamma$ is dense.

#source(4, printed: 172)
#lemma[
  The subgroup of the central automorphisms of the ring $R$ is nonidentity if
  and only if $p,q in Gamma$ and $Gamma_0!=emptyset$. It has a decomposition in
  the Cartesian product of $|Gamma_0|$ subgroups which are isomorphic to the
  additive group $(End(K^+))^+$.
] <lem:l2004-finitary-central-automorphisms>
#proof[
  Suppose that $p,q in Gamma$ and, therefore, the center of the ring $R$
  coincides with $K e_(q p)$. It coincides also with the annihilator
  ${alpha in R | R alpha=alpha R=0}$ of $R$. Consequently, the restriction on
  $R^2$ of an arbitrary central automorphism $sigma$ of $R$ is identity. For
  every $j in Gamma_0$ the equalities
  $(sigma-1)(x e_(j^+,j))=sigma_j lr((x))e_(q p)$ $(x in K)$ defines an additive
  map $sigma_j:K arrow.r K$. It is clear that $(sigma+mu)_j=sigma_j+mu_j$.
  Conversely, for every collection of endomorphisms $sigma_j$ of $K$ with
  $j in Gamma_0$ the map
  $
    alpha arrow.r alpha+sum_(j in Gamma_0) sigma_j lr((a_(j^+,j)))e_(q p)
    quad (alpha=lr(‖a_(k m)‖) in R)
  $
  determines an automorphism of $R$ by [@bib:l2004-finitary-Kuzucuoglu2001,
  Lemma @lem:l2001-automorphisms-annihilator]. This completes the proof.
]
Consider hypercentral automorphisms of $G(R)$ and $Lambda(R)$. Let $m$ be a
positive integer and $m$th hypercenter does not coincide with $R$. According to
[@bib:l2004-finitary-Levchuk1990; @bib:l2004-finitary-Levchuk1992], an
automorphism is called hypercentral of height $<=m$ if it acts like the
identity, modulo the $m$th hypercenter. By [@bib:l2004-finitary-Levchuk1983;
@bib:l2004-finitary-Levchuk1987], in the conditions of Main Theorem on $K$ and
$Gamma$, every hypercentral automorphism of $Lambda(R)$ is a product of certain
inner and central automorphisms and the following automorphisms:
$
  x e_(k p) arrow.r (e_(k p)+a e_(q k))x quad (x in K),
  quad x e_(q t) arrow.r x(e_(q t)+b e_(t p)) quad (x in K),
$ <eq:l2004-finitary-height-two>
for $p triangle.l k<q$, $a(K ast K)=0$ and $p<t triangle.l q$, $(K ast K)b=0$,
respectively (the remaining elements $x e_(u v)$ are fixed); and
$
  x e_(k p) arrow.r (e_(k p)+c e_(q m))x, quad
  x e_(m p) arrow.r (e_(m p)+c e_(q k))x quad (x in K)
$
$
  "and" quad x e_(q t) arrow.r x(e_(q t)+d e_(s p)), quad
  x e_(q s) arrow.r x(e_(q s)+d e_(t p)) quad (x in K),
$ <eq:l2004-finitary-height-three>
for $p triangle.l k triangle.l m<q$, $2c=c(K ast K)=0$ and
$p<s triangle.l t triangle.l q$, $2d=(K ast K)d=0$, respectively. Also, the same
is true for the adjoint group $G(R)$, however, the main hypercentral
automorphisms of $G(R)$ act like an automorphism @eq:l2004-finitary-height-two,
modulo the center, @eq:l2004-finitary-height-three, modulo second hypercenter
and elements $a,b,c$ and $d$ of $K$ have additional restrictions.

The following lemma describes the lower central series. #lemma[
  The lower central series of $G(R)$ and of $Lambda(R)$ coincide with the series
  $R supset R^2 supset R^3 supset dots$. The intersection of all members of this
  series is generated by the sets $K e_(i j)$ $(j<i)$ with an infinite segment
  $[j,i]$. In particular, the equality $R=R^2$ is satisfied if and only if the
  chain $Gamma$ is dense.
] <lem:l2004-finitary-lower-central-series>
#proof[
  Straightforward. We note only that the inclusion $e_(i j) in R^2$ for
  $i,j in Gamma$ is satisfied if and only if there exists $k in Gamma$ such that
  $j<k<i$.
]
