#import "defs.typ": *
#import "diagrams/ideals.typ": ideal-segments, isomorphism-square
=== Certain Ideals and Isomorphisms
<sec:l2004-finitary-ideals-isomorphisms>
#source(5, printed: 173)
Let $G(R_S) tilde.eq G(R)$ or $Lambda(R_S) tilde.eq Lambda(R)$ for the ring
$R_S=NT(Omega, S)$ with some chain $Omega$ and associative ring $S$ with
identity. The adjoint group and the associated Lie ring of $R$ are generated by
subsets $K e_(i j)$, $i,j in Gamma$, $j<i$. The normal closure of $K e_(i j)$ in
$G(R)$ and the minimal Lie ideal in $Lambda(R)$ containing $K e_(i j)$ coincide
with
$
  N_(i j)=chevron.l K e_(u v) | v<u,i<=u,v<=j chevron.r quad (i,j in Gamma).
$
The analogous ideal of the ring $R_S$ for $k,m in Omega$ is denoted by
$N_(k m) lr((S))$. Its $psi$-image relative to any isomorphism $psi$ of $G(R_S)$
onto $G(R)$ or of $Lambda(R_S)$ onto $Lambda(R)$ is an ideal of the Lie ring
$Lambda(R)$. It shows #lemma[
  A subset of $R$ is a normal subgroup of the adjoint group $G(R)$ if and only
  if it is an ideal of the associated Lie ring $Lambda(R)$.
] <lem:l2004-finitary-normal-lie-correspondence>
#proof[
  It is proved in [@bib:l2004-finitary-Levchuk1987, Corollary
  @cor:l1987-rings-unital] even for arbitrary associative ring $K$ with $K=K^2$,
  in particular, for a ring $K$ with identity. (See also
  [@bib:l2004-finitary-Kuzucuoglu2000, § @sec:l2000-ideals-structural].)
]
Denote $tilde(Gamma)$, the set of initial segments of $Gamma$. Putting
$overline(T)=Gamma without T$ we set
$
  N_(V T)=chevron.l K e_(k m) | k in V,m in T,m<k chevron.r,
  quad N_T=N_(overline(T),T), quad V,T in tilde(Gamma).
$
#lemma[
  Let $R=NT(Gamma, K)$, $R_S=NT(Omega, S)$ and $psi$ be an isomorphism of
  $G(R_S)$ onto $G(R)$ or of $Lambda(R_S)$ onto $Lambda(R)$. Let
  $[N_T lr((S))]^psi=N_(T')$, $T in tilde(Omega)$, for some bijective map $'$ of
  $tilde(Omega)$ onto $tilde(Gamma)$. Then there exists an isomorphism or an
  anti-isomorphism $'$ of the chain $Omega$ onto $Gamma$ such that the ideal
  $[N_(i j) lr((S))]^psi$ coincides, respectively, with $N_(i' j')$ or
  $N_(j' i')$ for all $i,j in Omega$, $j<i$. If $psi$ is an isomorphism of the
  ring $R$, then $'$ is an isomorphism of the chain $Omega$.
] <lem:l2004-finitary-chain-reconstruction>
#proof[
  Choose arbitrary segments $V,T,L in tilde(Omega)$ with $V subset T subset L$.
  The $psi$-invariance of the inclusion
  $N_T lr((S)) supset N_V lr((S)) inter N_L lr((S))$ gives
  $N_(T') supset N_(V') inter N_(L')$ and, therefore, $V' subset T' subset L'$
  or $V' supset T' supset L'$, see Figure @fig:l2004-finitary-ideal-segments.

  The relation $subset$ for segments determines a linear ordering of
  $tilde(Omega)$ and $tilde(Gamma)$. Fixing two of the segments $V,T,L$ and
  varying the third one in $tilde(Omega)$, we easily deduce that $'$ is an
  isomorphism or an anti-isomorphism of the chain $tilde(Omega)$ onto
  $tilde(Gamma)$. If $psi$ is an isomorphism of the ring $R$, then the
  $psi$-invariance of relations $N_T lr((S))N_L lr((S))=0$ and
  $N_L lr((S))N_T lr((S))=N_T lr((S)) inter N_L lr((S))$ for $T subset L$ shows
  that $'$ is an isomorphism of the chain $tilde(Omega)$ onto $tilde(Gamma)$.
  The segment ${p}$ for $p in Gamma$ is the first element of $tilde(Gamma)$.
  Therefore there exists the first or last element $r$ of $Omega$ such that
  $[N_(r r) lr((S))]^psi=N_(p p)$ and we set $r'=p$. Similarly, we define
  inverse image of the last element of $Gamma$.

  Note that the centralizer $C(N_(overline(V),T))$ of $N_(overline(V),T)$ in $R$
  can be written in the form
  $
    C(N_(overline(V),T))=N_(overline(T),V), quad T,V in tilde(Gamma).
  $
  Let $T$ be the initial segment of $Gamma$ with the last element $i$ which is
  not first or last in $Gamma$. Then there exists the predecessor $L$ of $T$ in
  $tilde(Gamma)$ with $overline(L) inter T={i}$ and
  $
    N_(i i)=N_L+N_T=N_(overline(L),T)=C(N_L inter N_T),
    quad C(N_(i i))=N_L inter N_T=N_(overline(T),L).
  $
  #source(6, printed: 174)
  #figure(ideal-segments(), caption: [], kind: image)
  <fig:l2004-finitary-ideal-segments>
  Also, the intersection of inverse images of $overline(L)$ and $T$ in $Omega$
  consist of unique element $m$ and we set $m'=i$. Evidently, $'$ is an
  isomorphism or an anti-isomorphism of the chain $Omega$ onto $Gamma$ and
  $[N_(m m) lr((S))]^psi=N_(m' m')$ for all $m in Omega$. It remains to note
  that $N_(i j)=N_(i i) inter N_(j j)$ for $j<i$. The lemma is proved.
]
#lemma[
  Let $R_S=NT(Gamma, S)$ and $psi$ be an isomorphism of $G(R_S)$ onto $G(R)$ or
  of $Lambda(R_S)$ onto $Lambda(R)$. If $psi[N_(i j) lr((S))]=N_(i j)$ for all
  $i,j in Gamma$, $j<i$, then $psi$ is an isomorphism of the ring $R_S$ which is
  equal to a product of some $K$-ring isomorphism of $R_S$ onto $R$, triangular
  and central automorphisms of $R$.
] <lem:l2004-finitary-ideal-preserving-isomorphism>
#proof[
  The ideals $N_(i j)$ and $N_(i j) lr((S))$ with $j<i$ have zero multiplication
  and, therefore, $psi$ is additive on $N_(i j) lr((S))$. Consequently, $psi$
  preserves the relations
  $
    x e_(i j) circle y e_(i j)=x e_(i j)+y e_(i j)=(x+y)e_(i j)
    quad (i,j in Gamma,x,y in S)
  $
  of $R_S$. Choose arbitrary matrices $alpha in N_(i j) lr((S))$ and
  $beta in N_(k m) lr((S))$, $m<k$. Evidently, the annihilator of the
  intersection $N_(i j) inter N_(k m)$ in $R$ contains $N_(i j)$ and $N_(k m)$;
  the same is true for $R_S$. Therefore the commutator $[alpha,beta]$ in the
  adjoint group $G(R_S)$ coincides with the Lie product $alpha ast beta$. Also,
  they coincide with $alpha beta$ for $k<=i$ (because we have $N_(k m)N_(i j)=0$
  in $R$ and the same in $R_S$) and with $-beta alpha$ for $i<=k$. It follows
  the equality $alpha^psi beta^psi=(alpha beta)^psi$, in particular,
  $(x e_(i j))^psi(y e_(k m))^psi=[(x e_(i j))(y e_(k m))]^psi$. Since $psi$
  preserves all basic relations between elementary matrices of the ring $R_S$,
  it is an isomorphism of $R_S$ onto the ring $R$.

  Let $Q_(i j)$ be the ideal $R ast N_(i j)$ of the ring $R$; similarly the
  ideal $Q_(i j)(S)$ of $R_S$ is defined. Since $psi[Q_(i j)(S)]=Q_(i j)$, the
  equalities $(x e_(i j))^psi=x^(sigma_(i j))e_(i j)$ $("mod" Q_(i j))$,
  $x in S$, define some isomorphisms $sigma_(i j)$ $(i,j in Gamma,j<i)$ of $S^+$
  onto $K^+$. The $psi$-invariance of relation
  $x y e_(i k)=(x e_(i j))(y e_(j k))$ $("mod" Q_(i k))$ of $R_S$ implies that
  $(x y)^(sigma_(i k))=x^(sigma_(i j))y^(sigma_(j k))$. In particular,
  $K=K^(sigma_(i k))=d_(i j)K=K d_(j k)$ for $d_(i j)=(1_S)^(sigma_(i j))$
  $(j<i)$ and hence all elements $d_(i j)$ of $K$ are invertible. Fixing
  $m in Gamma$ we may assume, up to multiplication of $psi$ by a diagonal
  automorphism of $R$, that $d_(i m)=d_(m k)=1_K$. It follows that all elements
  $d_(i j)$ coincide with $1_K$. Therefore all maps $sigma_(i j)$ coincide
  between them, and #source(7, printed: 175)also $sigma_(i j)$ is an isomorphism
  of the ring $S$ which induces a $K$-ring isomorphism $tau$ of the ring $R_S$.
  Then $tau^(-1)psi$ is an automorphism of the ring $R$ having the identity
  restriction on every ideal $N_(i j)$, modulo $Q_(i j)$. By (e) in the proof of
  Theorem @th:l1987-rings-automorphisms [@bib:l2004-finitary-Levchuk1987] such
  automorphism is a product of some locally inner and central automorphisms of
  $R$.
]
We now need a description of maximal Abelian ideals of $Lambda(R)$. Since
$C(N_T)=C(N_(overline(T),T))=N_T$, the ideal $N_T$ of $R$ for any
$T in tilde(Gamma)$ (in particular, $N_(i j)$ for $j triangle.l i$) is maximal
Abelian.

Let $(K,K)$ be the ring of all $1 times 2$ matrices over $K$ with the
multiplication $(a,b)(c,d)=(b c,d a)$ and usual addition. (This ring is simple
for any simple ring $K$.) Every maximal commutative subset of the ring $(K,K)$,
different from $(K,0)$ and $(0,K)$, can be written in the form
${(x,x^nu) | x in F}$ for some nonzero additive subgroup $F$ of $K$ and an
isomorphism $nu$ of $F$ into $K^+$ with $x^nu y=y^nu x$ $(x,y in F)$. If
$p,q in Gamma$, then
$
  C(N_(i i))+{x e_(i p)+x^nu e_(q i) | x in F}, quad p<i<q,
$ <eq:l2004-finitary-maximal-abelian-ring>
is a maximal abelian ideal of $R$ by [@bib:l2004-finitary-Levchuk1976, Lemma
@lem:l1976-domain-abelian]. Analogously, if maps $lambda$, $mu$ and an
isomorphism $nu$ of an additive subgroup $F$ of $K$ into $K^+$ satisfy condition
$y^nu x z+z^nu x y=0$, $x in K$, $y,z in F$ (in particular, $2K=0$), then
$
  C(N_(m k))+{y e_(m p)+(y^lambda+x z)e_(k p)
    +(y^mu-z^nu x)e_(q k)+y^nu e_(q m) | x in K,y,z in F}
$ <eq:l2004-finitary-exceptional-abelian-lie>
is an Abelian ideal of the Lie ring $Lambda(R)$ for
$p triangle.l k triangle.l m triangle.l q$ by [@bib:l2004-finitary-Levchuk1976,
Lemma @lem:l1976-domain-lie-exceptional].

#lemma[
  Let $K$ be a ring with no zero-divisors. Then every maximal Abelian ideal of
  the ring $R$ coincides with $N_T$ for $T in tilde(Gamma)$ or with
  @eq:l2004-finitary-maximal-abelian-ring. A maximal Abelian ideal of the Lie
  ring $Lambda(R)$ is either an ideal of the ring $R$ or $|Gamma|>3$, $2K=0$ and
  it has the form @eq:l2004-finitary-exceptional-abelian-lie.
] <lem:l2004-finitary-maximal-abelian-classification>
#proof[
  It had been shown in [@bib:l2004-finitary-Levchuk1976, §
  @sec:l1976-maximal-abelian] and [@bib:l2004-finitary-Levchuk1987, Theorem
  @th:l1987-rings-maximal-abelian].
]
#corollary[
  The ideals $N_T$ $(T in tilde(Gamma))$ of the ring $R$ exhaust all maximal
  Abelian ideals of $R$ with zero multiplication.
] <cor:l2004-finitary-zero-product-maximal-ideals>
#lemma[
  Let $R=NT(Gamma, K)$, $R_S=NT(Omega, S)$ and $psi$ be an isomorphism of
  $G(R_S)$ onto $G(R)$ (or of $Lambda(R_S)$ onto $Lambda(R)$). If $K$ is a ring
  with no zero-divisors and $|Gamma|>4$, then $[N_T lr((S))]^psi=N_(T')^chi$
  $(T in tilde(Omega))$ for some bijective map $'$ of $tilde(Omega)$ onto
  $tilde(Gamma)$ and hypercentral automorphism $chi$ of height $<=3$ of $G(R)$
  (resp. $Lambda(R)$).
] <lem:l2004-finitary-normalization>
#proof[
  If the center of $R$ is zero, then $[N_T lr((S))]^psi=N_(T')$
  $(T in tilde(Omega))$ for some bijective map
  $':tilde(Omega) arrow.r tilde(Gamma)$, by Lemmas
  @lem:l2004-finitary-hypercenters and
  @lem:l2004-finitary-maximal-abelian-classification. Therefore we may assume
  that the center of $R$ is nonzero and hence the chain $Gamma$ contains first
  and last elements by Lemma @lem:l2004-finitary-hypercenters; of course, the
  same is true for the ring $R_S$.

  #source(8, printed: 176)The $m$th hypercenter of $R$ is denoted by $Z_m$. Let
  ${r,t}$ be the subset of $Omega$ consisting of the first and last elements of
  $Omega$. Then $[N_(r r) lr((S))+N_(t t) lr((S))]^psi=N_(p p)+N_(q q)$ because
  the Lie ideal $N_(p p)+N_(q q)$ of $R$ (similarly,
  $N_(r r) lr((S))+N_(t t) lr((S))$ of $R_S$) which is generated by two maximal
  Abelian ideals with the intersection coinciding with the center is unique, by
  Lemma @lem:l2004-finitary-maximal-abelian-classification. Putting
  $B=[N_(r r) lr((S))]^psi$ we may assume that every $(i,p)$-projection of $B$
  $(i in Gamma,p<i)$ is nonzero. By Lemma
  @lem:l2004-finitary-maximal-abelian-classification, it follows the equality
  $B=N_(p p)$, modulo $Z_3 inter (N_(p p)+N_(q q))$. If $N_(p p)+Z_2$ does not
  contain $B$, then $Z_3!=Z_2$ and $B$ has the form
  @eq:l2004-finitary-exceptional-abelian-lie with an isomorphism $nu$ of an
  additive subgroup $F$ of $K$ into $K^+$ and $p triangle.l k triangle.l m<q$.
  Since $psi$ induces an isomorphism of the quotient-ring $R_S/R_S^2$ and
  $|Gamma|>4$, we get $F=K$, $y^nu=c y$ $(y in K)$ and $2c=c(K ast K)=0$ for
  $c=1^nu$. Therefore hypercentral automorphism @eq:l2004-finitary-height-three
  of $Lambda(R)$ is determined. If $psi$ is an isomorphism of $G(R)$, then the
  additional condition $c(x^2-x)(y^2-y)=0$ $(x,y in K)$ is satisfied;
  conversely, for such element of $K$ the map
  $
    x e_(k p) arrow.r (e_(k p)+c e_(q m))x, quad
    x e_(m k) arrow.r x e_(m k)+c(x^2-x)e_(q k),
  $
  $
    x e_(m p) arrow.r x e_(m p)+c x e_(q k)+c x^2 e_(q p) quad (x in K)
  $
  is a hypercentral automorphism of $G(R)$ [@bib:l2004-finitary-Levchuk1983, §
  @sec:l1983-elementary]. Up to multiplication of $psi$ by a hypercentral
  automorphism of height $<=3$, we obtain $B=N_(p p)$, modulo $Z_2$. Also, up to
  multiplication of $psi$ by a hypercentral automorphism of height $<=2$ (of the
  form @eq:l2004-finitary-height-two of $Lambda(R)$), we obtain
  $[N_(r r) lr((S))]^psi=N_(p p)$ and similarly,
  $[N_(t t) lr((S))]^psi=N_(q q)$. Consequently, by Lemma
  @lem:l2004-finitary-maximal-abelian-classification there exist some bijective
  map $'$ of $tilde(Omega)$ onto $tilde(Gamma)$ such that the equality
  $[N_T lr((S))]^psi=N_(T')$ are satisfied for all $T in tilde(Omega)$.
]
#remark[
  Every chain $Omega$ is anti-isomorphic to the ‘opposite’ chain
  $Omega^((upright("op")))$, i.e. the set $Omega$ by the order relation which is
  opposite to the one in the chain $Omega$. Denote by $S^((upright("op")))$, the
  opposite ring of $S$, see Exercise 17 in [@bib:l2004-finitary-Hungerford1974,
  p. 122]. It is clear that the map $x e_(i j) arrow.r -x e_(j i)$
  $(x in S,i,j in Omega,j<i)$ admits extension to an isomorphism of $G(R_S)$
  onto $G[NT(Omega^((upright("op"))), S^((upright("op"))))]$ and to an
  isomorphism of $Lambda(R_S)$ onto
  $Lambda[NT(Omega^((upright("op"))), S^((upright("op"))))]$. This isomorphism
  is said to be opposite. Set $(Omega_1,S_1)=(Omega,S)$ for
  $Omega tilde.eq Gamma$ and otherwise
  $(Omega_1,S_1)=(Omega^((upright("op"))),S^((upright("op"))))$. An isomorphism
  of $G(R)$ (similarly, $Lambda(R)$) is said to be standard if it is a product
  of some hypercentral of height $<=3$ and triangular automorphisms and an
  idempotent $S_1$-ring isomorphism of $G(R)$ (resp. $Lambda(R)$), an
  $Omega_1$-chain isomorphism of the ring $NT(Gamma, S_1)$ and, finally, an
  isomorphism $tau$ of $G[NT(Omega_1, S_1)]$ onto $G(R_S)$ (resp.
  $Lambda[NT(Omega_1, S_1)]$ onto $Lambda(R_S)$), which is the identity map for
  $Omega tilde.eq Gamma$ and otherwise it is the opposite isomorphism.
] <rem:l2004-finitary-standard-isomorphism>
#example[
  Let $Gamma=[a,b)$ and $Omega=(c,d]$ be nonempty subchains of the usual chain
  of rational or real numbers. Evidently that the chains $Gamma$ and $Omega$ are
  anti-isomorphic but not isomorphic. Therefore there exists a standard
  isomorphism between the adjoint groups $G(R)$ and $G(R_S)$ or between Lie
  rings $Lambda(R)$ and $Lambda(R_S)$ if and only if
  $K tilde.eq S^((upright("op")))$.
] <exm:l2004-finitary-opposite-chains>
We now consider the case of a ring $K$ with no zero-divisors in the main
theorem.
#source(9, printed: 177)
#theorem[
  Let $R=NT(Gamma, K)$, $R_S=NT(Omega, S)$, $K$ be a ring with no zero-divisors
  and $|Gamma|>4$. If there exists an isomorphism $psi$ of $G(R)$ onto $G(R_S)$
  or of $Lambda(R)$ onto $Lambda(R_S)$, then $Gamma tilde.eq Omega$,
  $K tilde.eq S$ or $Gamma tilde.eq Omega^((upright("op")))$,
  $K tilde.eq S^((upright("op")))$ and the isomorphism $psi$ is standard.
] <th:l2004-finitary-domain-isomorphisms>
#proof[
  Assume that there exists an isomorphism $psi$ of $G(R)$ onto $G(R_S)$ (resp.
  $Lambda(R)$ onto $Lambda(R_S)$) and therefore, $Gamma tilde.eq Omega$ or
  $Gamma tilde.eq Omega^((upright("op")))$ by Lemmas
  @lem:l2004-finitary-normalization and
  @lem:l2004-finitary-chain-reconstruction. Let $(Omega_1,S_1)$ and $tau$ be as
  in Remark @rem:l2004-finitary-standard-isomorphism, so
  $Gamma tilde.eq Omega_1$. By Lemmas @lem:l2004-finitary-normalization and
  @lem:l2004-finitary-chain-reconstruction, there exists $Omega_1$-chain
  isomorphism $sigma$ of the ring $NT(Gamma, S_1)$ such that the ideal
  $sigma tau psi^(-1)[N_(i j)(S_1)]$ $(i,j in Gamma,j<i)$ of $Lambda(R)$
  coincides with the image of $N_(i j)$ relative to some hypercentral
  automorphism of $G(R)$ (resp. $Lambda(R)$). By Lemma
  @lem:l2004-finitary-ideal-preserving-isomorphism,
  $sigma tau psi^(-1)=theta^(-1)lambda^(-1)chi^(-1)$ for a hypercentral
  automorphism $chi$ of height $<=3$, a triangular automorphism $lambda$ and a
  $S_1$-ring isomorphism $theta$ of $G(R)$ (resp. $Lambda(R)$). To complete the
  proof it remains to note that the following diagram is commutative:

  #isomorphism-square()
]
