#import "defs.typ": *
=== The Proof of the Main Theorem
<sec:l2004-finitary-main-proof>
Firstly, in this section we will prove the following theorem. #theorem[
  Let $R=NT(Gamma, K)$, $R_S=NT(Omega, S)$ and $Gamma$ be a finite chain of
  order $>4$. The adjoint groups $G(R)$ and $G(R_S)$ or associated Lie rings
  $Lambda(R)$ and $Lambda(R_S)$ are isomorphic if and only if rings $K$ and $S$
  are idempotent isomorphic and $|Omega|=|Gamma|$; every isomorphism between
  them is standard.
] <th:l2004-finitary-finite-chain-isomorphisms>
We need the following characterization of the one-sided Peirce decompositions.
#lemma[
  Let $K$ be an associative ring with identity. Let $K=A_1+A_2=B_1+B_2$ and
  $A_i B_i=0$ for some subsets $A_i,B_i$ of $K$, $i=1,2$. Then there exists an
  idempotent $f$ of $K$ such that $A_1=K f$, $A_2=K(1-f)$, $B_1=(1-f)K$ and
  $B_2=f K$. If $K f=f K$, then an idempotent $f$ is in the center of $K$.
] <lem:l2004-finitary-peirce-decomposition>
#proof(head: [Proof (see [@bib:l2004-finitary-Levchuk1983, Lemma
  @lem:l1983-peirce-decomposition]).])[
  By hypothesis, $1=f_1+f_2=g_1+g_2$ for some elements $f_i in A_i$,
  $g_i in B_i$. They satisfy the equations
  $
    f_1=f_1(g_1+g_2)=f_1 g_2=(f_1+f_2)g_2=g_2, quad f_2=g_1,
  $
  $
    f_1-f_1^2=f_1(1-f_1)=f_1 f_2=f_1 g_1=0.
  $
  Consequently, $f_1$ is an idempotent and
  $A_i=A_i lr((g_1+g_2))=A_i lr((1-g_i))=A_i f_i$ for $i=1,2$. Since the sum
  $K f_1+K(1-f_1)=K$ is direct [@bib:l2004-finitary-Hahn1984, Sect. 3.7], we get
  $A_i=K f_i$. Similarly, $B_i=(1-f_i)K$, $i=1,2$. Thus, the first assertion of
  the #source(
    10,
    printed: 178,
  )lemma holds for $f=f_1$. Let $f K=K f$ and $x in K$. Then $y f=f x$,
  $x f=f z$ for some elements $y,z in K$. Hence, $f x=(y f)f=f x f=f(f z)=x f$,
  i.e., $f$ is a central idempotent. This proves the lemma.
]
#lemma[
  Let $Gamma$ be a finite chain ${1,2,dots,n}$ and $'$ be an anti-automorphism
  of $Gamma$. If $1<=j<n$, $1<i<=n$, then $N_(j',j)=C(R^j)$, the ideal $N_(i j)$
  coincides with the intersection of the left annihilator of $R^j$ and the right
  annihilator of $R^(n-i)$ in $R$ and also
  $
    C(R^j)=C(R^j) inter R^2+C(R^(j-1))+N_(j+1,j)+N_(j',j'-1),
    quad n-j<=j<n.
  $ <eq:l2004-finitary-centralizer-decomposition>
] <lem:l2004-finitary-finite-centralizers>
#proof[
  The power $R^j$ is additively generated by the sets $K e_(u v)$ with $u-v>=j$.
  It is easy to see that the left annihilator of $R^j$ and the right annihilator
  of $R^(n-i)$ in $R$ coincide with $N_(2 j)$ and $N_(i,n-1)$, respectively. It
  is clear that $N_(i j)=N_(i,n-1) inter N_(2 j)$. The formula of the
  centralizer $C(N_(overline(V),T))=N_(overline(T),V)$ from Section
  @sec:l2004-finitary-ideals-isomorphisms gives the equality
  $C(N_(i j))=N_(j+1,i-1)$. Evidently, the map $m arrow.r n+1-m$, $1<=m<=n$, is
  the unique anti-automorphism of the chain $Gamma$. It follows the equalities
  $N_(j',j)=C(N_(j+1,n-j))=C(R^j)$ and
  @eq:l2004-finitary-centralizer-decomposition. The lemma is proved.
]
#proof(head: [Proof of Theorem @th:l2004-finitary-finite-chain-isomorphisms.])[
  Let $R$ be a ring $NT(Gamma, K)$ with a finite chain $Gamma$ and
  $R_S=NT(Omega, S)$. If $G(R) tilde.eq G(R_S)$ or
  $Lambda(R_S) tilde.eq Lambda(R)$, then $|Omega|=|Gamma|$ by Lemma
  @lem:l2004-finitary-lower-central-series; for a finite chain $Gamma$ it means
  that $Omega tilde.eq Gamma$. We now may assume (with using a chain
  isomorphism) that $Omega=Gamma$ and $Gamma$ coincides with the usual chain
  ${1,2,dots,n}$. In this case we may write $R=NT(n, K)$ and $R_S=NT(n, S)$, as
  usual.

  Investigate arbitrary isomorphism $psi$ of $G(R_S)$ onto $G(R)$ or of
  $Lambda(R_S)$ onto $Lambda(R)$. Let $n>4$ and $H^((i))=N_(i+1,i) lr((S))^psi$,
  $1<=i<n$. By @eq:l2004-finitary-centralizer-decomposition, the sum of
  $(i+1,i)$-projections of $H^((i))$ and $H^((n-i))$ coincides with $K$. If
  $n=2m$, then $m'=m+1$ and by Lemma @lem:l2004-finitary-finite-centralizers,
  $H^((m))=[C(R_S^m)]^psi=C(R^m)=N_(m+1,m)$. Choose arbitrary $m$ with
  $n-m<m<n$. Since $H^((i))$ is an (maximal) abelian ideal of $Lambda(R)$, we
  have $H^((i)) ast (H^((i)) inter K e_(m 1))=0$ for $i=m,n-m$. Denote by
  $H_(u v)^((i))$, the $(u,v)$-projection of $H^((i))$, i.e., the set of all
  $(u,v)$-coefficients of matrices in $H^((i))$. It is not difficult to show
  that $H_(m',m'-1)^((i))e_(m 1) subset H^((i))$. Therefore we get
  $
    H_(m+1,m)^((i))H_(m',m'-1)^((i))=0, quad
    K=H_(i+1,i)^((m))+H_(i+1,i)^((n-m)), quad i=m,n-m.
  $
  Consequently, by Lemma @lem:l2004-finitary-peirce-decomposition,
  $H_(m+1,m)^((i))=K f_i$ and $H_(m',m'-1)^((i))=f_(n-i)K$ $(i=m,n-m)$ for an
  idempotent $f_m$ of $K$ and $f_(n-m)=1_K-f_m$. Using that $H^((i))$ is an
  Abelian ideal of $Lambda(R)$, for $m>n-m+1 (=m')$ we get
  $
    H^((i)) inter K e_(m 1)=f_(n-i)K e_(m 1), quad
    H^((i)) inter K e_(n m')=K f_i e_(n m'),
  $
  and hence $K f_m K subset.eq f_m K$; similarly, $K f_m K subset.eq K f_m$.
  Therefore, $K f_m=f_m K$ and $f_m$ is a central idempotent by Lemma
  @lem:l2004-finitary-peirce-decomposition. Since the Lie product
  $H^((m+1)) ast H^((n-m))$ is #source(11, printed: 179)congruent to zero modulo
  $R^3$ for $n-m<m<n-1$, we have $f_m lr((1-f_(m+1)))=f_(m+1)(1-f_m)=0$ and
  $f_m=f_(m+1)$. Consequently, we have proved the existence of an idempotent $f$
  in the center of the ring $K$ such that
  $
    psi(x e_(i+1,i))=mu_i lr((x))e_(i+1,i)
    -nu_i lr((x))e_(i',i'-1) quad ("mod" R^2), quad x in S,1<=i<n,
  $
  for some homomorphisms $mu_i:S^+ arrow.r f K$ and $nu_i:S^+ arrow.r (1_K-f)K$
  of the additive group $S^+$. Also we get
  $
    (N_(i+1,i) lr((S)))^psi=H^((i))=f N_(i+1,i)+(1-f)N_(i',i'-1),
    quad i=2,3,dots,n-2.
  $
  For $i=1$ and $i=n-1$ these equations are also valid modulo $R^2$.

  Considering the product $H^i ast H^(i-1)$ $(1<i<n)$, we obtain, modulo $R^3$,
  $
    f K e_(i+1,i-1)+(1_K-f)K e_(i'+1,i'-1)
    =psi(e_(i+1,i)) ast H^((i-1))=H^((i)) ast psi(e_(i,i-1))
  $
  because the commutation $[, ]$ in the adjoint group of $R$ and the Lie
  multiplication $ast$ of $R$ coincides, modulo $R^3$. Now, it is easy to verify
  that the elements of the form $mu_i lr((1_S))+nu_j lr((1_S))$ are invertible
  in the ring $K$. Therefore, up to multiplication by a diagonal automorphism of
  the ring $R$, the isomorphism $psi$ satisfies the additional condition
  $psi(e_(i+1,i))=f e_(i+1,i)-(1_K-f)e_(i',i'-1)$, modulo $R^2$, for $1<=i<n$
  and $nu_1=nu_2=dots=nu_(n-1)$. Since $(R_S^2)^psi=R^2$ and
  $f K inter (1_K-f)K=0$, the equality $mu_1 lr((a))+nu_1 lr((a))=0$ $(a in S)$
  gives $a=0$. Therefore $mu_1+nu_1$ is an isomorphism of the additive group
  $S^+$ onto $K^+$.

  It is easy to verify that for any $g$-isomorphism $sigma$ of the ring $S$ onto
  $K$ with an idempotent $g$ in the center of $S$ the map $sigma^(-1)$ is an
  $g^sigma$-isomorphism of the ring $K$ onto $S$. Let $theta=(mu_1+nu_1)^(-1)$
  and $f^theta=g$. Since $f K inter (1-f)K=0$, we have
  $f=theta^(-1)(g)=mu_1 lr((g))+nu_1 lr((g))=mu_1 lr((g))$ and $nu_1 lr((g))=0$.
  Therefore,
  $
    theta^(-1)(g^2)=mu_1 lr((g))^2+nu_1 lr((g))^2=f^2=f
    =mu_1 lr((g))=theta^(-1)(g),
  $
  $
    theta^(-1)(g S)=mu_1 lr((g S))+nu_1 lr((g S))=mu_1 lr((g))f K
    =f^2 K=K f^2=mu_1 lr((S g))=theta^(-1)(S g).
  $
  So $g$ is an idempotent in the center of the ring $S$, by Lemma
  @lem:l2004-finitary-peirce-decomposition, and $theta^(-1)$ is an
  $g$-isomorphism of the ring $S$ onto $K$. Consequently, $theta$ is an
  $f$-isomorphism of the ring $K$ onto $S$.

  Denote by $tau$, the idempotent $S$-ring isomorphism
  @eq:l2004-finitary-idempotent-isomorphism of $G(R)$ (or $Lambda(R)$, according
  to the choice of $psi$), which is induced by the $f$-isomorphism $theta$. Let
  $pi=psi tau$. Then $pi in Aut G(R)$ (resp. $pi in Aut Lambda(R)$) so for all
  $y in K$ and $i>j$ we get
  $
    pi(y e_(i j)) & =psi[(y f)^theta e_(i j)-(y-y f)^theta e_(j' i')] \
                  & =lr([(y f)^theta g])^(theta^(-1))e_(i j)
                    -lr([(y f)^theta dot (1-g)])^(theta^(-1))e_(j' i') \
                  & quad -lr([(y-y f)^theta g])^(theta^(-1))e_(j' i')
                    +lr([(y-y f)^theta dot (1-g)])^(theta^(-1))e_(i j) \
                  & =[f^2+(1-f)^2]y e_(i j) \
                  & quad -[(1-f)y f+(y-y f)f]e_(j' i') \
                  & =y e_(i j) quad ("mod" R^2).
  $
  #source(12, printed: 180)Thus, the automorphism $pi$ acts like the identity,
  modulo $R^2$; by Lemma @lem:l1983-first-layer-kernel of
  [@bib:l2004-finitary-Levchuk1983] it is a product of some hypercentral of
  height $<=3$ and inner automorphisms. Therefore $psi$ is a product of some
  idempotent $K$-ring isomorphism of $G(R_S)$ (resp. $Lambda(R_S)$),
  hypercentral and triangular automorphisms of $G(R_S)$ (resp. $Lambda(R_S)$),
  i.e., $psi$ is a standard isomorphism. Theorem
  @th:l2004-finitary-finite-chain-isomorphisms is proved.
]
#remark[
  In particular case of $Omega=Gamma$ and $S=K$ Theorem
  @th:l2004-finitary-domain-isomorphisms and Theorem
  @th:l2004-finitary-finite-chain-isomorphisms give the description of
  $Aut G(R)$ and $Aut Lambda(R)$. For $n=|Gamma|=3,4$ the statement of Theorem
  @th:l2004-finitary-finite-chain-isomorphisms is not true. In fact, choose a
  commutative ring $K$, a matrix $lr(‖a_(i j)‖) in SL(2, K)$ with
  $2a_(i 1)a_(i 2)=0$ $(i=1,2)$ at $n=4$ and the anti-automorphism
  $':j arrow.r n+1-j$ of $Gamma$. Then the map
  $
    x e_(2 1) arrow.r x(a_(1 1)e_(2 1)+a_(1 2)e_(1' 2')),
    quad x e_(1' 2') arrow.r x(a_(2 1)e_(2 1)+a_(2 2)e_(1' 2')),
    quad x in K,
  $
  in generating subsets $K e_(j+1,j)$ of the Lie ring $Lambda(R)$ at $n=3,4$
  (for $n=4$ it is the identity map of the remaining subset $K e_(3 2)$) defines
  its an isomorphism. Evidently, for standardness of this isomorphism it is
  necessary that the matrix $lr(‖a_(i j)‖)$ (and the group $SL(2, K)$) is
  generated by transvections, see [@bib:l2004-finitary-Levchuk1983, §
  @sec:l1983-small-ranks].
] <rem:l2004-finitary-small-ranks>
#proof(head: [Proof of the Main Theorem.])[
  Theorems @th:l2004-finitary-domain-isomorphisms and
  @th:l2004-finitary-finite-chain-isomorphisms prove statements (ii) and (iii)
  of the main theorem. Consider arbitrary isomorphism $psi$ of the ring $R_S$
  onto $R$. Up to multiplication of $psi$ by a chain isomorphism, we may assume,
  by Corollary @cor:l2004-finitary-zero-product-maximal-ideals, Lemma
  @lem:l2004-finitary-chain-reconstruction (for a finite chain) Lemma
  @lem:l2004-finitary-finite-centralizers, that $Gamma=Omega$ and
  $psi[N_(i j) lr((S))]=N_(i j)$ for all $i,j in Gamma$, $j<i$. Then, by Lemma
  @lem:l2004-finitary-ideal-preserving-isomorphism, $psi$ is a product of a
  $K$-ring isomorphism of $R_S$, triangular and central automorphisms of $R$.
  This completes the proof of the main theorem.
]
