#import "../../main-defs.typ": *
#import "../../statements.typ": *
#import "defs.typ": *
#import "diagrams/staircases.typ": staircases

=== Ideals of the Ring $R_n lr((K,J))$ <sec:l2013-ideals-ring-ideals>

Throughout this paper the coefficient ring $K$ denotes an associative
commutative ring with identity.

Ideals of the ring $R_n lr((K,J))$ are described in
[@bib:l2013-ideals-Kuzucuoglu2000] for some specific ideal $J$ of $K$. The
description uses the following pair of sets of matrices positions:
$
  Lc={(i_1,j_1),(i_2,j_2),dots,(i_r,j_r)}, quad r>=1,
  quad 1<=j_1<j_2<dots<j_r<=n, quad 1<=i_1<i_2<dots<i_r<=n;
$ <eq:l2013-ideals-primary-corners>
$
  Lc'={(1,j_r),(k_1,m_1),(k_2,m_2),dots,(k_q,m_q),(i_1,n)}, quad q>=0,
  quad j_r<m_1<m_2<dots<m_q<=n, quad 1<=k_1<k_2<dots<k_q<i_1.
$ <eq:l2013-ideals-secondary-corners>

We refer to the ordered pair $(Lc,Lc')$ as a “set of corners of degree $n$”.

Denote by $pi_(k m)$ the canonical projection (see
[@bib:l2013-ideals-Hungerford1974]) on the ring of all $n times n$ matrices over
$K$ and by $e_(i j)$ the matrix unit in which the $(i,j)$-coefficient
$pi_(i j) lr((e_(i j)))$ is equal #source(3, printed: "1250140-3")to 1 and
others are zero. For any additive subgroup $F$ of $K$ we denote by
$N_(i j) lr((F))$ (respectively, by $Q_(i j) lr((F))$) the additive group of
$R_n lr((K,J))$ generated by sets $F e_(k m)$ for all $(k,m)>=(i,j)$
(respectively, $(k,m)>(i,j)$) where we suppose $(i,j)<(k,m)$, if $i<=k$, $m<=j$
and $(i,j)!=(k,m)$.

Also, we require the following concept.

#definition(title: [@bib:l2013-ideals-Kuzucuoglu2000, Definition~2.1])[
  An ideal $J$ of a commutative ring $K$ is called a strongly maximal ideal if
  for any $J$-submodule $T$ of $K$ every ideal of $K$, which is between a
  $J$-submodule $T$ and $J T$, is equal to $T$ or $J T$.
] <def:l2013-ideals-strongly-maximal>

Let $J$ be a strongly maximal ideal of $K$. In according to
[@bib:l2013-ideals-Kuzucuoglu2000, Theorem~2.2], every ideal of the ring
$R_n lr((K,J))$ is generated by a unique $T$-boundary
$A subset.eq R_n lr((K,J))$ which depends from a $J$-submodule $T$ of $K$ and
$(Lc,Lc')$ such that
$
  J B subset.eq A subset.eq B,
  quad B=sum_((i,j) in Lc) T e_(i j)+sum_((k,m) in Lc') (J T)e_(k m).
$
Moreover, $pi_(i j) lr((A))$ generates the ideal of $K$ coinciding with $J T$
for the free secondary corners and with $T$ at $(n,1)!=(i,j) in Lc$; if
$Lc={(n,1)}$, then $pi_(n 1) lr((A))=T$.

Regard a $n times n$ matrix as a square array of $n^2$ points $(i,j)$ (matrix
positions). Associating “staircases” with $Lc$ and $Lc'$ we can compare with the
ideal generated by the $T$-boundary $A$ the matrix in
Fig.~@fig:l2013-ideals-staircases.

By [@bib:l2013-ideals-Kuzucuoglu2000, Theorem~2.2], every ideal of the ring
$R_n lr((K,J))$ coincides with the ideal $I(A)$ which is generated by certain
$T$-boundary $A=A(T;Lc,Lc')$:
$
  I(A)=A+sum_((i,j) in Lc) Q_(i j) lr((T))+sum_((k,m) in Lc') Q_(k m) lr((J T))
  +N_(i_1 n) lr((T J))+N_(1 j_r) lr((J T))+N_(1 n) lr((J T J)).
$

#figure(
  staircases(),
  caption: [#counted("fig", n => [Figure #n.])],
  supplement: none,
  numbering: none,
)
<fig:l2013-ideals-staircases>

#source(4, printed: "1250140-4")In general case elements in corners $(Lc,Lc')$
of matrices from an ideal $I(A)$ can be depended between them, see
Fig.~@fig:l2013-ideals-staircases. See also [@bib:l2013-ideals-Kuzucuoglu2001].

We now distinguish coordinate ideals of the ring $R_n lr((K,J))$. An ideal is
called coordinate if it is a direct sum $I=sum_(i,j) I_(i j)e_(i j)$, where
every $I_(i j)$ is an ideal of $K$.#ed-note[The original asserts this
  description for all $D$-invariant ideals. For
  $K=FF_3[epsilon] slash (epsilon^2)$, $J=(epsilon)$ and $n=2$, the ideal
  $H=FF_3 epsilon I_2+FF_3 epsilon e_(2 1)$ is $D$-invariant but its diagonal
  entries are linked, so it is not coordinate. The general description in
  [@bib:l2013-ideals-Kuzucuoglu2000, Theorem~2.2] permits dependent boundary
  entries. The printed closed formula also overcounts coordinate ideals: for
  $n=3$ and $s=2$ it gives 36, whereas the staircase count gives 34.]

For a coordinate ideal the entries of its $T$-boundary are independent. In the
description of [@bib:l2013-ideals-Kuzucuoglu2000, Theorem~2.2],
$T=pi_(n 1) lr((I))$ is an ideal of $K$. At a primary corner the coefficient
ideal is already an ideal of $K$, so the statement that it generates $T$ means
that it equals $T$. Similarly the coefficient ideal at a free secondary corner,
outside the primary staircase, is $J T$. The fixed boundary strips have
coefficients $J T$ wherever the primary staircase does not already give $T$.
Thus the elements of matrices from $I$ independently run $T$ below or on the
staircase $Lc$ and $J T$ below or on the staircase $Lc'$. Consequently, $I$
coincides with the ideal
$
  I(T;Lc,Lc')=sum_((i,j) in Lc) N_(i j) lr((T))
  +sum_((k,m) in Lc') N_(k m) lr((J T))
  +N_(1 n) lr((J T J)).
$ <eq:l2013-ideals-coordinate-ideal>



Thus, the following theorem is satisfied.

#theorem[
  Let $K$ be a commutative ring coinciding with its ideal which is generated by
  the set $1-K^*$ and let $J$ be a strongly maximal ideal of $K$. Then every
  nonzero coordinate ideal of the ring $R_n lr((K,J))$ coincides with an ideal
  @eq:l2013-ideals-coordinate-ideal for uniquely determined an ideal $T$ of $K$
  and a canonical set of corners $(Lc,Lc')$ of degree $n$; when $J T=J^2 T$,
  take $q=0$, and when $T=J T$, take $Lc={(1,n)}$.
] <th:l2013-ideals-diagonal-invariant-description>

By the proved theorem, the number of all coordinate ideals in the ring
$R_n lr((K,J))$ is finite if and only if the lattice of all ideals of the
coefficient ring is finite. Note also that the maximal ideal of an arbitrary
local principal ideal ring is strongly maximal.

We now find combinatorial expression of the number of all coordinate ideals in
$R_n lr((K,J))$ when $K$ is a local ring with a principal maximal ideal $J$
which is nilpotent of degree $s$. Then all ideals of the ring $K$ are exhausted
by the following $s+1$ ideals:
$ J^0=K, quad J, quad J^2, quad J^3, quad dots, quad J^(s-1), quad J^s=0. $
Indeed, write $J=(t)$. Every nonzero element is $t^k u$ for a unit $u$: choose
the largest $k$ for which the element belongs to $J^k$ and factor out $t^k$. The
remaining factor is outside $J$ and hence invertible. Choosing the least such
$k$ in a nonzero ideal shows that the ideal is $J^k$. Thus the coordinate
coefficient ideals are precisely these powers.

The staircase description can also be read directly from their exponents. Write
$I_(i j)=J^(a_(i j))$, with $a_(i j)=s$ for a zero coefficient ideal.
Multiplication by the matrix units of $R_n lr((K,J))$ says that exponents cannot
increase when a position moves down or left, and cannot increase by more than 1
when it moves up or right. If $m=a_(n 1)$, all exponents therefore lie between
$m$ and $min(m+2, s)$. The positions of exponent $m$ form a downward-left
staircase $Lc$. Multiplication of these positions by $J$ forces exponent at most
$m+1$ in the rows $i>=i_1$ and columns $j<=j_r$. The remaining positions of
exponent $m+1$, when $m+1<s$, form a downward-left staircase in the rectangle
$1<=i<i_1$, $j_r<j<=n$; these are precisely the free corners of $Lc'$. All other
coefficients are $J^(m+2)$, or zero if $m+2>=s$. Conversely these staircases
satisfy each matrix-unit multiplication condition. Their corners are uniquely
determined by the exponent array; when $m=s-1$, the free staircase is empty.

Theorem~@th:l2013-ideals-diagonal-invariant-description shows that the number of
all coordinate ideals of the ring $R_n lr((K,J))$ is a function $Omega(n, s)$
from the numbers $n$ and $s$.

We denote by $Omega^+(n)$ the number of all sets of corners $(Lc,Lc')$ of degree
$n$ with $i>j$ for all $(i,j) in Lc$, and by $Omega^0(n)$ the number of all
staircases $Lc$ in sets of corners @eq:l2013-ideals-primary-corners.

Let $J!=0$ and hence $s>=2$. Since $I(T;Lc,Lc') subset.eq R_n lr((K,J))$ so we
have in @eq:l2013-ideals-coordinate-ideal either $T=K$ and $i>j$ for all
$(i,j) in Lc$ or $T subset.eq J$. Therefore the number of all ideals
@eq:l2013-ideals-coordinate-ideal with $T=K$ is equal to the number
$Omega^+(n)$. On the other hand, every ideal @eq:l2013-ideals-coordinate-ideal
with nonzero $T$ and $J T=0$ can be written in the form $I(J^(s-1),Lc,Lc')$ with
$q=0$ in @eq:l2013-ideals-secondary-corners. Thus, the number of all such ideals
is equal to $Omega^0(n)$.
