"""Exact checks of Levchuk 1976, Example 1 and adjacent misprints.

Run with ``sage -python checks/sage/example.py``; assertions require no -O.
Example 1 uses ZZ and a polynomial ring over ZZ. The field counterexample
to Theorem 2 uses QQ, as required by the theorem's hypotheses. Printed
readings are literals from pp. 565–571. False printed assertions are kept
next to corrections. No approximate arithmetic is used.

Coverage: the two explicit matrices of Example 1 (eq:even-example), the
sign identity on p. 566, one admissible Lie ideal contradicting the printed
exception of Theorem 2 (th:lie-ideals), a proper abelian ideal contradicting
the literal corollary on p. 570 (cor:domain-abelian), and centralizers of
rectangular ideals in NT(n,ZZ), 2 <= n <= 6 (lem:centralizers).
These checks do not prove any complete general theorem of the article.
"""

from sage.all import ZZ, QQ, FreeModule, PolynomialRing, matrix, zero_matrix

COUNT = 0


def check(condition):
    global COUNT
    assert condition
    COUNT += 1


def refuted(condition):
    check(not condition)


def elementary(n, i, j, coefficient=1):
    result = zero_matrix(ZZ, n)
    result[i - 1, j - 1] = coefficient
    return result


def bracket(left, right):
    return left * right - right * left


def compose(left, right):
    return left + right + left * right


def parameter_matrix(a=0, b=0, c=0, d=0, s=0, t=0, x=0, y=0, z=0,
                     quadratic=True, base=ZZ):
    parameters = (a, b, c, d, s, t, x, y, z)
    if base == ZZ:
        assert all(value in ZZ and value % 2 == 0 for value in parameters)
    return matrix(base, [
        [0, 0, 0, 0, 0],
        [a, 0, 0, 0, 0],
        [4 * s - 2 * y, 2 * a, 0, 0, 0],
        [2 * (s + x) + 4 * b,
         4 * (y + z) + a + (2 * a**2 if quadratic else 0),
         2 * a, 0, 0],
        [2 * d, 2 * (t + x) + 4 * c, 4 * t - 2 * z, a, 0],
    ])


def necessary_membership_condition(candidate, quadratic):
    """A necessary congruence, obtained from the printed even parameters.

    For s=2S,t=2T,x=2X,y=2Y,z=2Z,b=2B,c=2C, write
    p=c31/4=2S-Y, q=c53/4=2T-Z, r=c41/4=S+X+2B,
    u=c52/4=T+X+2C, v=(c42-a-2a^2)/8=Y+Z.
    Then v+p+q-2r+2u=4T-4B+4C must be divisible by 4.
    H1 uses v=(c42-a)/8 instead. This is only a necessary condition.
    """
    a = candidate[1, 0]
    adjusted = candidate[3, 1] - a - (2 * a**2 if quadratic else 0)
    if adjusted % 8 != 0:
        return False
    entries = [candidate[2, 0], candidate[4, 2],
               candidate[3, 0], candidate[4, 1]]
    if any(entry % 4 != 0 for entry in entries):
        return False
    p, q, r, u = [entry // 4 for entry in entries]
    v = adjusted // 8
    return (v + p + q - 2 * r + 2 * u) % 4 == 0


def example():
    pi2 = parameter_matrix(2)
    pi4 = parameter_matrix(4)
    expected = 16 * elementary(5, 4, 2)
    check(pi4 - 2 * pi2 == expected)
    check(necessary_membership_condition(pi2, quadratic=True))
    check(not necessary_membership_condition(expected, quadratic=True))
    check(not necessary_membership_condition(expected, quadratic=False))
    sigma = parameter_matrix(2, quadratic=False)
    left = bracket(sigma, 2 * elementary(5, 2, 1))
    right = bracket(2 * elementary(5, 5, 4), sigma)
    term = compose(sigma, -sigma)
    # p. 566 as printed: the first two terms have plus signs.
    refuted(left + right - term == expected)
    check(left + right - term == expected
          + 16 * elementary(5, 3, 1) + 8 * elementary(5, 4, 1)
          + 8 * elementary(5, 5, 2) + 16 * elementary(5, 5, 3))
    # Minimal correction: reverse the first two signs.
    check(-left - right - term == expected)
    # H1 is exactly the ZZ-module generated by the nine even parameters.
    ambient = FreeModule(ZZ, 25)
    names = ("a", "b", "c", "d", "s", "t", "x", "y", "z")
    generators = [parameter_matrix(**{name: 2}, quadratic=False)
                  for name in names]
    ideal = ambient.submodule([ambient(value.list()) for value in generators])
    units = [2 * elementary(5, i, j)
             for i in range(2, 6) for j in range(1, i)]
    for value in generators:
        for unit in units:
            check(ambient(bracket(value, unit).list()) in ideal)
    check(ambient(sigma.list()) in ideal)
    check(ambient(expected.list()) not in ideal)
    check(ambient(compose(sigma, -sigma).list()) not in ideal)
    # Polynomial coefficients over ZZ establish closure and inverses of H
    # for all even parameters, using the exact lattice H1 above.
    ring = PolynomialRing(ZZ, [f"{name}{side}" for side in (1, 2)
                              for name in names])
    first = parameter_matrix(*[2 * var for var in ring.gens()[:9]],
                             base=ring)
    second = parameter_matrix(*[2 * var for var in ring.gens()[9:]],
                              base=ring)
    e42 = elementary(5, 4, 2).change_ring(ring)

    def coefficients_in_ideal(value):
        monomials = set(sum([entry.monomials() for entry in value.list()], []))
        for monomial in monomials:
            coefficient = ambient([entry.monomial_coefficient(monomial)
                                   for entry in value.list()])
            check(coefficient in ideal)

    product = compose(first, second)
    a = product[1, 0]
    coefficients_in_ideal(product - 2 * a**2 * e42)
    inverse = -first + first**2 - first**3 + first**4
    a_inverse = inverse[1, 0]
    coefficients_in_ideal(inverse - 2 * a_inverse**2 * e42)
    check(compose(first, inverse) == zero_matrix(ring, 5))
    # Lie brackets with generators suffice for normality by Lemma 3.
    for unit in units:
        value = bracket(first, unit.change_ring(ring))
        check(value[1, 0] == 0)
        coefficients_in_ideal(value)


def staircase_exception():
    """K=QQ: corners (s,k+1)=(4,3),(k,m)=(2,1)."""
    n = 4
    basis = [elementary(n, 2, 1) + elementary(n, 4, 3),
             elementary(n, 3, 1) - elementary(n, 4, 2),
             elementary(n, 4, 1)]
    ambient = FreeModule(QQ, n * n)
    ideal = ambient.submodule([ambient(value.list()) for value in basis])
    units = [elementary(n, i, j)
             for i in range(2, n + 1) for j in range(1, i)]
    for value in basis:
        for unit in units:
            check(ambient(bracket(value, unit).list()) in ideal)
    check(ideal.rank() == 3)
    # The printed first exception (s,k+1) is already a corner and does not
    # exempt (s,k)=(4,2). This admissible ideal has no isolated e42.
    refuted(ambient(elementary(n, 4, 2).list()) in ideal)
    check(ambient((elementary(n, 3, 1)
                   - elementary(n, 4, 2)).list()) in ideal)
    check(ambient(elementary(n, 4, 1).list()) in ideal)


def maximal_qualifier():
    """p. 570: NT(2,ZZ) is abelian; 2ZZ e21 is a proper abelian ideal."""
    ambient = FreeModule(ZZ, 4)
    e21 = elementary(2, 2, 1)
    proper = ambient.submodule([ambient((2 * e21).list())])
    listed = ambient.submodule([ambient(e21.list())])
    check(bracket(2 * e21, e21) == zero_matrix(ZZ, 2))
    check((2 * e21) * e21 == zero_matrix(ZZ, 2))
    check(proper.is_submodule(listed))
    refuted(proper == listed)


def rectangle_basis(n, k, ell):
    return [elementary(n, i, j)
            for i in range(k, n + 1) for j in range(1, ell + 1)]


def centralizers():
    """Check the additive sum interpretation of p. 571, in ranks 2..6."""
    for n in range(2, 7):
        units = [elementary(n, i, j)
                 for i in range(2, n + 1) for j in range(1, i)]
        ambient = FreeModule(ZZ, len(units))
        for k in range(2, n + 1):
            for ell in range(1, k):
                rectangle = rectangle_basis(n, k, ell)
                # Columns contain the commutators of each unknown coordinate.
                operator = matrix(ZZ, [
                    sum((bracket(unit, target).list()
                         for target in rectangle), [])
                    for unit in units
                ]).transpose()
                actual = ambient.submodule(operator.right_kernel().basis())
                support = {(i, j)
                           for boundary in range(ell, k)
                           for i in range(boundary + 1, n + 1)
                           for j in range(1, boundary + 1)}
                expected = ambient.submodule([
                    ambient([int(unit[i - 1, j - 1] == 1)
                             for unit in units]) for i, j in support
                ])
                check(actual == expected)
    # Interpreting concatenation as associative multiplication is false.
    ambient = FreeModule(ZZ, 9)
    left = rectangle_basis(3, 3, 2)
    right = rectangle_basis(3, 2, 1)
    product = ambient.submodule([ambient((a * b).list())
                                 for a in left for b in right])
    corrected = ambient.submodule([ambient(value.list())
                                   for value in left + right])
    refuted(product == corrected)
    check(ambient(elementary(3, 2, 1).list()) not in product)
    check(bracket(elementary(3, 2, 1), elementary(3, 3, 1))
          == zero_matrix(ZZ, 3))


if __name__ == "__main__":
    example()
    staircase_exception()
    maximal_qualifier()
    centralizers()
    print(f"ok example: {COUNT} checks")
