#import "defs.typ": *

=== Structural connections of associated Lie ring and adjoint group
<sec:l2000-ideals-structural>

Recall that an ideal $H$ of the associative ring $R$ is called quasi-regular, if
$H$ is a group with respect to the adjoint multiplication $a compose b=a+b+a b$,
cf. [@bib:l2000-ideals-Hungerford1974]. A ring
#source(4, printed: "3505")
$R$ is called a radical (Jacobson) ring, if $(R,compose)$ is a group (adjoint
group), that is, for each element $a in R$ there exists an element $a' in R$
such that $a compose a'=a' compose a=0$. If $a$ is a nilpotent element, then
$a'=-a+a^2-a^3+dots$. On the other hand, every associative ring $R$ is also
associated Lie ring $(R,+,ast)$, where $ast$ is the associated Lie
multiplication $a ast b=a b-b a$. It is clear that each ideal of the radical
ring is a normal subgroup of the adjoint group and an ideal of the associated
Lie ring, simultaneously. The following question is still open:

Characterize radical rings $R$ such that the class $OmL(R)$ of all ideals of
associated Lie ring coincides with the class $OmG(R)$ of all normal subgroups of
the adjoint group [@bib:l2000-ideals-Kourovka1992, question~10.19].

Other relations between the adjoint group of a radical ring and the associated
Lie ring were investigated by A.~I.~Mal’cev [@bib:l2000-ideals-Malcev1949] and
S.~A.~Jennings [@bib:l2000-ideals-Jennings1955].

Taking into account relations
$ (x e_(i i))'=x' e_(i i), quad (x e_(i j))'=-x e_(i j), quad i!=j, $
we can say that the ring $R_n lr((K,J))=NT_n lr((K))+M_n lr((J))$ is radical if
and only if $J$ is a quasi-regular ideal of the associative ring $K$. It was
shown in [@bib:l2000-ideals-Levchuk1976] that
$OmL(NT_n lr((K)))=OmG(NT_n lr((K)))$, if the ring $K$ is generated by the set
${x y | x,y in K}$, i.e. $K=K^2$. It does not hold when $K=2 ZZ$, $n>=5$.
Examples of non-nilpotent radical rings $R$ with the equality $OmL(R)=OmG(R)$
were constructed in [@bib:l2000-ideals-Levchuk1987]. On the other hand, we have

#example[
  Let $J$ be a quasi-regular ideal of an associative commutative ring $K$ with
  identity and $R=R_n lr((K,J))$, $n>=2$. Let $e$ be an identity $n times n$
  matrix. The following map $pi: alpha arrow.r e+alpha$ $(alpha in R)$ is a
  monomorphism between the adjoint group of the ring $R$ and $GL_n lr((K))$.
  Assume $H=pi^(-1) lr((pi(R) inter SL_n lr((K))))$. It is clear that $H$ is a
  normal subgroup of the adjoint group of $R$. If $a e_11+b e_22 in H$, then
  $1=(1+a)(1+b)=1+a compose b$ and $b=a'$. Thus
  $a(e_11-e_22)=a e_12 ast e_21 in H$ $(a in J)$ holds only when $a'=-a$ and
  hence $a^2=0$. Therefore, if the ideal $J$ contains an element $x$ satisfying
  $x^2!=0$, then the normal subgroup $H$ of the adjoint group of the ring $R$ is
  not an ideal of the associated Lie ring and moreover it is not an ideal of the
  groupoid $(R,ast)$.
] <exm:l2000-ideals-determinant-kernel>

It was shown in [@bib:l2000-ideals-Levchuk1976,
Lemma~@lem:l1976-normal-groupoid] that for arbitrary subgroup $H$ of the adjoint
group of the ring $R=NT_n lr((K))$ over any associative ring $K$ the following
two conditions are equivalent:

#enum(
  numbering: "(i)",
  [$H$ is a normal subgroup of adjoint group $(R,compose)$;],
  [#source(5, printed: "3506")
    $H$ is an ideal of the groupoid $(R,ast)$.],
)

In [@bib:l2000-ideals-Levchuk1976, Remark~@rem:l1976-normal-groupoid-question]
and in [@bib:l2000-ideals-Kourovka1980, question~6.19] it was asked whether the
above conditions (i) and (ii) are equivalent for any subgroup $H$ of the adjoint
group of any nilpotent associative ring $R$.

It was shown that this question has a negative answer in general case.
E.~I.~Khukhro (cf. comments to the question~6.19 in
[@bib:l2000-ideals-Kourovka1980]) gave the first counterexample in the case of
$R$ to be a free nilpotent algebra of nilpotency class~3 over the field $GF(2)$
generated by two elements, see also [@bib:l2000-ideals-Kuzucuoglu1998].
Example~@exm:l2000-ideals-determinant-kernel shows that for rings
$R_n lr((K,J))$ with $J!=0$ the answer to the question is usually negative.
