#import "defs.typ": *
#import "diagrams.typ": ideal-staircases

=== The construction of ideals <sec:l2000-ideals-construction>

Throughout this section $K$ will denote a commutative (associative) ring with
identity and $J$ will be an ideal of $K$. First we will distinguish some special
ideals of the ring $R_n lr((K,J))$. Consider following ordered sets of matrices
positions
$ Lc={(i_1,j_1),(i_2,j_2),dots,(i_r,j_r)}, quad r>=1, $
<eq:l2000-ideals-corners>
$ 1<=j_1<j_2<dots<j_r<=n, quad 1<=i_1<i_2<dots<i_r<=n; $
$ Lc'={(k_1,m_1),(k_2,m_2),dots,(k_q,m_q)}, quad q>=0, $
<eq:l2000-ideals-secondary-corners>
$ j_r<m_1<m_2<dots<m_q<=n, quad 1<=k_1<k_2<dots<k_q<i_1. $

We refer to $Lc$ as a “set of corners” of degree $n$ (compare with
[@bib:l2000-ideals-Dubisch1951, Sect.~7], [@bib:l2000-ideals-Levchuk1976,
§~@sec:l1976-lie-ideals]). We also allow the possibility that $Lc'=nothing$.
Choose a $J$-submodule $T$ of $K$. We now consider all $J$-submodules $A$ of the
ring $R_n lr((K,J))$ with the following conditions (i)–(iv):

#enum(
  numbering: "(i)",
  [There exist sets $Lc$ and $Lc'$ defined by @eq:l2000-ideals-corners and
    @eq:l2000-ideals-secondary-corners such that
    $
      J B subset.eq A subset.eq B, quad "where"
      B=sum_((i,j) in Lc)T e_(i j)+sum_((k,m) in Lc')(J T)e_(k m);
    $],
  [If $J T=J T J$ then $Lc'=nothing$ and also $Lc={(1,n)}$ when $J T=T$;],
  [The ideal of $K$ generated by $pi_(i j) lr((A))$ is equal to $T$ if
    $(n,1)!=(i,j) in Lc$ and $pi_(n 1) lr((A))=T$, if $Lc={(n,1)}$;],
  [$pi_(k m) lr((A))$ generates the ideal $J T$ for all $(k,m) in Lc'$.],
)

We call every $J$-submodule $A$ with (i)–(iv) a _T-boundary_ in $R_n lr((K,J))$.
Notice that we can determine a $T$-boundary $A=A(T;Lc,Lc')$ with $Lc={(n,1)}$
for any
#source(6, printed: "3507")
$J$-submodule $T$ of $K$. If $Lc!={(n,1)}$ then $T$ is an ideal of $K$. It is
clear that either $T subset.eq J$ or $i>j$ for all $(i,j) in Lc$ because
$A subset.eq R_n lr((K,J))$.

We now describe the ideal of $R_n lr((K,J))$ which is generated by any
$T$-boundary $A$. Regard the $n times n$ matrix as a square array of $n^2$
points $(i,j)$ (matrix position). Consider the following partial ordering:
$(i,j)<(k,m)$ (or $(k,m)>(i,j)$), if $i<=k$, $m<=j$ and $(i,j)!=(k,m)$. For any
additive subgroup $L$ of $K$ we denote by $N_(i j) lr((L))$ (resp. by
$Q_(i j) lr((L))$) the additive group generated by sets $L e_(k m)$ for all
$(k,m)>=(i,j)$ (resp. $(k,m)>(i,j)$). It can be easily shown that the ideal of
the ring $R_n lr((K,J))$ generated by any $T$-boundary $A=A(T;Lc,Lc')$ is equal
to
$
               I(A)=A+sum_((i,j) in Lc)Q_(i j) lr((T))
               +N_(i_1,n) lr((T J))+N_(1,j_r) lr((J T)) & \
  +M_n lr((J T J))+sum_((k,m) in Lc')Q_(k m) lr((J T)). &
$ <eq:l2000-ideals-generated-boundary>

We associate “staircases” with sets $Lc$ and $Lc'$ as in
[@bib:l2000-ideals-Dubisch1951], [@bib:l2000-ideals-Levchuk1976]. Then we can
compare with the ideal $I(A)$ the following matrix.

#figure(
  ideal-staircases(),
  caption: [#counted("fig", n => [Figure #n.])],
  supplement: none,
  numbering: none,
)
<fig:l2000-ideals-staircases>

Now we shall show that in certain cases all ideals of the ring $R_n lr((K,J))$
are ideals $I(A)$.

#definition[
  An ideal $J$ of a ring $K$ is called a strongly maximal ideal if for any
  $J$-submodule $L$ of $K$ every ideal of $K$ which is between a $J$-submodule
  $L$ and $J L$ is equal to $L$ or $J L$.
] <def:l2000-ideals-strongly-maximal>

#source(7, printed: "3508")
Let $J$ be a strongly maximal ideal of a ring $K$.

#theorem[
  If $H$ is any ideal of the ring $R_n lr((K,J))$, $n>=2$, then there exists a
  unique $pi_(n 1) lr((H))$-boundary $A$ in $R_n lr((K,J))$ such that $H=I(A)$.
] <th:l2000-ideals-boundary-classification>

We now require following lemmas.

#lemma[
  Let $J$ be an arbitrary ideal of $K$ and let $H$ be an ideal of the ring
  $R_n lr((K,J))$ and $H_(u v)=pi_(u v) lr((H))$. Then
  $J H_(u v) subset.eq H_(i v) inter H_(u j)$ for all $i,j,u,v$, and
  $
    J^2 T subset.eq H_(u v) subset.eq K H_(u v) subset.eq H_(i j) subset.eq T
    quad "for all" (u,v)<(i,j),
  $ <eq:l2000-ideals-projections>
  where $T=H_(n 1)$. In particular, all projections $H_(u v)$ are $J$-submodules
  of $K$ and
  $ M_n lr((J^2 T)) subset.eq H subset.eq M_n lr((T)). $
  <eq:l2000-ideals-projection-bounds>
] <lem:l2000-ideals-projection-inclusions>

#proof[
  Notice that the product of matrices $e_(k i) alpha$ can have nonzero entries
  only in $k$-th row which is equal to $i$-th row of $alpha$. Using the
  inclusion $(K e_(m i))H subset.eq H$ it follows $K H_(i j) subset.eq H_(m j)$
  for $m>i$. Similarly, we have $K H_(j m) subset.eq H_(j i)$ for $m>i$.
  Combining these inclusions we get $K H_(u v) subset.eq H_(i j) subset.eq T$
  for all $(u,v)<(i,j)$ and hence $H subset.eq M_n lr((T))$. The ideal $H$
  contains a set $J(e_(i u)H+H e_(v j))$ and hence
  $J H_(u v) subset.eq H_(i v) inter H_(u j)$. Since the additive group of
  $M_n lr((J^2 T))$ is generated by its elementary matrices and
  $ (J^2 H_(u v))e_(i j)=(J e_(i u))H(J e_(v j)) subset.eq H $
  we derive $M_n lr((J^2 T)) subset.eq H$ and @eq:l2000-ideals-projections which
  conclude the proof.
]

Let $Lc(H)$ be the set of all minimal (with respect to the relation $<=$)
matrices positions $(i,j)$ such that $H_(i j)$ generates an ideal of $K$ which
contains $T=H_(n 1)$. It is clear that the set $Lc(H)$ is defined uniquely for
$H$.

#lemma[
  Keeping notation of Lemma~@lem:l2000-ideals-projection-inclusions the
  following hold:
  #enum(
    numbering: "(i)",
    [The set $Lc=Lc(H)$ is a set of corners which is defined by
      @eq:l2000-ideals-corners;],
    [$H_(i n) inter H_(1 j) supset.eq J T$ and $H_(k m)=T$ for all $(i,j) in Lc$
      and $(k,m)>(i,j)$;],
    [The $J$-submodule $T$ is an ideal of $K$ when $Lc!={(n,1)}$.],
  )
] <lem:l2000-ideals-corner-projections>

#proof[
  Since $T=H_(n 1) subset.eq K T$, the set $Lc(H)$ is non-empty. Suppose that
  $(i,j) in Lc(H)$. Taking into account @eq:l2000-ideals-projections and the
  inclusion $T subset.eq K H_(i j)$, we obtain
  $ K H_(i j)=H_(k m)=T quad "for all" (k,m)>(i,j). $
  #source(8, printed: "3509")
  Therefore the set $Lc=Lc(H)$ is a set of corners as in
  @eq:l2000-ideals-corners. Also, if $Lc!={(n,1)}$, then $T$ is an ideal of $K$.
  Using Lemma~@lem:l2000-ideals-projection-inclusions and the equality
  $H_(n 1)=T$ we obtain
  $H_(i n) inter H_(1 j) supset.eq J H_(i j)=J K H_(i j)=J T$ for all
  $(i,j) in Lc$ and our lemma is proved.
]

#proof(head: [Proof of Theorem~@th:l2000-ideals-boundary-classification.])[
  Suppose that $H_(u v)=pi_(u v) lr((H))$, $T=H_(n 1)$ and $Lc=Lc(H)$. If
  $Lc={(1,n)}$, in particular when $T=J T$, then we have
  $H=H_(1 n)e_(1 n)+Q_(1 n) lr((T))$ since
  $
    H supset.eq K(e_(u i)H+H e_(j v)) supset.eq (K H_(i j))e_(u v),
    quad i<u, quad v<j.
  $ <eq:l2000-ideals-isolating-products>
  Therefore, in this case $H_(1 n)e_(1 n)$ is a unique $T$-boundary $A$ such
  that $H=I(A)$. Assume that $Lc!={(1,n)}$. Then we have $T!=J T$. Choose an
  arbitrary matrix position $(s,t)$ which is placed in the set
  $ {(i_1-1,1),(i_2-1,j_1+1),dots,(i_r-1,j_(r-1)+1),(n,j_r+1)}. $
  <eq:l2000-ideals-staircase-complement>
  It is clear that $(s,t)>=(1,j_r)$ or $(s,t)>=(i_1,n)$. Hence
  $T supset.eq K H_(s t) supset.eq H_(s t) supset.eq J T$ by
  @eq:l2000-ideals-projections and by
  Lemma~@lem:l2000-ideals-corner-projections(ii). By definition of $Lc(H)$ the
  $J$-submodule $H_(s t)$ generates the ideal of $K$ which does not contain $T$.
  Now, assume that $J$ is a strongly maximal ideal of $K$. Then we conclude
  $K H_(s t)=J T=H_(s t)$.

  Let $(k,m)$ be an arbitrary matrix position which is placed above staircase
  $Lc(H)$. Then there exists a matrix position $(s,t)>=(k,m)$ which is in the
  set @eq:l2000-ideals-staircase-complement. Therefore
  $J T=H_(s t) supset.eq K H_(k m) supset.eq H_(k m) supset.eq J(J T)$ by
  @eq:l2000-ideals-projections. This implies that either the set $H_(k m)$
  generates the ideal $J T$ or $H_(k m)=J^2 T$. Notice that if $(k,m)>=(i_1,n)$
  or $(k,m)>=(1,j_r)$, then $H_(k m) supset.eq J T$ by
  Lemma~@lem:l2000-ideals-corner-projections(ii) and
  @eq:l2000-ideals-projections.

  If $J T!=J^2 T$ we define $Lc'(H)$ to be the set of all minimal matrices
  positions $(k,m)$ such that $1<=k<i_1$, $j_r<m<=n$ and that the $J$-submodule
  $H_(k m)$ generates the ideal $J T$. If $J T=J^2 T$ then $Lc'=nothing$. Thus,
  for $H$ the set $Lc'=Lc'(H)$ is defined uniquely and $Lc'=Lc'(H)$ is a set
  @eq:l2000-ideals-secondary-corners.

  Suppose that $(i,j) in Lc$. Then $J H_(i j)=J K H_(i j)=J T$ and hence
  $ (J e_(i i))H=(J T)e_(i j) quad mod Q_(i j) lr((J T))+M_n lr((J^2 T)). $
  Taking into account @eq:l2000-ideals-isolating-products we obtain
  $N_(1 j) lr((J T)) subset.eq H$ and similarly,
  $N_(i n) lr((J T)) subset.eq H$. Therefore
  $N_(i_1,n) lr((J T))+N_(1,j_r) lr((J T))+M_n lr((J^2 T)) subset.eq H$. Using
  @eq:l2000-ideals-isolating-products it is easy to show that
  $
    Q_(i j) lr((T))+Q_(k m) lr((J T)) subset.eq H
    quad "for all" (i,j) in Lc quad "and" (k,m) in Lc'.
  $

  We choose the set $A$ of all matrices $alpha=||a_(u v)|| in H$ with
  $a_(u v)=0$ if $(u,v) in.not$
  #source(9, printed: "3510")
  $Lc union Lc'$. It is clear that the set $A=A(T;Lc,Lc')$ is a $J$-submodule of
  $R_n lr((K,J))$ with conditions (i)–(iv). Therefore, the set $A$ is a
  $T$-boundary and $H=I(A)$. Finally, $T$-boundary $A$ is defined uniquely for
  $H$. This completes the proof.
]

Thus, Theorem~@th:l2000-ideals-boundary-classification describes all ideals of
the ring $R_n lr((K,J))$ when $J$ is a strongly maximal ideal of $K$. The next
proposition indicates examples of such ideals.

#proposition[
  The zero ideal of any field and every maximal ideal of the rings $ZZ$ and
  $ZZ_m$, $m>1$, are strongly maximal ideals.
] <prop:l2000-ideals-strongly-maximal-examples>

#proof[Straightforward.]

Observe that the case $J=0$ of Theorem~@th:l2000-ideals-boundary-classification
gives well known description of ideals of the ring or algebra $NT_n lr((K))$
over a field $K$ (see [@bib:l2000-ideals-Dubisch1951, Thm.~9] and
[@bib:l2000-ideals-Levchuk1976, §~@sec:l1976-lie-ideals]).

It is clear that any strongly maximal ideal of a ring $K$, which is not equal to
$K$, is maximal. We conclude this section with an example.

#example[
  Consider the ring $K=ZZ[x]$ of polynomials in one indeterminate $x$ over $ZZ$.
  The ideal $J=p ZZ+x K$ for an arbitrary prime $p$ is maximal and
  $ J^s=p^s ZZ+p^(s-1)x ZZ+dots+p x^(s-1)ZZ+x^s K. $
  Let $T=J^s$ and $s>=1$. The quotient-ring $T/(J T)$ is a ring with zero
  multiplication and with elementary abelian additive group of order $p^(s+1)$.
  Thus between $T$ and $J T$ we can find chains of ideals of $K$ with arbitrary
  finite length varying $s$ suitably. Hence, the ideal $J$ of $K$ is not
  strongly maximal.
] <exm:l2000-ideals-polynomial-maximal>
