#import "defs.typ": *

=== Construction and enumeration of ideals <sec:l2001-enumeration-construction>

The unipotent subgroup $U Phi lr((K))$ of the Chevalley group of the type $Phi$
over arbitrary field $K$ is generated by root subgroups corresponding to
positive roots $r in Phi^+$. Also, the subgroup $U_G lr((K))$ is defined for
twisted types $G = ""^m Phi$, cf. R.~Carter [@bib:l2001-enumeration-Carter1972,
5.1 and 13.6]. All characteristic and all normal $D$-invariant subgroups of the
group $U_G lr((K))$ have been enumerated in [@bib:l2001-enumeration-Levchuk1990]
and [@bib:l2001-enumeration-Egorychev1996]. For classic Lie-types $G$ the
following theorems are proved in [@bib:l2001-enumeration-Egorychev1993] and
[@bib:l2001-enumeration-Egorychev1996].

#theorem[
  The number $c(G; K)$ of characteristic subgroups of the classic Lie-type group
  $U_G lr((K))$ over arbitrary field $K$ of order greater then 2 is equal to:
  $
    binom(n, floor(n/2)) quad "for" G = A_(n-1) "or" ""^2 A_(n-1), n > 1;
  $
  $
    binom(2n, n) quad "for" G = B_n quad (n > 3, 2K = K)
    "or" C_n quad (n >= 2, 3K = 0, abs(K) > 3)
    "or" D_(n+1) quad (n > 3)
    "or" ""^2 D_(n+1) quad (n >= 3, abs(K) > 4);
  $
  $
    4^(n-1) + binom(2n - 1, n) quad "for" 2K = 0,
    G = B_n "or" C_n, n >= 2;
  $
  $
    binom(2n, n) - 1 quad "for" G = C_n, 6K = K;
  $
  $
    binom(2n, n) - 2 quad "for" G = C_n, n > 2, abs(K) = 3.
  $
] <th:l2001-enumeration-characteristic-count>

#theorem[
  #source(3, printed: 22)The number $d(G; K)$ of normal $D$-invariant subgroups
  of the classic Lie-type group $U_G lr((K))$ over arbitrary field $K$ of order
  greater then 2 is equal to:
  $
    1/n binom(2n, n - 1) quad "for" G = A_(n-1), n > 1;
  $
  $
    binom(n, floor(n/2)) quad "for" G = ""^2 A_(n-1), n > 1;
  $
  $
    binom(2n, n) quad "for" G = ""^2 D_(n+1), n >= 2, abs(K) > 4,
    "or" K = 2K, G = B_n "or" C_n, n >= 1;
  $
  $
    binom(2n - 1, n) + 4^(n-1) quad "for" 2K = 0,
    G = B_n "or" C_n, n > 2;
  $
  $
    binom(2n - 1, n) + binom(2n - 2, n) quad "for" G = D_n, n > 2.
  $
] <th:l2001-enumeration-normal-count>

By [@bib:l2001-enumeration-Levchuk1990], we may consider the group
$U Phi lr((K))$ as the adjoint group of the algebra $N Phi lr((K))$. Further,
for roots $r, s in Phi$, we suppose $s <= r$, if $r - s$ is linear combination
of fundamental roots with non-negative coefficients. Roots $r, s$ are called
incident ones, if $r <= s$ or $s <= r$. For any set of pairwise non-incident
roots $r_1, r_2, dots, r_m in Phi^+$ the subgroup $T(r_1, dots, r_m)$ of adjoint
group $N Phi lr((K)) approx U Phi lr((K))$ is selected. By definition it is
generated by all possible root subgroups corresponding to roots $s$, such that
$r_i <= s$ for some $i$.

#lemma(title: [[@bib:l2001-enumeration-Egorychev1996]])[
  Subgroups $T(r_1, dots, r_m)$ of the adjoint group $N Phi lr((K))$ of classic
  type are different for different sets of pairwise non-incident roots
  $r_1, r_2, dots, r_m in Phi^+$. All they are normal $D$-invariant subgroups
  and exhaust them if $abs(K) > 2$ and furthermore $2K = K$ at $G = B_n, C_n$.
] <lem:l2001-enumeration-root-ideals>

The subgroup $T(r_1, dots, r_m)$ of the adjoint group $N Phi lr((K))$ is also a
subalgebra of the Lie algebra $N Phi lr((K))$. Its basis is formed by elements
$e_s$ of Chevalley one upon the conditions $r_i <= s$ for some $i$. The
subalgebra $T(r_1, dots, r_m)$ is a $D$-invariant ideal of the Lie algebra
$N Phi lr((K))$. Conversely, upon the conditions of
Lemma~@lem:l2001-enumeration-root-ideals every $D$-invariant ideal of Lie ring
$N Phi lr((K))$ is a $D$-invariant normal subgroup of the adjoint group by #[
  [@bib:l2001-enumeration-Levchuk1982,
  Theorem~@th:l1982-parabolic-normal-basis-decomposition]
]. Hence, upon the conditions of Lemma~@lem:l2001-enumeration-root-ideals on
$Phi, K$, the number $Lambda(Phi; K)$ is equal to $d(Phi; K)$ and
Theorem~@th:l2001-enumeration-ideal-count follows from
Theorem~@th:l2001-enumeration-normal-count.

Using Theorem~@th:l1982-parabolic-normal-basis-decomposition and
Lemma~@lem:l1982-parabolic-three-blocks [@bib:l2001-enumeration-Levchuk1982] we
obtain that all $D$-invariant ideals of Lie ring $N C_n lr((K))$ ($abs(K) > 2$)
are generated $K$-linearly by elements of the form $e_s$, $s in Phi^+$, see also
[@bib:l2001-enumeration-Dubisch1951, §~5]. The case $2K = 0$, $Phi = B_n$ or
$C_n$ in Lemma~@lem:l2001-enumeration-root-ideals is substantially exclusive.
Here we have $[e_r, e_s] = e_r ast e_s = 2e_(r+s) = 0$ ($ast$ — Lie
multiplication in $N C_n lr((K))$) for any short roots $r, s$ such that $r + s$
is long one.

Let $T_0$ be a subalgebra of the algebra $N C_n lr((K))$, $2K = 0$, whose basis
is formed by elements $e_s$ for all possible short roots $s$. It turns out that
the minimal $D$-invariant ideal of the Lie ring $N C_n lr((K))$, containing an
element $e_r$ for arbitrary short root $r$, coincides with the intersection
$T(r) inter T_0$. Thus, the following lemma is true:

#lemma[
  Let ${r_1, dots, r_m}$ be an arbitrary (possibly empty) set of pairwise
  non-incident short roots from $Phi^+$. Let $M$ be some subset of long roots
  from $Phi^+$, and let, for each non-maximal root $r in M$, a number $k$ exist
  such that $1 <= k <= m$ and either $r_k <= r$ or $r_k <= r + q$ for a simple
  root $q$. Then
  $
    T_0 inter T(r_1, dots, r_m) + sum_(r in M) K e_r
  $ <eq:l2001-enumeration-characteristic-two-c-ideal>
  is a $D$-invariant ideal of the Lie ring $N C_n lr((K))$, $2K = 0$. All
  $D$-invariant ideals of the Lie ring $N C_n lr((K))$ are obtained in such
  manner.
] <lem:l2001-enumeration-characteristic-two-c-ideals>

Further, let’s use representation of the algebra $N Phi lr((K))$ of classic-type
by $Phi^+$-matrices, pointed out in [@bib:l2001-enumeration-Levchuk1990]. As
well as root notation
$
  epsilon_i - v epsilon_j = p_(i,v j), quad
  1 <= j <= i <= n, v in {0, 1, -1},
$

#import "diagrams/stepline.typ": stepline
#source(4, printed: 23)#drawing(stepline) <fig:l2001-enumeration-stepline>

see Tables I–IV [@bib:l2001-enumeration-Bourbaki1968]. If
$r_1 = p_(i_1,j_1), dots, r_m = p_(i_m,j_m)$, then a task of enumerating
subalgebras $T(r_1, dots, r_m)$ turns to be equivalent to that of enumerating
the steplines $L$ in corresponding $Phi^+$-matrix.

Also, let’s introduce an auxiliary table
$
  mat(

    , , , a_(0,0), , , ;
    , , a_(1,-1), a_(1,0), a_(1,1), , ;
    , , dots, dots, dots, , ;
    a_(n,-n), dots, a_(n,-1), a_(n,0), a_(n,1), dots, a_(n,n);
    delim: #none,
  )
$ <eq:l2001-enumeration-auxiliary-table>

It is obtained from $B_(n+1)^+$-matrix $norm(a_(u v))$
[@bib:l2001-enumeration-Levchuk1990], if $a_(u v)$ were renamed through
$a_(u-1,v)$. The number of all the steplines from $a_(i v)$ to $a_(k m)$
($v <= m <= k <= n$, $abs(v) <= i <= k$) is denoted by
$upright(N)[(i,v);(k,m)]$. The next formula arises from
Lemma~@lem:l2001-enumeration-characteristic-two-c-ideals:
$
  Lambda(C_n; K) = sum_(i=1)^n 2^(n-i+1) upright(N)[(i,-i+1);(n,n)].
$ <eq:l2001-enumeration-c-steplines>

#lemma[
  If $2K = 0$, $abs(K) > 2$, then#ed-note[The displayed decomposition is used
    for $n >= 2$. For $n=1$ the algebra is one-dimensional and
    $Lambda(B_1; K)=2$.]
  $
    Lambda(B_n; K) = d(A_n;K) + 2d(A_(n-1);K) - 2d(A_(n-2);K)
    + sum_(i=2)^n sum_(t=i)^n (t+1)
    upright(N)[(i,-i),(t,-1)] upright(N)[(t,1),(n,n)]
    + sum_(i=1)^(n-1) sum_(t=i)^(n-1) sum_(m=t+1)^n (t+1)
    upright(N)[(i,-i),(t,-2)] upright(N)[(m,1),(n,n)], quad n >= 2.
  $ <eq:l2001-enumeration-b-steplines>
] <lem:l2001-enumeration-b-steplines>

#proof[
  First of all let’s note that each $D$-invariant ideal of the Lie ring
  $N B_n lr((K))$, $2K = 0$, $abs(K) > 2$ is a subalgebra too, whose basis might
  be constructed by elements $e_r$ of the Chevalley basis. On other hand, the
  minimal ideal containing $K e_r$ is a subalgebra whose basis is formed by
  elements $e_s$ where $s$ runs over a certain set $R subset Phi^+$. More
  exactly $R = {s in Phi^+ | r <= s}$, excluding the following cases:

  + if $r$ is short root (i.e. $r = p_(i 0)$), then
    $R = {s in Phi^+ | r <= s, abs(s) = abs(r)}$;
  + if $r$ is long root, but $r+p$ is short one for a simple short root $p$,
    then $R$ consist of all possible roots $s$, $r <= s$ such that $s-p$ is not
    the short root.

  Again we can reduce the enumeration of all $D$-invariant ideals of the Lie
  ring $N B_n lr((K))$ to listing the definite ways in table
  @eq:l2001-enumeration-auxiliary-table. According to its enumeration the number
  $A$ of such ideals containing $e_(1,-1)$ is evidently equal to $d(A_n;K)$.

  #source(5, printed: 24)The number $B$ of ideals containing $e_(1,1)$ but not
  $e_(1,-1)$ is equal to doubled number of ideals containing $e_(0,0)$,
  $e_(1,-1)$ but not $e_(1,1)$. Therefore $B = 2[d(A_(n-1);K) - d(A_(n-2);K)]$.

  Let’s consider the ideals which do not contain $e_(1,1)$, $e_(1,-1)$. The
  number of such ideals $H$ which always contain $e_(t,-1)$, if $e_(t,1) in H$
  is denominated as $C$, and that of rest ideals — as $D$. Simple reasoning
  leads to expressions
  $
    C = sum_(i=2)^n sum_(t=i)^n (t+1)
    upright(N)[(i,-i),(t,-1)] upright(N)[(t,1),(n,n)],
  $
  $
    D = sum_(i=1)^(n-1) sum_(t=i)^(n-1) sum_(m=t+1)^n (t+1)
    upright(N)[(i,-i),(t,-2)] upright(N)[(m,1),(n,n)], quad n >= 2.
  $
  It remains to note that $Lambda(B_n; K) = A+B+C+D$. The Lemma is proved.
]

Thus the task of evaluating numbers $Lambda(Phi; K)$ turns our to be a purely
combinatorial one. It’s solution is obtained in
§~@sec:l2001-enumeration-lattice-paths and
§~@sec:l2001-enumeration-integral-sums, using methods of integral representation
of sums (the method of coefficients, G.~P.~Egorychev
[@bib:l2001-enumeration-Egorychev1989]) and of listing lattice paths (V.~Feller
[@bib:l2001-enumeration-Feller1967]).
